begin;
select plan(44);
select has_table('public','categories');
select has_table('public','job_descriptions');
select has_table('public','resumes');
select has_table('public','tailoring_jobs');
select has_table('public','user_profiles');
select has_table('public','industry_domain_categories');
select has_table('public','profiles');
select has_table('public','roles');
select has_table('public','user_roles');
select col_is_pk('public','categories','id');
select col_is_pk('public','job_descriptions','id');
select col_is_pk('public','resumes','id');
select col_is_pk('public','tailoring_jobs','id');
select col_is_pk('public','user_profiles','id');
select col_is_pk('public','profiles','id');
select has_column('public','profiles','status');
select has_index('public','job_descriptions','job_descriptions_user_normalized_url_key');
select fk_ok('public','job_descriptions','user_id','public','user_profiles','id');
select fk_ok('public','job_descriptions','industry_domain_category_id','public','industry_domain_categories','id');
select has_column('public','job_descriptions','location_text');
select has_column('public','job_descriptions','work_arrangement');
select has_column('public','job_descriptions','clearance_requirements');
select has_column('public','job_descriptions','travel_required');
select has_column('public','job_descriptions','travel_details');
select has_column('public','job_descriptions','structured_content');
select has_column('public','job_descriptions','industry_domain_category_id');
select has_column('public','job_descriptions','salary_min');
select has_column('public','job_descriptions','salary_max');
select has_column('public','job_descriptions','salary_currency');
select has_column('public','job_descriptions','salary_period');
select has_column('public','job_descriptions','salary_text');
select has_column('public','resumes','structured_content');
select has_column('public','resumes','structured_schema_version');
select is((select public from storage.buckets where id='original-resumes'),false,'original bucket private');
select is((select public from storage.buckets where id='tailored-resumes'),false,'tailored bucket private');
select is((select count(*)::integer from public.categories where parent_id is null),7,'seven primary categories');
select has_function('public','is_active_user',array['uuid']);
select has_function('public','has_role',array['text','uuid']);
select has_function('public','has_any_role',array['text[]','uuid']);
select has_function('public','get_my_access_context',array[]::text[]);
select is((select count(*)::integer from public.roles where active and is_system),5,'five active system roles');
select ok((select relrowsecurity from pg_class where oid='public.profiles'::regclass),'profiles RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.roles'::regclass),'roles RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.user_roles'::regclass),'user roles RLS enabled');
select * from finish();
rollback;
