begin;
select plan(20);
select has_table('public','applier_workload_settings','workload settings exists');
select has_table('public','application_assignment_batches','assignment batches exist');
select has_table('public','application_assignment_batch_results','assignment results exist');
select col_is_pk('public','applier_workload_settings','user_id','one settings row per Applier');
select col_not_null('public','applier_workload_settings','max_active_applications','capacity is required');
select has_function('public','list_applier_workloads_v08',array['text','boolean','boolean','integer','integer'],'workload function exists');
select has_function('public','preview_bulk_assignment_v08',array['uuid[]','uuid[]','text','jsonb'],'preview function exists');
select has_function('public','assign_applications_bulk_v08',array['jsonb','text','text','text','text'],'commit function exists');
select has_function('public','list_assignment_batches_v08',array['text','text','text','uuid','timestamptz','timestamptz','integer','integer'],'batch list exists');
select ok((select relrowsecurity from pg_class where oid='public.applier_workload_settings'::regclass),'settings RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.application_assignment_batches'::regclass),'batch RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.application_assignment_batch_results'::regclass),'result RLS enabled');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='applier_workload_settings' and policyname='managers read workload settings'),'settings manager policy exists');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='application_assignment_batches' and policyname='managers read assignment batches'),'batch manager policy exists');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='application_assignment_batch_results' and policyname='managers read assignment batch results'),'result manager policy exists');
select ok(not has_table_privilege('authenticated','public.applier_workload_settings','INSERT'),'authenticated cannot insert settings directly');
select ok(not has_table_privilege('authenticated','public.application_assignment_batches','INSERT'),'authenticated cannot insert batches directly');
select ok(not has_table_privilege('authenticated','public.application_assignment_batch_results','INSERT'),'authenticated cannot insert results directly');
select ok(not has_function_privilege('authenticated','public.bulk_assign_applications(uuid[],uuid,text)','EXECUTE'),'legacy bulk reassignment is retired');
select ok(has_function_privilege('authenticated','public.assign_applications_bulk_v08(jsonb,text,text,text,text)','EXECUTE'),'authenticated caller may invoke protected v0.8 commit');
select * from finish();
rollback;
