import{AppError}from"../shared/errors.js";import{validateResume}from"../shared/resume-validation.js";import{preserveSkills}from"../shared/skill-detection.js";import{apiRequest}from"./api-client.js";
async function token(client){const{data,error}=await client.auth.getSession();if(error||!data.session?.access_token)throw new AppError("SESSION_EXPIRED","Your session has expired. Sign in again.");return data.session.access_token;}
async function call(client,baseUrl,path,options={}){return(await apiRequest({baseUrl,path,token:await token(client),...options})).data;}
export async function createResume(client,baseUrl,userId,meta,file,checksum){const validation=validateResume(meta,file);if(!validation.valid)throw new AppError("RESUME_VALIDATION_FAILED","Review the resume fields.",Object.values(validation.errors).join(" "));const metadata={...meta,skills:preserveSkills(meta.skills),industries:[...new Set(meta.industries.map(x=>x.trim()).filter(Boolean))],checksum,structuredSchemaVersion:1};const body=new FormData();body.append("metadata",JSON.stringify(metadata));body.append("file",file,file.name);return call(client,baseUrl,"/api/v1/resumes",{method:"POST",body});}
export async function listResumes(client,baseUrl,{status="ACTIVE",categoryId="",search=""}={}){const q=new URLSearchParams({page:"1",pageSize:"100",sort:"updated_desc"});if(status!=="ALL")q.set("status",status);if(categoryId)q.set("categoryId",categoryId);if(search)q.set("search",search);return(await call(client,baseUrl,`/api/v1/resumes?${q}`)).items||[];}
export const eligibleResumes=(client,baseUrl,categoryId)=>listResumes(client,baseUrl,{status:"ACTIVE",categoryId});
export const setResumeStatus=(client,baseUrl,id,status)=>call(client,baseUrl,`/api/v1/resumes/${id}/status`,{method:"PATCH",body:{status}});
export const findActiveChecksum=(client,baseUrl,checksum)=>call(client,baseUrl,`/api/v1/resumes/checksum/${checksum}`);
export const updateResumeMetadata=(client,baseUrl,id,changes)=>call(client,baseUrl,`/api/v1/resumes/${id}`,{method:"PATCH",body:changes});
export async function openResumeFile(client,baseUrl,id,filename){const data=await call(client,baseUrl,`/api/v1/resumes/${id}/file-url`);const a=document.createElement("a");a.href=data.signedUrl;a.download=filename||"resume";a.target="_blank";a.rel="noopener";a.click();}
