import * as mammoth from "mammoth/mammoth.browser.js";
import * as pdfjs from "pdfjs-dist/legacy/build/pdf.mjs";
import { AppError } from "../shared/errors.js";
export function normalizeResumeText(text=""){return String(text).replace(/\0/g,"").replace(/\r\n?/g,"\n").replace(/\n{4,}/g,"\n\n\n").trim().slice(0,300000);}
export async function parseTxt(buffer){const bytes=new Uint8Array(buffer);if(bytes.some((b)=>b===0))throw new AppError("BINARY_TEXT_FILE","The TXT file appears to contain binary data.");return normalizeResumeText(new TextDecoder("utf-8",{fatal:true}).decode(bytes));}
export async function parseDocx(buffer){try{const result=await mammoth.extractRawText({arrayBuffer:buffer});const text=normalizeResumeText(result.value);if(!text)throw new Error("empty");return {text,warnings:result.messages.map((m)=>m.message)};}catch(error){throw new AppError("DOCX_PARSE_FAILED","The DOCX file could not be parsed.",error.message);}}
export async function parsePdf(buffer){try{if(typeof chrome!=="undefined"&&chrome.runtime)pdfjs.GlobalWorkerOptions.workerSrc=chrome.runtime.getURL("assets/pdf.worker.min.mjs");const pdf=await pdfjs.getDocument({data:new Uint8Array(buffer)}).promise;const pages=[];for(let pageNo=1;pageNo<=pdf.numPages;pageNo++){try{const content=await (await pdf.getPage(pageNo)).getTextContent();pages.push(content.items.map((item)=>item.str).join(" "));}catch(error){throw new AppError("PDF_PAGE_PARSE_FAILED",`PDF parsing failed on page ${pageNo}.`,error.message);}}const text=normalizeResumeText(pages.join("\n\n"));if(text.length<20)throw new AppError("PDF_NO_READABLE_TEXT","The PDF contains no readable text. Scanned PDFs require OCR, which is not supported.");return text;}catch(error){if(error instanceof AppError)throw error;throw new AppError("PDF_PARSE_FAILED","The PDF could not be parsed.",error.message);}}
export async function parseResumeFile(file){const buffer=await file.arrayBuffer();if(file.type==="text/plain")return {text:await parseTxt(buffer),warnings:[]};if(file.type==="application/pdf")return {text:await parsePdf(buffer),warnings:[]};if(file.type==="application/vnd.openxmlformats-officedocument.wordprocessingml.document")return parseDocx(buffer);throw new AppError("UNSUPPORTED_RESUME_TYPE","Only PDF, DOCX, and TXT resumes are supported.");}
export async function sha256Hex(buffer){const digest=await crypto.subtle.digest("SHA-256",buffer);return [...new Uint8Array(digest)].map((b)=>b.toString(16).padStart(2,"0")).join("");}
