import { AppError,safeError } from "../shared/errors.js";
import { buildStoragePath,validateResume } from "../shared/resume-validation.js";
import { canonicalizeSkills } from "../shared/skill-detection.js";
import { uploadOriginal,deleteOriginal } from "./storage-service.js";
export async function createResume(client,userId,meta,file,checksum){const validation=validateResume(meta,file);if(!validation.valid)throw new AppError("RESUME_VALIDATION_FAILED","Review the resume fields.",Object.values(validation.errors).join(" "));const id=crypto.randomUUID(),path=buildStoragePath(userId,id,file.name);await uploadOriginal(client,path,file);const row={id,candidate_name:meta.candidateName.trim(),resume_name:meta.resumeName.trim(),primary_category_id:meta.primaryCategoryId,subcategory_id:meta.subcategoryId||null,seniority:meta.seniority,skills:canonicalizeSkills(meta.skills),industries:[...new Set(meta.industries.map((x)=>x.trim()).filter(Boolean))],resume_text:meta.resumeText.trim(),structured_content:meta.structuredContent,structured_schema_version:1,storage_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size,file_sha256:checksum};const {data,error}=await client.from("resumes").insert(row).select("id,candidate_name,resume_name,primary_category_id,subcategory_id,seniority,skills,industries,resume_text,structured_content,structured_schema_version,storage_bucket,storage_path,original_filename,mime_type,file_size_bytes,file_sha256,status,created_at,updated_at").single();if(error){try{await deleteOriginal(client,path);}catch(cleanup){throw new AppError("RESUME_INSERT_AND_CLEANUP_FAILED","Resume metadata failed to save and the uploaded file could not be cleaned up.",cleanup.details);}throw safeError(error,"RESUME_DATABASE_INSERT_FAILED","Resume metadata could not be saved.");}return data;}
export async function listResumes(client,{status="ACTIVE",categoryId="",search=""}={}){let q=client.from("resumes").select("id,candidate_name,resume_name,primary_category_id,subcategory_id,seniority,skills,industries,storage_bucket,storage_path,original_filename,mime_type,file_size_bytes,file_sha256,status,created_at,updated_at").order("updated_at",{ascending:false}).limit(100);if(status!=="ALL")q=q.eq("status",status);if(categoryId)q=q.eq("primary_category_id",categoryId);if(search)q=q.ilike("candidate_name",`%${search.replace(/[%_]/g,"")}%`);const {data,error}=await q;if(error)throw safeError(error,"RESUME_LIST_FAILED","Resumes could not be loaded.");return data||[];}
export async function eligibleResumes(client,categoryId){return listResumes(client,{status:"ACTIVE",categoryId});}
export async function setResumeStatus(client,id,status){const {data,error}=await client.from("resumes").update({status}).eq("id",id).select("id,status").single();if(error)throw safeError(error,"RESUME_UPDATE_FAILED","Resume status could not be updated.");return data;}
export async function findActiveChecksum(client,checksum){const {data,error}=await client.from("resumes").select("id,candidate_name,resume_name").eq("file_sha256",checksum).eq("status","ACTIVE").limit(1);if(error)throw safeError(error,"CHECKSUM_LOOKUP_FAILED","The duplicate-file check failed.");return data?.[0]||null;}
export async function updateResumeMetadata(client,id,changes){const allowed={candidate_name:String(changes.candidateName||"").trim(),resume_name:String(changes.resumeName||"").trim(),primary_category_id:changes.primaryCategoryId,subcategory_id:changes.subcategoryId||null,seniority:changes.seniority,skills:canonicalizeSkills(changes.skills||[]),industries:[...new Set((changes.industries||[]).map((x)=>x.trim()).filter(Boolean))]};const {data,error}=await client.from("resumes").update(allowed).eq("id",id).select("id,candidate_name,resume_name,primary_category_id,subcategory_id,seniority,skills,industries,status,updated_at").single();if(error)throw safeError(error,"RESUME_UPDATE_FAILED","Resume metadata could not be updated.");return data;}
