import React,{useEffect,useMemo,useState}from"react";
import{Alert,App as AntApp,Button,Card,Descriptions,Empty,Flex,Form,Input,Select,Space,Table,Tag,Typography}from"antd";
import{formatDate,formatLabel}from"../../shared/formatters.js";
import{LoadingState,StatusTag}from"../../components/ui.jsx";
import{createTailoringRunnerTicket,getTailoringJob,getTailoringResumeUrl,getTailoringReviews,listTailoringJobs,listTailoringTemplates,materializeTailoredResume,reviewTailoringPreview,selectTailoringFormat,selectTailoringTemplate}from"./tailoring-service.js";

const{Text,Title,Paragraph}=Typography;
const STATUSES=["ALL","PENDING","PROCESSING","NEEDS_REVIEW","APPROVED","MATERIALIZING","COMPLETED","REJECTED","FAILED","CANCELLED"];
const one=value=>Array.isArray(value)?value[0]:value||{};
const go=hash=>location.assign(hash);

export function TailoringQueuePage({client,apiBaseUrl,reload}){
  const[status,setStatus]=useState("ALL"),[items,setItems]=useState(),[error,setError]=useState("");
  useEffect(()=>{let live=true;setItems();setError("");listTailoringJobs(client,apiBaseUrl,status).then(value=>live&&setItems(value)).catch(x=>live&&setError(x.message));return()=>{live=false;};},[client,apiBaseUrl,status,reload]);
  const columns=useMemo(()=>[
    {title:"Application",render:(_,row)=>one(row.applications).application_number?`#${one(row.applications).application_number}`:"Legacy queue"},
    {title:"Company",render:(_,row)=>one(row.job_descriptions).company||"—"},
    {title:"Job title",render:(_,row)=>one(row.job_descriptions).job_title||"—"},
    {title:"Resume",render:(_,row)=>{const original=one(row.resumes),tailored=one(row.tailored_resume),resume=tailored.id?tailored:original;return`${resume.resume_name||"Resume"}${resume.resume_number?` #${resume.resume_number}`:""}${tailored.id?" (Tailored)":""}`;}},
    {title:"Template",dataIndex:"render_template_key",render:value=>formatLabel(value||"CLASSIC_V1")},
    {title:"Format",dataIndex:"render_format",render:value=><Tag>{value||"DOCX"}</Tag>},
    {title:"Status",dataIndex:"status",render:value=><StatusTag value={value}/>},
    {title:"Updated",dataIndex:"updated_at",render:formatDate},
    {title:"Action",render:(_,row)=>row.application_id?<Button type="link" onClick={()=>go(`#/tailoring-jobs/${row.id}`)}>{row.status==="NEEDS_REVIEW"?"Review":"View"}</Button>:<Text type="secondary">Not Application-linked</Text>}
  ],[]);
  return <div className="page">
    <Flex justify="space-between" align="center" wrap><div><Text className="eyebrow" type="secondary">RESUME TAILORING</Text><Title level={1}>Tailoring Reviews</Title></div><Select value={status} onChange={setStatus} style={{minWidth:220}} options={STATUSES.map(value=>({value,label:value==="ALL"?"All statuses":formatLabel(value)}))}/></Flex>
    <Alert className="ui-alert" showIcon type="info" message="Approved content becomes one Application-specific Resume" description="Creating the selected DOCX or PDF stores a private TAILORED child and atomically switches only its Application."/>
    {error&&<Alert className="ui-alert" showIcon type="error" message={error}/>} {!items&&!error?<LoadingState/>:<Card><Table rowKey="id" columns={columns} dataSource={items||[]} pagination={{pageSize:25,showSizeChanger:false}} scroll={{x:"max-content"}} locale={{emptyText:<Empty description="No tailoring jobs match this status."/>}}/></Card>}
  </div>;
}

export function TailoringReviewPage({client,apiBaseUrl,id,reload}){
  const{modal}=AntApp.useApp(),[form]=Form.useForm(),[job,setJob]=useState(),[history,setHistory]=useState([]),[templates,setTemplates]=useState([]),[notes,setNotes]=useState(""),[runner,setRunner]=useState(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const load=async()=>{setError("");try{const[data,reviews,availableTemplates]=await Promise.all([getTailoringJob(client,apiBaseUrl,id),getTailoringReviews(client,apiBaseUrl,id),listTailoringTemplates(client,apiBaseUrl).catch(()=>[])]);setJob(data);setHistory(reviews||[]);setTemplates(availableTemplates||[]);setNotes(data.review_notes||"");if(data.output_preview)form.setFieldsValue({summary:data.output_preview.summary,professionalExperience:data.output_preview.professionalExperience,skills:data.output_preview.skills});}catch(x){setError(x.message);}};
  useEffect(()=>{load();},[client,apiBaseUrl,id,reload]);
  useEffect(()=>{if(!["PENDING","PROCESSING","MATERIALIZING"].includes(job?.status))return;const timer=setInterval(load,4000);return()=>clearInterval(timer);},[job?.status,client,apiBaseUrl,id]);
  if(!job)return <div className="page">{error?<Alert type="error" showIcon message={error}/>:<LoadingState/>}</div>;
  const jd=one(job.job_descriptions),resume=one(job.resumes),tailored=one(job.tailored_resume),application=one(job.applications),editable=job.status==="NEEDS_REVIEW"&&Boolean(job.output_preview);
  async function submit(action){
    const values=await form.validateFields(),preview={...job.output_preview,summary:values.summary.trim(),professionalExperience:values.professionalExperience.map(item=>({...item,tailoredDetails:item.tailoredDetails.trim()})),skills:[...new Set((values.skills||[]).map(value=>String(value).trim()).filter(Boolean))]};
    setBusy(true);setError("");setSuccess("");try{await reviewTailoringPreview(client,apiBaseUrl,id,{action,preview,notes:notes.trim(),expectedUpdatedAt:job.updated_at});setSuccess(action==="SAVE_DRAFT"?"Review draft saved.":action==="APPROVE"?"Tailored content approved for rendering.":"Tailored content rejected.");await load();}catch(x){setError(x.message);}finally{setBusy(false);}
  }
  const confirm=action=>{if(action==="REJECT"&&!notes.trim()){setError("Enter review notes before rejecting this preview.");return;}modal.confirm({title:action==="APPROVE"?"Approve tailored content?":"Reject tailored content?",content:action==="APPROVE"?"This locks the reviewed content so it can be rendered as an Application Resume.":"The reason will be retained in the immutable review history.",okText:formatLabel(action),okButtonProps:action==="REJECT"?{danger:true}:{},onOk:()=>submit(action)});};
  async function prepareRunner(){setBusy(true);setError("");try{const value=await createTailoringRunnerTicket(client,apiBaseUrl,id);setRunner(value);setSuccess("Runner command created. Run it from the repository root before the ticket expires.");await load();}catch(x){setError(x.message);}finally{setBusy(false);}}
  async function materialize(){setBusy(true);setError("");setSuccess("");try{const value=await materializeTailoredResume(client,apiBaseUrl,id);setSuccess(`Tailored Resume #${value.tailoredResumeNumber} created and assigned to Application #${application.application_number}.`);await load();}catch(x){setError(x.message);}finally{setBusy(false);}}
  async function chooseTemplate(renderTemplateKey){setBusy(true);setError("");setSuccess("");try{await selectTailoringTemplate(client,apiBaseUrl,id,{renderTemplateKey,expectedUpdatedAt:job.updated_at});setSuccess(`${templates.find(item=>item.key===renderTemplateKey)?.name||formatLabel(renderTemplateKey)} template selected.`);await load();}catch(x){setError(x.message);}finally{setBusy(false);}}
  async function chooseFormat(renderFormat){setBusy(true);setError("");setSuccess("");try{await selectTailoringFormat(client,apiBaseUrl,id,{renderFormat,expectedUpdatedAt:job.updated_at});setSuccess(`${renderFormat} output selected.`);await load();}catch(x){setError(x.message);}finally{setBusy(false);}}
  async function download(){setBusy(true);setError("");try{const value=await getTailoringResumeUrl(client,apiBaseUrl,id);window.open(value.signedUrl,"_blank","noopener,noreferrer");}catch(x){setError(x.message);}finally{setBusy(false);}}
  const historyColumns=[{title:"When",dataIndex:"createdAt",render:formatDate},{title:"Action",dataIndex:"action",render:value=><Tag>{formatLabel(value)}</Tag>},{title:"Reviewer",dataIndex:"reviewerName"},{title:"Status",dataIndex:"newStatus",render:value=><StatusTag value={value}/>},{title:"Notes",dataIndex:"notes",render:value=>value||"—"}];
  const runnerCommand=runner?`npm run tailoring:run -- --ticket "${runner.ticket}" --api-base-url "${apiBaseUrl||location.origin}"`:"";
  return <div className="page">
    <Button type="link" href="#/tailoring-jobs">← Back to Tailoring Reviews</Button>
    <Flex justify="space-between" align="start" wrap><div><Text className="eyebrow" type="secondary">APPLICATION #{application.application_number||"—"}</Text><Title level={1}>{jd.company||"Job"} — {jd.job_title||"Tailoring Preview"}</Title><Paragraph>{resume.resume_name||"Resume"}{resume.resume_number?` #${resume.resume_number}`:""} · {resume.candidate_name||"Unknown candidate"}</Paragraph></div><StatusTag value={job.status}/></Flex>
    {error&&<Alert className="ui-alert" type="error" showIcon message={error}/>} {success&&<Alert className="ui-alert" type="success" showIcon message={success}/>}
    {!job.output_preview?<Card title="Generate the preview locally"><Alert className="ui-alert" type="info" showIcon message={`Current status: ${formatLabel(job.status)}`} description="Create a short-lived command, copy it, and run it once from the repository root. This page checks for completion automatically."/>{runner?<><Paragraph copyable={{text:runnerCommand}} code>{runnerCommand}</Paragraph><Text type="secondary">Ticket expires {formatDate(runner.expiresAt)}. Creating another command revokes this one. Treat it as a temporary secret.</Text></>:<Button type="primary" loading={busy} disabled={!['PENDING','PROCESSING'].includes(job.status)} onClick={prepareRunner}>{job.status==="PROCESSING"?"Create Retry Command":"Create Runner Command"}</Button>}</Card>:<>
      <Card title="Tailored content" extra={<Text type="secondary">Preview generated {formatDate(job.preview_generated_at)}</Text>}><Form form={form} layout="vertical" disabled={!editable}><Form.Item label="Summary" name="summary" rules={[{required:true,message:"Summary is required."}]}><Input.TextArea rows={7} maxLength={4000} showCount/></Form.Item><Form.List name="professionalExperience">{fields=><Space direction="vertical" size="large" style={{width:"100%"}}>{fields.map(({key,name:fieldName})=><Card size="small" key={key} title={`Experience ${fieldName+1}`}><Form.Item name={[fieldName,"sourceExperienceId"]} label="Source experience ID"><Input disabled/></Form.Item><Form.Item name={[fieldName,"tailoredDetails"]} label="Tailored details" rules={[{required:true,message:"Experience details are required."}]}><Input.TextArea rows={8} maxLength={12000} showCount/></Form.Item></Card>)}</Space>}</Form.List><Form.Item label="Skills" name="skills"><Select mode="tags" tokenSeparators={[","]} open={false}/></Form.Item></Form></Card>
      <Card title="Evidence notes"><Descriptions column={{xs:1,md:2}} items={[{key:"changes",label:"Change summary",children:(job.output_preview.changeSummary||[]).join("; ")||"None"},{key:"unsupported",label:"Unsupported requirements",children:(job.output_preview.unsupportedRequirements||[]).join("; ")||"None"},{key:"warnings",label:"Warnings",children:(job.output_preview.warnings||[]).join("; ")||"None"}]}/></Card>
      {editable&&<Card title="Decision"><Input.TextArea value={notes} onChange={event=>setNotes(event.target.value)} rows={4} maxLength={1000} showCount placeholder="Review notes; required when rejecting"/><Space wrap style={{marginTop:16}}><Button onClick={()=>submit("SAVE_DRAFT")} loading={busy}>Save Draft</Button><Button type="primary" onClick={()=>confirm("APPROVE")} loading={busy}>Approve Content</Button><Button danger onClick={()=>confirm("REJECT")} loading={busy}>Reject</Button></Space></Card>}
      {job.status==="APPROVED"&&<Card title="Create Application Resume"><Alert className="ui-alert" type="warning" showIcon message="The approved content is ready" description="Choose a versioned layout and DOCX or PDF output. The original Resume remains unchanged."/><Form.Item label="Resume template" extra={templates.find(item=>item.key===job.render_template_key)?.description||"The selected template key is retained for auditability."}><Select value={job.render_template_key||"CLASSIC_V1"} loading={!templates.length} disabled={busy||!templates.length} onChange={chooseTemplate} options={templates.map(item=>({value:item.key,label:`${item.name} (${item.key.replace("_V"," v")})`}))}/></Form.Item><Form.Item label="Artifact format" extra="PDF is ready to upload to job sites; DOCX remains editable."><Select value={job.render_format||"DOCX"} disabled={busy} onChange={chooseFormat} options={[{value:"PDF",label:"PDF"},{value:"DOCX",label:"DOCX"}]}/></Form.Item><Button type="primary" loading={busy} onClick={()=>modal.confirm({title:"Create and assign the tailored Resume?",content:`The Application will use a ${templates.find(item=>item.key===job.render_template_key)?.name||formatLabel(job.render_template_key||"CLASSIC_V1")} ${job.render_format||"DOCX"}. The original Resume remains the primary source and is not changed.`,okText:"Create Resume",onOk:materialize})}>Create Tailored Resume</Button></Card>}
      {job.status==="MATERIALIZING"&&<Alert className="ui-alert" type="info" showIcon message="Creating the private tailored Resume…" description="This page refreshes automatically."/>}
      {job.status==="COMPLETED"&&<Card title="Tailored Resume ready"><Descriptions column={1} items={[{key:"number",label:"Resume number",children:`#${tailored.resume_number||"—"}`},{key:"template",label:"Template",children:formatLabel(tailored.render_template_key||job.render_template_key||"CLASSIC_V1")},{key:"format",label:"Format",children:tailored.render_format||job.render_format||"DOCX"},{key:"created",label:"Created",children:formatDate(job.materialized_at)}]}/><Button type="primary" loading={busy} onClick={download}>Download Tailored Resume</Button></Card>}
    </>}
    <Card title="Review history"><Table rowKey="id" columns={historyColumns} dataSource={history} pagination={false} scroll={{x:"max-content"}} locale={{emptyText:<Empty description="No human review actions recorded."/>}}/></Card>
  </div>;
}
