import React from "react";
import{Card,Col,Form,Input,Row,Select,Space,Tabs,Tag,Typography}from"antd";

const{Paragraph,Text}=Typography;
const list=value=>Array.isArray(value)?value:[];
const words=value=>String(value||"").trim().split(/\s+/).filter(Boolean).length;
const lines=value=>String(value||"").split(/\r?\n/).map(x=>x.replace(/^\s*[-*•]\s*/,"").trim()).filter(Boolean);

function Pane({title,tone="source",children}){return <Card size="small" className={`tailoring-pane tailoring-pane-${tone}`} title={<Space><span className="tailoring-pane-dot"/><Text strong>{title}</Text></Space>}>{children}</Card>}
function Bullets({value}){const items=lines(value);return items.length?<ul className="tailoring-bullets">{items.map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul>:<Text type="secondary">No content</Text>}

export function TailoringComparison({resume,preview,editable}){
  const structured=resume?.structured_content||{},sourceExperiences=list(structured.professional_experience),tailored=list(preview?.professionalExperience),sourceSkills=list(resume?.skills);
  const summary=<Row gutter={[16,16]}><Col xs={24} lg={12}><Pane title={`Original summary · ${words(structured.summary)} words`}><Paragraph className="tailoring-copy">{structured.summary||"No original summary"}</Paragraph></Pane></Col><Col xs={24} lg={12}><Pane tone="tailored" title={`Tailored summary · ${words(preview?.summary)} words`}><Form.Item name="summary" rules={[{required:true,message:"Summary is required."}]} noStyle><Input.TextArea className="tailoring-editor" autoSize={{minRows:8,maxRows:18}} maxLength={4000} showCount disabled={!editable}/></Form.Item></Pane></Col></Row>;
  const experience=<Space direction="vertical" size="large" style={{width:"100%"}}>{sourceExperiences.map((source,index)=>{const result=tailored.find(x=>x.sourceExperienceId===source.id)||tailored[index]||{};return <Card key={source.id||index} className="tailoring-experience" title={<div><Text strong>{source.job_title||"Experience"}</Text><br/><Text type="secondary">{source.company||"Unknown employer"}</Text></div>} extra={<Tag color="blue">{lines(source.experience_details).length} → {lines(result.tailoredDetails).length} bullets</Tag>}><Row gutter={[16,16]}><Col xs={24} lg={12}><Pane title="Original Evidence"><Bullets value={source.experience_details}/></Pane></Col><Col xs={24} lg={12}><Pane tone="tailored" title="Tailored Version"><Form.Item name={["professionalExperience",index,"sourceExperienceId"]} hidden><Input/></Form.Item><Form.Item name={["professionalExperience",index,"tailoredDetails"]} rules={[{required:true,message:"Experience details are required."}]} noStyle><Input.TextArea className="tailoring-editor" autoSize={{minRows:8,maxRows:24}} maxLength={12000} showCount disabled={!editable}/></Form.Item></Pane></Col></Row></Card>;})}</Space>;
  const skills=<Row gutter={[16,16]}><Col xs={24} lg={12}><Pane title={`Original skills · ${sourceSkills.length}`}><div className="tailoring-skill-cloud">{sourceSkills.map(skill=><Tag key={skill}>{skill}</Tag>)}</div></Pane></Col><Col xs={24} lg={12}><Pane tone="tailored" title={`Tailored order · ${list(preview?.skills).length}`}><Form.Item name="skills" noStyle><Select mode="tags" tokenSeparators={[","]} open={false} disabled={!editable} style={{width:"100%"}}/></Form.Item><Paragraph type="secondary" style={{marginTop:12,marginBottom:0}}>Relevant supported skills should appear first. Skills remain sourced from the original Resume.</Paragraph></Pane></Col></Row>;
  return <Card className="tailoring-comparison" title="Resume Comparison" extra={<Space><Tag>Original</Tag><Tag color="green">Tailored</Tag></Space>}><Paragraph type="secondary">Compare evidence and proposed wording before approval. Edit only the tailored side.</Paragraph><Form.Item noStyle shouldUpdate>{()=> <Tabs defaultActiveKey="summary" items={[{key:"summary",label:"Summary",children:summary},{key:"experience",label:`Experience (${sourceExperiences.length})`,children:experience},{key:"skills",label:`Skills (${sourceSkills.length})`,children:skills}]}/>}</Form.Item></Card>;
}
