import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import{BaseAtsAdapter}from"../extension/adapters/base-ats-adapter.js";
import{createAdapterRegistry,selectJobSiteAdapter}from"../extension/adapters/adapter-registry.js";

class TestAdapter extends BaseAtsAdapter{constructor(id,host,tier){super({id,label:id,version:"test",tier});this.host=host;}matches(url){return url.hostname===this.host;}}
test("v0.9.3 selects exact domain, ATS family, then Generic HTML",()=>{const exact=new TestAdapter("exact","careers.example.com","EXACT_DOMAIN"),family=new TestAdapter("family","jobs.example.net","ATS_FAMILY"),generic=new TestAdapter("generic","never.invalid","GENERIC");generic.matches=()=>true;const registry=createAdapterRegistry({exact:[exact],families:[family],generic});assert.equal(registry.select("https://careers.example.com/apply").id,"exact");assert.equal(registry.select("https://jobs.example.net/1").id,"family");assert.equal(registry.select("https://other.example.org/form").id,"generic");});
test("v0.9.3 recognizes Greenhouse and Workable families",()=>{assert.equal(selectJobSiteAdapter("https://job-boards.greenhouse.io/acme/jobs/1").id,"greenhouse");assert.equal(selectJobSiteAdapter("https://apply.workable.com/acme/j/1/apply/").id,"workable");assert.equal(selectJobSiteAdapter("https://careers.example.com/apply").id,"generic-html");});
test("v0.9.3 adapters expose the bounded capability contract",()=>{const selected=selectJobSiteAdapter("https://example.com");for(const name of["detectResumeField","detectFields","attachResume","fillField","fillFields","verifyField"])assert.equal(typeof selected.adapter[name],"function");assert.deepEqual(Object.keys(selected.adapter.diagnostics()).sort(),["id","label","tier","version"]);});
test("content scripts delegate to adapters without persistence, network access, or submission",async()=>{const sources=await Promise.all(["../extension/adapters/base-ats-adapter.js","../extension/adapters/generic-html-adapter.js","../extension/adapters/adapter-registry.js","../extension/content/personal-autofill.js","../extension/content/resume-upload.js"].map(path=>readFile(new URL(path,import.meta.url),"utf8"))),text=sources.join("\n");assert.match(text,/selectJobSiteAdapter/);assert.match(text,/detectFields/);assert.match(text,/attachResume/);assert.match(text,/fillFields/);assert.doesNotMatch(text,/supabase|fetch\(|chrome\.storage|\.submit\(|requestSubmit\(/i);});
