import test from"node:test";import assert from"node:assert/strict";import{parseHTML}from"linkedom";
import{autofillValue,autofillValues}from"../extension/autofill/autofill-context.js";
import{detectPersonalFields,fillPersonalFields}from"../extension/autofill/personal-field-adapter.js";
import{createAdapterRegistry}from"../extension/adapters/adapter-registry.js";

test("v1 flattens bounded structured employment and education without inference",()=>{const context={values:{"candidate.firstName":"Ada"},employmentHistory:[{company:"Example",jobTitle:"Engineer",startDate:{month:2,year:2020},isCurrent:true}],education:[{institution:"State University",degree:"BS",endDate:{year:2019}}]},values=autofillValues(context);assert.equal(values["employment.0.company"],"Example");assert.equal(values["employment.0.startMonth"],2);assert.equal(values["education.0.endYear"],2019);assert.equal(autofillValue(context,{key:"employment.0.jobTitle"}),"Engineer");});

test("v1 detects and verifies structured fields and a current-employment checkbox",()=>{const{document,window}=parseHTML(`<form><label>Company<input name="company"></label><label>Job title<input name="title"></label><label>Currently employed<input type="checkbox" name="current"></label></form>`);Object.assign(globalThis,{Event:window.Event,HTMLInputElement:window.HTMLInputElement,HTMLTextAreaElement:window.HTMLTextAreaElement});const keys=["employment.0.company","employment.0.jobTitle","employment.0.isCurrent"],fields=detectPersonalFields(document,keys);assert.equal(fields.length,3);const values={"employment.0.company":"Example","employment.0.jobTitle":"Engineer","employment.0.isCurrent":true},results=fillPersonalFields(fields.map(field=>({...field,value:values[field.key]})),document);assert.ok(results.every(result=>result.status==="VERIFIED"));});

test("v1 registry identifies four ATS families and keeps generic fallback",()=>{const registry=createAdapterRegistry();assert.equal(registry.select("https://jobs.lever.co/acme/1").adapter.id,"lever");assert.equal(registry.select("https://careers-acme.icims.com/jobs/1").adapter.id,"icims");assert.equal(registry.select("https://boards.greenhouse.io/acme/jobs/1").adapter.id,"greenhouse");assert.equal(registry.select("https://apply.workable.com/acme/j/1").adapter.id,"workable");assert.equal(registry.select("https://example.com/apply").adapter.id,"generic-html");});
