import test from "node:test";import assert from "node:assert/strict";import {parseHTML} from "linkedom";import {extractJobFromPage,selectBestFrameExtraction} from "../extension/shared/extraction.js";
function page(html,url="https://example.com/jobs/1"){const parsed=parseHTML(html);globalThis.window=parsed.window;globalThis.document=parsed.document;globalThis.location=new URL(url);globalThis.getComputedStyle=()=>({display:"block",visibility:"visible"});parsed.window.getSelection=()=>({toString:()=>""});}
test("extracts Paylocity-style JobPosting JSON-LD",()=>{page(`<title>Career Opportunities - Data Engineer</title><script type="application/ld+json">{"@type":"JobPosting","title":"Data Engineer","hiringOrganization":{"name":"TruDataRx"},"description":"<p>ABOUT TRUDATARX</p><p>${"Clinical data pipeline experience. ".repeat(8)}</p>"}</script>`,`https://recruiting.paylocity.com/Recruiting/Jobs/Details/3794874`);const result=extractJobFromPage(false);assert.equal(result.company,"TruDataRx");assert.equal(result.jobTitle,"Data Engineer");assert.equal(result.captureMethod,"json_ld");assert.equal(result.sourceSite,"recruiting.paylocity.com");assert.match(result.jobDescription,/ABOUT TRUDATARX/);});
test("extracts a structured JSON-LD job location",()=>{page(`<script type="application/ld+json">{"@type":"JobPosting","title":"Analyst","hiringOrganization":{"name":"Acme"},"jobLocation":{"address":{"addressLocality":"Arlington","addressRegion":"VA","postalCode":"22201","addressCountry":"US"}},"description":"${"Analyze business performance and build strategic recommendations. ".repeat(4)}"}</script>`);const result=extractJobFromPage(false);assert.equal(result.location,"Arlington, VA, 22201, US");});
test("extracts location from common page markup",()=>{page(`<title>Acme Careers</title><h1>Data Analyst</h1><div data-testid="job-location">New York, NY</div><main>${"Build reports and analyze operational data for business teams. ".repeat(5)}</main>`);assert.equal(extractJobFromPage(false).location,"New York, NY");});
test("keeps location blank for fully remote JSON-LD jobs",()=>{page(`<script type="application/ld+json">{"@type":"JobPosting","title":"Engineer","hiringOrganization":{"name":"Acme"},"jobLocationType":"TELECOMMUTE","jobLocation":{"address":{"addressLocality":"Boston","addressRegion":"MA"}},"description":"${"Build reliable distributed systems for customers and internal teams. ".repeat(4)}"}</script>`);const result=extractJobFromPage(false);assert.equal(result.location,"");assert.equal(result.workArrangement,"REMOTE");});
test("extracts structured JSON-LD salary data",()=>{page(`<script type="application/ld+json">{"@type":"JobPosting","title":"Engineer","hiringOrganization":{"name":"Acme"},"baseSalary":{"@type":"MonetaryAmount","currency":"USD","value":{"@type":"QuantitativeValue","minValue":130000,"maxValue":175000,"unitText":"YEAR"}},"description":"${"Build reliable distributed systems for customers and internal teams. ".repeat(4)}"}</script>`);assert.deepEqual(extractJobFromPage(false).salary,{min:130000,max:175000,currency:"USD",period:"YEAR",text:"USD 130000 - 175000 YEAR"});});
test("rejects a large company navigation container and uses title identity",()=>{page(`<title>Block - Careers - Senior Data Engineer, Risk</title><div class="companyName">${"Company NEWS IMPACT AI OPEN SOURCE BITCOIN CAREERS ".repeat(5)}</div><h1>Senior Data Engineer, Risk</h1><main>${"Build risk and compliance data pipelines at Block. ".repeat(10)}</main>`,`https://block.xyz/careers/jobs/5281312008`);const result=extractJobFromPage(false);assert.equal(result.company,"Block");assert.equal(result.jobTitle,"Senior Data Engineer, Risk");assert.equal(result.sourceSite,"block.xyz");});
test("extracts iCIMS job content inside its content frame",()=>{page(`<title>ERMCO Careers</title><h1 class="iCIMS_Header">Sr. Business Analyst, Corporate Strategy &amp; Analytics</h1><section class="iCIMS_JobContent"><h2>Overview</h2><p>${"Analyze corporate strategy, operations, and financial performance. ".repeat(8)}</p><h2>Responsibilities</h2></section>`,`https://careers-ermcoeci.icims.com/jobs/6547/example/job?in_iframe=1`);const result=extractJobFromPage(false);assert.equal(result.jobTitle,"Sr. Business Analyst, Corporate Strategy & Analytics");assert.equal(result.captureMethod,"known_selector");assert.match(result.jobDescription,/Responsibilities/);});
test("selects a usable iframe result over an empty top-frame wrapper",()=>{const iframe={company:"ERMCO",jobTitle:"Sr. Business Analyst",jobDescription:"Complete job description ".repeat(20),captureMethod:"known_selector"};assert.deepEqual(selectBestFrameExtraction([{frameId:0,result:{company:"",jobTitle:"",jobDescription:"",captureMethod:"manual"}},{frameId:7,result:iframe}]),{frameId:7,result:iframe});});
test("replaces generic Greenhouse frame branding with the first-party company",()=>{const outer={company:"Pantheon",jobTitle:"Careers detail",jobDescription:"Wrapper page content ".repeat(10),captureMethod:"main_fallback"},frame={company:"Job Boards",jobTitle:"Senior Software Engineer",jobDescription:"Real job description ".repeat(30),captureMethod:"known_selector"};const best=selectBestFrameExtraction([{frameId:0,result:outer},{frameId:4,result:frame}]);assert.equal(best.frameId,4);assert.equal(best.result.company,"Pantheon");assert.equal(best.result.jobTitle,"Senior Software Engineer");});
test("rejects Job Boards as a company on a first-party career page",()=>{page(`<title>Careers detail | Pantheon.io</title><div data-testid="company-name">Job Boards</div><h1>Senior Engineer</h1><main>${"Build and operate Pantheon's cloud platform for customers. ".repeat(6)}</main>`,`https://pantheon.io/about/careers/detail?gh_jid=8054337`);assert.equal(extractJobFromPage(false).company,"Pantheon");});
