import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const migration=name=>readFileSync(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8');
const sql=migration('202609282300_v3_133_unique_tailoring_artifact_paths.sql');
test('new PDF attempts preserve archived objects, authorize only the active path, and finalize the exact uploaded path',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
    create function auth.uid() returns uuid language sql stable as $$select '${id(999)}'::uuid$$;
    create function assert_application_manager() returns void language sql as $$select$$;
    create function application_actor_can_manage() returns boolean language sql as $$select true$$;
    create function assert_tailoring_preview_v14(uuid,jsonb) returns void language sql as $$select$$;
    create table resumes(id uuid primary key default gen_random_uuid(),resume_number bigint generated by default as identity,user_id uuid,resume_type text,status text,
      candidate_name text,candidate_email text,candidate_phone text,candidate_first_name text,candidate_middle_name text,candidate_last_name text,
      address_line_1 text,address_line_2 text,address_city text,address_state_region text,address_postal_code text,address_country text,linkedin_url text,github_url text,portfolio_url text,
      resume_name text,primary_category_id uuid,subcategory_id uuid,seniority text,skills text[],industries text[],resume_text text,structured_content jsonb,structured_schema_version integer,
      storage_bucket text,storage_path text,original_filename text,mime_type text,file_size_bytes bigint,file_sha256 text,profile_review_status text,profile_reviewed_by uuid,profile_reviewed_at timestamptz,
      profile_schema_version integer,autofill_preferences jsonb,parent_resume_id uuid,render_template_key text,render_format text,resume_headline text);
    create table job_descriptions(id uuid primary key,company text,job_title text);
    create table applications(id uuid primary key,resume_id uuid,job_description_id uuid,application_number integer);
    create table tailoring_jobs(id uuid primary key,application_id uuid,resume_id uuid,job_description_id uuid,status text,tailored_resume_id uuid,tailored_resume_path text,
      materializing_by uuid,materialized_by uuid,materialized_at timestamptz,materialization_token uuid,materialization_started_at timestamptz,output_preview jsonb,
      failure_code text,failure_message text,updated_at timestamptz default now(),render_format text,render_template_key text,format_selected_by uuid,format_selected_at timestamptz,
      automatic_materialization boolean,processed_by uuid);
    create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));
    alter table storage.objects enable row level security;
    grant usage on schema storage to anon,authenticated;grant insert on storage.objects to anon,authenticated;
    insert into resumes(id,user_id,resume_type,status,candidate_name,resume_name,skills,structured_content) values('${id(1)}','${id(999)}','ORIGINAL','ACTIVE','Test Candidate','Test Resume',array['Python'],
      '{"summary":"Original source","professional_experience":[{"id":"role-1","company":"Example","job_title":"Engineer","experience_details":"Original work"}]}');
    insert into job_descriptions values('${id(10)}','Example','Engineer');
    insert into applications values('${id(20)}','${id(1)}','${id(10)}',1);
    insert into tailoring_jobs(id,application_id,resume_id,job_description_id,status,render_format,render_template_key,automatic_materialization,processed_by,output_preview)
      values('${id(30)}','${id(20)}','${id(1)}','${id(10)}','APPROVED','PDF','MODERN_V1',true,'${id(999)}',
      '{"summary":"A complete approved summary with sufficient content for the rendered document.","professionalExperience":[{"sourceExperienceId":"role-1","tailoredDetails":"- Built robust services and reliable reporting pipelines for the team."}],"skills":["Python","Statistical Analysis"]}');
  `);
  const v16=migration('202608030042_v1_6_tailored_resume_materialization.sql'),start=v16.indexOf('create or replace function public.begin_tailoring_materialization_v16');
  await db.exec(v16.slice(start,v16.indexOf('end$$;',start)+6));
  await db.exec(sql);
  await db.exec(`create policy runner_upload on storage.objects for insert to anon with check(bucket_id='tailored-resumes' and public.can_auto_materialize_tailored_resume_v34(name));`);
  const value=async(query,args=[]) => (await db.query(query,args)).rows[0]?.result;
  const begin=()=>value('select begin_tailoring_materialization_v19($1) result',[id(30)]);
  const finalize=(started,path=started.targetPath)=>value('select finalize_tailoring_materialization_v19($1,$2,$3,$4,$5,$6,$7) result',[id(30),started.materializationToken,path,started.filename,'application/pdf',2048,'a'.repeat(64)]);
  const legacy=`${id(999)}/${id(30)}/resume-1-application-1-tailored.pdf`;
  await db.query("insert into storage.objects values('tailored-resumes',$1)",[legacy]);
  const first=await begin();
  assert.notEqual(first.targetPath,legacy);
  assert.ok(first.targetPath.includes(`/${first.materializationToken}/`));
  assert.equal(first.filename,'resume-1-application-1-tailored.pdf');
  await assert.rejects(begin,/already being materialized/);
  await db.exec('set role anon');
  await db.query("insert into storage.objects values('tailored-resumes',$1)",[first.targetPath]);
  await assert.rejects(()=>db.query("insert into storage.objects values('tailored-resumes',$1)",[legacy]),/row-level security/);
  await assert.rejects(()=>db.exec('select * from storage.objects'),/permission denied/);
  await db.exec('reset role');
  await assert.rejects(()=>finalize(first,legacy),/TAILORING_ARTIFACT_INVALID/);
  // The prior lease expires; a new begin gets a different token and upload path.
  await db.exec("update tailoring_jobs set materialization_started_at=now()-interval '16 minutes'");
  const retry=await begin();assert.notEqual(retry.targetPath,first.targetPath);
  assert.equal(await value('select can_auto_materialize_tailored_resume_v34($1) result',[first.targetPath]),false);
  assert.equal(await value('select can_auto_materialize_tailored_resume_v34($1) result',[retry.targetPath]),true);
  await assert.rejects(()=>finalize(first),/TAILORING_MATERIALIZATION_CONFLICT/);
  await db.exec('set role anon');
  await db.query("insert into storage.objects values('tailored-resumes',$1)",[retry.targetPath]);
  await db.exec('reset role');
  assert.equal((await finalize(retry)).status,'COMPLETED');
  assert.equal(await value('select storage_path result from resumes where id=(select resume_id from applications where id=$1)',[id(20)]),retry.targetPath);
  assert.equal(await value('select count(*)::integer result from storage.objects'),3);
  assert.equal((await begin()).alreadyMaterialized,true);
  assert.equal((await finalize(retry)).alreadyMaterialized,true);
  assert.equal(await value('select can_auto_materialize_tailored_resume_v34($1) result',[retry.targetPath]),false);
});
