import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const sql=readFileSync(new URL("../supabase/migrations/202608030038_v1_1_resume_variants.sql",import.meta.url),"utf8");

test("v1.1 assigns human Resume numbers and models one-level variants",()=>{
  assert.match(sql,/resume_number bigint generated by default as identity/i);
  assert.match(sql,/resume_type text not null default 'ORIGINAL'/i);
  assert.match(sql,/parent_resume_id uuid references public\.resumes\(id\) on delete restrict/i);
  assert.match(sql,/resume_type in\('ORIGINAL','TAILORED'\)/i);
  assert.match(sql,/resume_type='TAILORED' and parent_resume_id is not null/i);
  assert.match(sql,/v_parent\.resume_type<>'ORIGINAL'/i);
  assert.match(sql,/RESUME_VARIANT_IMMUTABLE/i);
});

test("v1.1 keeps original and tailored files in their private variant buckets",()=>{
  assert.match(sql,/resume_type='ORIGINAL' and storage_bucket='original-resumes'/i);
  assert.match(sql,/resume_type='TAILORED' and storage_bucket='tailored-resumes'/i);
  assert.match(sql,/create index resumes_type_status_updated_idx/i);
  assert.match(sql,/create index resumes_parent_updated_idx/i);
});

test("v1.1 keeps primary Resume workflows original-only",()=>{
  assert.match(sql,/where r\.resume_type='ORIGINAL'/i);
  assert.match(sql,/r\.status='ACTIVE' and r\.resume_type='ORIGINAL'/i);
  assert.match(sql,/New Applications must start with an original Resume/i);
  assert.match(sql,/where resume_type='ORIGINAL'/i);
});

test("v1.1 exposes no privileged key or AI execution path",()=>{
  assert.doesNotMatch(sql,/service_role|sb_secret_|openai|codex exec/i);
});
