import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const sql=readFileSync(new URL("../supabase/migrations/202608030042_v1_6_tailored_resume_materialization.sql",import.meta.url),"utf8");
test("v1.6 records one concurrency-protected tailored artifact per job",()=>{assert.match(sql,/add column tailored_resume_id uuid references public\.resumes/);assert.match(sql,/materialization_token uuid/);assert.match(sql,/unique index tailoring_jobs_tailored_resume_key/);assert.match(sql,/status='MATERIALIZING'/);});
test("v1.6 keeps JD and Resume-family duplicate protection after the Application switch",()=>{assert.match(sql,/function public\.prevent_application_resume_family_duplicate_v16/);assert.match(sql,/coalesce\(r\.parent_resume_id,r\.id\)=v_family/);assert.match(sql,/APPLICATION_ALREADY_EXISTS/);assert.match(sql,/applications_resume_family_unique_v16/);});
test("v1.6 begins only from an approved Application source",()=>{assert.match(sql,/function public\.begin_tailoring_materialization_v16/);assert.match(sql,/perform public\.assert_application_manager\(\)/);assert.match(sql,/v_job\.status not in\('APPROVED','MATERIALIZING'\)/);assert.match(sql,/v_application\.resume_id is distinct from v_resume\.id/);assert.match(sql,/perform public\.assert_tailoring_preview_v14/);});
test("v1.6 finalization verifies Storage and atomically creates and assigns one child",()=>{assert.match(sql,/exists\(select 1 from storage\.objects/);assert.match(sql,/insert into public\.resumes/);assert.match(sql,/'TAILORED',v_resume\.id/);assert.match(sql,/update public\.tailoring_jobs set status='COMPLETED'/);assert.match(sql,/update public\.applications set resume_id=v_tailored_id/);assert.ok(sql.indexOf("update public.tailoring_jobs set status='COMPLETED'")<sql.indexOf("update public.applications set resume_id=v_tailored_id"));});
test("v1.6 changes only approved content sections and copies candidate metadata",()=>{assert.match(sql,/v_resume\.structured_content\|\|jsonb_build_object\('summary'/);assert.match(sql,/'professional_experience',v_experience/);assert.match(sql,/'skills',array_to_string/);assert.match(sql,/v_resume\.candidate_email,v_resume\.candidate_phone/);assert.match(sql,/v_resume\.address_line_1,v_resume\.address_line_2/);assert.match(sql,/v_resume\.autofill_preferences,'TAILORED',v_resume\.id/);});
test("v1.6 private Storage policies include assigned Applier reads and manager-only writes",()=>{assert.match(sql,/application scoped or manager read tailored resumes/);assert.match(sql,/a\.assigned_to=auth\.uid\(\)/);assert.match(sql,/manager materializes tailored resumes/);assert.match(sql,/t\.materializing_by=auth\.uid\(\)/);assert.doesNotMatch(sql,/service.?role|secret.?key/i);});
test("v1.6 keeps extension metadata and reviewed answers sourced from the original",()=>{assert.match(sql,/resumeNumber.*resumeType.*parentResumeId/);assert.match(sql,/coalesce\(r\.parent_resume_id,r\.id\)/);assert.match(sql,/x\.resume_id=v_answer_resume_id/);assert.match(sql,/get_application_autofill_context_v089_pre_v16/);});
