import{Body,Controller,Delete,Get,Inject,Param,ParseUUIDPipe,Patch,Post,Query,Req,UseGuards}from"@nestjs/common";import{ApiBearerAuth,ApiTags}from"@nestjs/swagger";import{AuthGuard}from"../auth/auth.guard.js";import{RequireRoles}from"../auth/require-roles.decorator.js";import{RolesGuard}from"../auth/roles.guard.js";import type{ApiRequest}from"../common/types/request.js";import{DtoValidationPipe}from"../common/validation/dto-validation.pipe.js";import{PlatformService,TailoringService}from"./platform.service.js";import{ProfileUpdateDto,RoleMutationDto,TailoringCreateDto,TailoringListQueryDto,UserListQueryDto,UserStatusDto}from"./platform.dto.js";
const BUSINESS=["APPLIER","APPLYING_MANAGER","ADMIN"]as const;
@ApiTags("Profile")@ApiBearerAuth()@Controller("profile")@UseGuards(AuthGuard)export class ProfileController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}@Patch()async update(@Req()r:ApiRequest,@Body(new DtoValidationPipe(ProfileUpdateDto))b:ProfileUpdateDto){return{data:await this.service.profile(r.user!,b.fullName),requestId:r.requestId};}}
@ApiTags("Administration")@ApiBearerAuth()@Controller("admin")@UseGuards(AuthGuard,RolesGuard)@RequireRoles("ADMIN")export class AdministrationController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get("roles")async roles(@Req()r:ApiRequest){return this.out(r,await this.service.roles(r.user!));}@Get("users")async users(@Req()r:ApiRequest,@Query(new DtoValidationPipe(UserListQueryDto))q:UserListQueryDto){return this.out(r,await this.service.users(r.user!,q));}@Get("users/:id")async user(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.user(r.user!,id));}
@Post("users/:id/roles")async addRole(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(RoleMutationDto))b:RoleMutationDto){return this.out(r,await this.service.role(r.user!,id,b.roleCode,true));}@Delete("users/:id/roles/:roleCode")async removeRole(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("roleCode")roleCode:string){const b=await new DtoValidationPipe(RoleMutationDto).transform({roleCode});return this.out(r,await this.service.role(r.user!,id,b.roleCode,false));}@Patch("users/:id/status")async status(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(UserStatusDto))b:UserStatusDto){return this.out(r,await this.service.status(r.user!,id,b.status));}}
@ApiTags("Business Overview")@ApiBearerAuth()@Controller("business-overview")@UseGuards(AuthGuard,RolesGuard)@RequireRoles(...BUSINESS)export class BusinessOverviewController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}@Get()async get(@Req()r:ApiRequest){return{data:await this.service.overview(r.user!),requestId:r.requestId};}}
@ApiTags("Tailoring Queue")@ApiBearerAuth()@Controller("tailoring-jobs")@UseGuards(AuthGuard,RolesGuard)export class TailoringController{constructor(@Inject(TailoringService)private readonly service:TailoringService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get()@RequireRoles(...BUSINESS)async list(@Req()r:ApiRequest,@Query(new DtoValidationPipe(TailoringListQueryDto))q:TailoringListQueryDto){return this.out(r,await this.service.list(r.user!,q.status));}@Post()@RequireRoles("APPLYING_MANAGER","ADMIN")async create(@Req()r:ApiRequest,@Body(new DtoValidationPipe(TailoringCreateDto))b:TailoringCreateDto){return this.out(r,await this.service.create(r.user!,b));}@Patch(":id/cancel")@RequireRoles("APPLYING_MANAGER","ADMIN")async cancel(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.cancel(r.user!,id));}@Get(":id/file-url")@RequireRoles(...BUSINESS)async file(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.fileUrl(r.user!,id));}}
