import{HttpStatus,Inject,Injectable}from"@nestjs/common";import type{AuthenticatedUser}from"@resume-jd/contracts";import{ApiException}from"../common/errors/api.exception.js";import{SupabaseService}from"../supabase/supabase.service.js";
function failure(error:any,fallback:string):never{const raw=String(error?.message||""),known=raw.match(/^([A-Z][A-Z0-9_]+):\s*(.+)$/),code=known?.[1]||(error?.code==="42501"?"ACCESS_DENIED":"DATABASE_ERROR"),status=error?.code==="42501"||code.includes("ACCESS")?403:code.includes("NOT_FOUND")?404:code.includes("EXPIRED")?410:code.includes("CONFLICT")||code.includes("UNAVAILABLE")?409:known?400:502;throw new ApiException(code,known?.[2]||fallback,status);}
@Injectable()export class PlatformService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(u:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(u.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  async roles(u:AuthenticatedUser){const{data,error}=await this.supabase.forUser(u.token).from("roles").select("id,code,name,description,active,is_system,created_at").order("code");if(error)failure(error,"System roles could not be loaded.");return data||[];}
  async users(u:AuthenticatedUser,q:any){const size=q.pageSize||25,page=q.page||1,data:any[]=await this.rpc(u,"admin_list_users_v2",{p_search:q.search||"",p_status:q.status||null,p_role_code:q.roleCode||null,p_sort:q.sort||"created_desc",p_limit:size,p_offset:(page-1)*size},"Users could not be loaded."),total=Number(data?.[0]?.total_count)||0;return{items:data||[],page,pageSize:size,total,totalPages:Math.ceil(total/size)};}
  user=(u:AuthenticatedUser,id:string)=>this.rpc(u,"admin_get_user",{p_user_id:id},"The user could not be loaded.");
  role=(u:AuthenticatedUser,id:string,code:string,assign:boolean)=>this.rpc(u,assign?"admin_assign_role":"admin_remove_role",{p_user_id:id,p_role_code:code},"The role assignment could not be changed.");
  status=(u:AuthenticatedUser,id:string,status:string)=>this.rpc(u,"admin_set_user_status",{p_user_id:id,p_status:status},"The account status could not be changed.");
  profile=(u:AuthenticatedUser,name:string)=>this.rpc(u,"update_my_profile",{p_full_name:String(name||"").trim()},"The profile could not be updated.");
  overview=(u:AuthenticatedUser)=>this.rpc(u,"get_business_overview",{},"The business overview could not be loaded.");
}
@Injectable()export class TailoringService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}
  private async rpc(u:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(u.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  async create(u:AuthenticatedUser,m:any){const unique=new Map<string,any>();for(const item of m.matches)if(!unique.has(item.resumeId))unique.set(item.resumeId,item);return this.rpc(u,"create_tailoring_jobs_v13",{p_job_description_id:m.jobDescriptionId,p_matches:[...unique.values()]} ,"Tailoring jobs could not be created.");}
  requestApplication(u:AuthenticatedUser,applicationId:string){return this.rpc(u,"request_application_tailoring_v13",{p_application_id:applicationId},"The Application tailoring request could not be created.");}
  input(u:AuthenticatedUser,id:string){return this.rpc(u,"get_tailoring_job_input_v13",{p_tailoring_job_id:id},"The sanitized tailoring input could not be loaded.");}
  preview(u:AuthenticatedUser,id:string,b:any){return this.rpc(u,"submit_tailoring_preview_v13",{p_tailoring_job_id:id,p_preview:b.result,p_generated_at:b.generatedAt},"The tailoring preview could not be saved.");}
  ticket(u:AuthenticatedUser,id:string){return this.rpc(u,"create_tailoring_runner_ticket_v15",{p_tailoring_job_id:id},"The local runner ticket could not be created.");}
  review(u:AuthenticatedUser,id:string,b:any){return this.rpc(u,"review_tailoring_preview_v14",{p_tailoring_job_id:id,p_action:b.action,p_preview:b.preview,p_notes:b.notes||"",p_expected_updated_at:b.expectedUpdatedAt},"The tailoring review could not be saved.");}
  reviews(u:AuthenticatedUser,id:string){return this.rpc(u,"get_tailoring_job_reviews_v14",{p_tailoring_job_id:id},"Tailoring review history could not be loaded.");}
  async list(u:AuthenticatedUser,status:string){let q:any=this.supabase.forUser(u.token).from("tailoring_jobs").select("id,application_id,match_score,match_details,status,input_schema_version,output_schema_version,output_preview,preview_generated_at,review_notes,reviewed_by,reviewed_at,created_at,updated_at,applications(application_number),job_descriptions(id,company,job_title),resumes(id,resume_number,resume_type,candidate_name,resume_name,original_filename)").order("updated_at",{ascending:false}).limit(100);if(status!=="ALL")q=q.eq("status",status);const{data,error}=await q;if(error)failure(error,"The tailoring queue could not be loaded.");return data||[];}
  async detail(u:AuthenticatedUser,id:string){const{data,error}=await this.supabase.forUser(u.token).from("tailoring_jobs").select("id,application_id,status,input_schema_version,output_schema_version,output_preview,preview_generated_at,processed_by,failure_code,failure_message,review_notes,reviewed_by,reviewed_at,created_at,updated_at,started_at,completed_at,applications(application_number),job_descriptions(id,company,job_title),resumes(id,resume_number,resume_type,candidate_name,resume_name)").eq("id",id).maybeSingle();if(error)failure(error,"The tailoring job could not be loaded.");if(!data)throw new ApiException("TAILORING_JOB_NOT_FOUND","The tailoring job was not found or is inaccessible.",HttpStatus.NOT_FOUND);return data;}
  cancel(u:AuthenticatedUser,id:string){return this.rpc(u,"cancel_tailoring_job_v13",{p_tailoring_job_id:id},"The pending tailoring job could not be cancelled.");}
  async fileUrl(u:AuthenticatedUser,id:string){const client=this.supabase.forUser(u.token),{data,error}=await client.from("tailoring_jobs").select("resumes(storage_bucket,storage_path,original_filename)").eq("id",id).maybeSingle();if(error)failure(error,"The queue file could not be loaded.");const resume:any=Array.isArray(data?.resumes)?data.resumes[0]:data?.resumes;if(!resume)throw new ApiException("TAILORING_JOB_NOT_FOUND","The tailoring job was not found or is inaccessible.",HttpStatus.NOT_FOUND);const{data:signed,error:signedError}=await client.storage.from(resume.storage_bucket).createSignedUrl(resume.storage_path,90);if(signedError||!signed?.signedUrl)failure(signedError,"The private Resume file could not be opened.");return{signedUrl:signed.signedUrl,expiresInSeconds:90,filename:resume.original_filename};}
}
@Injectable()export class TailoringRunnerService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(name:string,args:any,fallback:string){const{data,error}=await this.supabase.anonymous().rpc(name,args);if(error)failure(error,fallback);return data;}claim(ticket:string){return this.rpc("claim_tailoring_runner_ticket_v15",{p_ticket:ticket},"The runner ticket could not be claimed.");}preview(ticket:string,b:any){return this.rpc("submit_tailoring_runner_preview_v15",{p_ticket:ticket,p_preview:b.result,p_generated_at:b.generatedAt},"The runner preview could not be submitted.");}fail(ticket:string,code:string){return this.rpc("fail_tailoring_runner_v15",{p_ticket:ticket,p_failure_code:code},"The runner failure could not be recorded.");}}
