import{Body,Controller,Delete,Get,Inject,Param,ParseUUIDPipe,Patch,Post,Put,Query,Req,UseGuards}from"@nestjs/common";import{ApiBearerAuth,ApiOperation,ApiTags}from"@nestjs/swagger";import{Throttle}from"@nestjs/throttler";import{AuthGuard}from"../auth/auth.guard.js";import{RequireRoles}from"../auth/require-roles.decorator.js";import{RolesGuard}from"../auth/roles.guard.js";import type{ApiRequest}from"../common/types/request.js";import{DtoValidationPipe}from"../common/validation/dto-validation.pipe.js";import{PlatformService,TailoringRunnerService,TailoringService}from"./platform.service.js";import{FailTailoringRunnerDto,ProfileUpdateDto,ReviewTailoringPreviewDto,RoleMutationDto,SubmitTailoringPreviewDto,SubmitTailoringRunnerPreviewDto,TailoringCreateDto,TailoringListQueryDto,TailoringRunnerTicketDto,UserListQueryDto,UserStatusDto}from"./platform.dto.js";
import{SelectTailoringFormatDto,SelectTailoringTemplateDto}from"./platform.dto.js";
const BUSINESS=["APPLIER","APPLYING_MANAGER","ADMIN"]as const;
@ApiTags("Profile")@ApiBearerAuth()@Controller("profile")@UseGuards(AuthGuard)export class ProfileController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}@Patch()async update(@Req()r:ApiRequest,@Body(new DtoValidationPipe(ProfileUpdateDto))b:ProfileUpdateDto){return{data:await this.service.profile(r.user!,b.fullName),requestId:r.requestId};}}
@ApiTags("Administration")@ApiBearerAuth()@Controller("admin")@UseGuards(AuthGuard,RolesGuard)@RequireRoles("ADMIN")export class AdministrationController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get("roles")async roles(@Req()r:ApiRequest){return this.out(r,await this.service.roles(r.user!));}@Get("users")async users(@Req()r:ApiRequest,@Query(new DtoValidationPipe(UserListQueryDto))q:UserListQueryDto){return this.out(r,await this.service.users(r.user!,q));}@Get("users/:id")async user(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.user(r.user!,id));}
@Post("users/:id/roles")async addRole(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(RoleMutationDto))b:RoleMutationDto){return this.out(r,await this.service.role(r.user!,id,b.roleCode,true));}@Delete("users/:id/roles/:roleCode")async removeRole(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("roleCode")roleCode:string){const b=await new DtoValidationPipe(RoleMutationDto).transform({roleCode});return this.out(r,await this.service.role(r.user!,id,b.roleCode,false));}@Patch("users/:id/status")async status(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(UserStatusDto))b:UserStatusDto){return this.out(r,await this.service.status(r.user!,id,b.status));}}
@ApiTags("Business Overview")@ApiBearerAuth()@Controller("business-overview")@UseGuards(AuthGuard,RolesGuard)@RequireRoles(...BUSINESS)export class BusinessOverviewController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}@Get()async get(@Req()r:ApiRequest){return{data:await this.service.overview(r.user!),requestId:r.requestId};}}
@ApiTags("Tailoring Queue")@ApiBearerAuth()@Controller("tailoring-jobs")@UseGuards(AuthGuard,RolesGuard)export class TailoringController{constructor(@Inject(TailoringService)private readonly service:TailoringService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get()@RequireRoles(...BUSINESS)async list(@Req()r:ApiRequest,@Query(new DtoValidationPipe(TailoringListQueryDto))q:TailoringListQueryDto){return this.out(r,await this.service.list(r.user!,q.status));}
@Get("templates")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"List fixed versioned tailored Resume templates"})async templates(@Req()r:ApiRequest){return this.out(r,this.service.templates());}
@Post()@RequireRoles("APPLYING_MANAGER","ADMIN")async create(@Req()r:ApiRequest,@Body(new DtoValidationPipe(TailoringCreateDto))b:TailoringCreateDto){return this.out(r,await this.service.create(r.user!,b));}
@Post("application/:applicationId")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Request an idempotent Application-scoped tailoring preview"})@Throttle({default:{limit:10,ttl:60000}})async request(@Req()r:ApiRequest,@Param("applicationId",new ParseUUIDPipe({version:"4"}))applicationId:string){return this.out(r,await this.service.requestApplication(r.user!,applicationId));}
@Get(":id/input")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Load the sanitized source contract and mark the job PROCESSING"})@Throttle({default:{limit:20,ttl:60000}})async input(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.input(r.user!,id));}
@Put(":id/preview")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Persist a schema-validated tailoring preview for review"})@Throttle({default:{limit:10,ttl:60000}})async preview(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(SubmitTailoringPreviewDto))b:SubmitTailoringPreviewDto){return this.out(r,await this.service.preview(r.user!,id,b));}
@Post(":id/runner-ticket")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Create a short-lived, job-scoped local runner ticket"})@Throttle({default:{limit:10,ttl:60000}})async ticket(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.ticket(r.user!,id));}
@Patch(":id/review")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Save, approve, or reject a tailoring preview with optimistic concurrency"})@Throttle({default:{limit:20,ttl:60000}})async review(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ReviewTailoringPreviewDto))b:ReviewTailoringPreviewDto){return this.out(r,await this.service.review(r.user!,id,b));}
@Patch(":id/template")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Select an allowlisted DOCX template before materialization"})@Throttle({default:{limit:20,ttl:60000}})async template(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(SelectTailoringTemplateDto))b:SelectTailoringTemplateDto){return this.out(r,await this.service.selectTemplate(r.user!,id,b));}
@Patch(":id/format")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Select DOCX or PDF before materialization"})@Throttle({default:{limit:20,ttl:60000}})async format(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(SelectTailoringFormatDto))b:SelectTailoringFormatDto){return this.out(r,await this.service.selectFormat(r.user!,id,b));}
@Post(":id/materialize")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Render an approved preview with its selected template and artifact format, then atomically assign its TAILORED Resume"})@Throttle({default:{limit:5,ttl:60000}})async materialize(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.materialize(r.user!,id));}
@Get(":id/reviews")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Read immutable tailoring review history"})async reviews(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.reviews(r.user!,id));}
@Patch(":id/cancel")@RequireRoles("APPLYING_MANAGER","ADMIN")async cancel(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.cancel(r.user!,id));}
@Get(":id/file-url")@RequireRoles(...BUSINESS)async file(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.fileUrl(r.user!,id));}
@Get(":id")@RequireRoles(...BUSINESS)async detail(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.detail(r.user!,id));}}
@ApiTags("Tailoring Runner")@Controller("tailoring-runner")export class TailoringRunnerController{constructor(@Inject(TailoringRunnerService)private readonly service:TailoringRunnerService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Post("claim")@ApiOperation({summary:"Claim one short-lived runner capability and load sanitized input"})@Throttle({default:{limit:10,ttl:60000}})async claim(@Req()r:ApiRequest,@Body(new DtoValidationPipe(TailoringRunnerTicketDto))b:TailoringRunnerTicketDto){return this.out(r,await this.service.claim(b.ticket));}
@Put("preview")@ApiOperation({summary:"Submit one validated preview using the claimed capability"})@Throttle({default:{limit:10,ttl:60000}})async preview(@Req()r:ApiRequest,@Body(new DtoValidationPipe(SubmitTailoringRunnerPreviewDto))b:SubmitTailoringRunnerPreviewDto){return this.out(r,await this.service.preview(b.ticket,b));}
@Post("failure")@ApiOperation({summary:"Record a bounded local runner failure"})@Throttle({default:{limit:10,ttl:60000}})async fail(@Req()r:ApiRequest,@Body(new DtoValidationPipe(FailTailoringRunnerDto))b:FailTailoringRunnerDto){return this.out(r,await this.service.fail(b.ticket,b.failureCode));}}
