import{Body,Controller,Delete,Get,Inject,Param,ParseUUIDPipe,Patch,Post,Put,Query,Req,UseGuards}from"@nestjs/common";import{ApiBearerAuth,ApiOperation,ApiTags}from"@nestjs/swagger";import{Throttle}from"@nestjs/throttler";import{AuthGuard}from"../auth/auth.guard.js";import{RequireRoles}from"../auth/require-roles.decorator.js";import{RolesGuard}from"../auth/roles.guard.js";import type{ApiRequest}from"../common/types/request.js";import{DtoValidationPipe}from"../common/validation/dto-validation.pipe.js";import{PlatformService,TailoringService}from"./platform.service.js";import{ProfileUpdateDto,ReviewTailoringPreviewDto,RoleMutationDto,SubmitTailoringPreviewDto,TailoringCreateDto,TailoringListQueryDto,UserListQueryDto,UserStatusDto}from"./platform.dto.js";
const BUSINESS=["APPLIER","APPLYING_MANAGER","ADMIN"]as const;
@ApiTags("Profile")@ApiBearerAuth()@Controller("profile")@UseGuards(AuthGuard)export class ProfileController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}@Patch()async update(@Req()r:ApiRequest,@Body(new DtoValidationPipe(ProfileUpdateDto))b:ProfileUpdateDto){return{data:await this.service.profile(r.user!,b.fullName),requestId:r.requestId};}}
@ApiTags("Administration")@ApiBearerAuth()@Controller("admin")@UseGuards(AuthGuard,RolesGuard)@RequireRoles("ADMIN")export class AdministrationController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get("roles")async roles(@Req()r:ApiRequest){return this.out(r,await this.service.roles(r.user!));}@Get("users")async users(@Req()r:ApiRequest,@Query(new DtoValidationPipe(UserListQueryDto))q:UserListQueryDto){return this.out(r,await this.service.users(r.user!,q));}@Get("users/:id")async user(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.user(r.user!,id));}
@Post("users/:id/roles")async addRole(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(RoleMutationDto))b:RoleMutationDto){return this.out(r,await this.service.role(r.user!,id,b.roleCode,true));}@Delete("users/:id/roles/:roleCode")async removeRole(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("roleCode")roleCode:string){const b=await new DtoValidationPipe(RoleMutationDto).transform({roleCode});return this.out(r,await this.service.role(r.user!,id,b.roleCode,false));}@Patch("users/:id/status")async status(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(UserStatusDto))b:UserStatusDto){return this.out(r,await this.service.status(r.user!,id,b.status));}}
@ApiTags("Business Overview")@ApiBearerAuth()@Controller("business-overview")@UseGuards(AuthGuard,RolesGuard)@RequireRoles(...BUSINESS)export class BusinessOverviewController{constructor(@Inject(PlatformService)private readonly service:PlatformService){}@Get()async get(@Req()r:ApiRequest){return{data:await this.service.overview(r.user!),requestId:r.requestId};}}
@ApiTags("Tailoring Queue")@ApiBearerAuth()@Controller("tailoring-jobs")@UseGuards(AuthGuard,RolesGuard)export class TailoringController{constructor(@Inject(TailoringService)private readonly service:TailoringService){}private out(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get()@RequireRoles(...BUSINESS)async list(@Req()r:ApiRequest,@Query(new DtoValidationPipe(TailoringListQueryDto))q:TailoringListQueryDto){return this.out(r,await this.service.list(r.user!,q.status));}
@Post()@RequireRoles("APPLYING_MANAGER","ADMIN")async create(@Req()r:ApiRequest,@Body(new DtoValidationPipe(TailoringCreateDto))b:TailoringCreateDto){return this.out(r,await this.service.create(r.user!,b));}
@Post("application/:applicationId")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Request an idempotent Application-scoped tailoring preview"})@Throttle({default:{limit:10,ttl:60000}})async request(@Req()r:ApiRequest,@Param("applicationId",new ParseUUIDPipe({version:"4"}))applicationId:string){return this.out(r,await this.service.requestApplication(r.user!,applicationId));}
@Get(":id/input")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Load the sanitized source contract and mark the job PROCESSING"})@Throttle({default:{limit:20,ttl:60000}})async input(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.input(r.user!,id));}
@Put(":id/preview")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Persist a schema-validated tailoring preview for review"})@Throttle({default:{limit:10,ttl:60000}})async preview(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(SubmitTailoringPreviewDto))b:SubmitTailoringPreviewDto){return this.out(r,await this.service.preview(r.user!,id,b));}
@Patch(":id/review")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Save, approve, or reject a tailoring preview with optimistic concurrency"})@Throttle({default:{limit:20,ttl:60000}})async review(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ReviewTailoringPreviewDto))b:ReviewTailoringPreviewDto){return this.out(r,await this.service.review(r.user!,id,b));}
@Get(":id/reviews")@RequireRoles("APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Read immutable tailoring review history"})async reviews(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.reviews(r.user!,id));}
@Patch(":id/cancel")@RequireRoles("APPLYING_MANAGER","ADMIN")async cancel(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.cancel(r.user!,id));}
@Get(":id/file-url")@RequireRoles(...BUSINESS)async file(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.fileUrl(r.user!,id));}
@Get(":id")@RequireRoles(...BUSINESS)async detail(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.out(r,await this.service.detail(r.user!,id));}}
