import{HttpStatus,Inject,Injectable}from"@nestjs/common";import type{AuthenticatedUser}from"@resume-jd/contracts";import{ApiException}from"../common/errors/api.exception.js";import{SupabaseService}from"../supabase/supabase.service.js";
function failure(error:any,fallback:string):never{const raw=String(error?.message||""),known=raw.match(/^([A-Z][A-Z0-9_]+):\s*(.+)$/),code=known?.[1]||(error?.code==="42501"?"ACCESS_DENIED":"DATABASE_ERROR"),status=error?.code==="42501"||code.includes("ACCESS")?403:code.includes("NOT_FOUND")?404:known?400:502;throw new ApiException(code,known?.[2]||fallback,status);}
@Injectable()export class PlatformService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(u:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(u.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  async roles(u:AuthenticatedUser){const{data,error}=await this.supabase.forUser(u.token).from("roles").select("id,code,name,description,active,is_system,created_at").order("code");if(error)failure(error,"System roles could not be loaded.");return data||[];}
  async users(u:AuthenticatedUser,q:any){const size=q.pageSize||25,page=q.page||1,data:any[]=await this.rpc(u,"admin_list_users_v2",{p_search:q.search||"",p_status:q.status||null,p_role_code:q.roleCode||null,p_sort:q.sort||"created_desc",p_limit:size,p_offset:(page-1)*size},"Users could not be loaded."),total=Number(data?.[0]?.total_count)||0;return{items:data||[],page,pageSize:size,total,totalPages:Math.ceil(total/size)};}
  user=(u:AuthenticatedUser,id:string)=>this.rpc(u,"admin_get_user",{p_user_id:id},"The user could not be loaded.");
  role=(u:AuthenticatedUser,id:string,code:string,assign:boolean)=>this.rpc(u,assign?"admin_assign_role":"admin_remove_role",{p_user_id:id,p_role_code:code},"The role assignment could not be changed.");
  status=(u:AuthenticatedUser,id:string,status:string)=>this.rpc(u,"admin_set_user_status",{p_user_id:id,p_status:status},"The account status could not be changed.");
  profile=(u:AuthenticatedUser,name:string)=>this.rpc(u,"update_my_profile",{p_full_name:String(name||"").trim()},"The profile could not be updated.");
  overview=(u:AuthenticatedUser)=>this.rpc(u,"get_business_overview",{},"The business overview could not be loaded.");
}
@Injectable()export class TailoringService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}
  async create(u:AuthenticatedUser,m:any){const unique=new Map<string,any>();for(const item of m.matches)if(!unique.has(item.resumeId))unique.set(item.resumeId,item);const client=this.supabase.forUser(u.token),ids=[...unique.keys()],{data:resumes,error:resumeError}=await client.from("resumes").select("id,storage_path").in("id",ids).eq("status","ACTIVE");if(resumeError)failure(resumeError,"Eligible Resumes could not be loaded.");const found=new Map((resumes||[]).map((r:any)=>[r.id,r])),rows=(resumes||[]).map((resume:any)=>{const match=unique.get(resume.id);return{user_id:u.id,job_description_id:m.jobDescriptionId,resume_id:resume.id,match_score:match.matchScore,match_details:match.matchDetails,source_resume_path:resume.storage_path,status:"PENDING"};}),createdIds=new Set<string>();if(rows.length){const{data,error}=await client.from("tailoring_jobs").upsert(rows,{onConflict:"user_id,job_description_id,resume_id",ignoreDuplicates:true}).select("resume_id");if(error)failure(error,"Tailoring jobs could not be created.");for(const row of data||[])createdIds.add(row.resume_id);}return ids.map(id=>({status:!found.has(id)?"failed":createdIds.has(id)?"created":"alreadyQueued",resumeId:id}));}
  async list(u:AuthenticatedUser,status:string){let q:any=this.supabase.forUser(u.token).from("tailoring_jobs").select("id,match_score,match_details,status,source_resume_path,tailored_resume_path,review_notes,created_at,job_descriptions(id,company,job_title),resumes(id,candidate_name,resume_name,original_filename)").order("created_at",{ascending:false}).limit(100);if(status!=="ALL")q=q.eq("status",status);const{data,error}=await q;if(error)failure(error,"The tailoring queue could not be loaded.");return data||[];}
  async cancel(u:AuthenticatedUser,id:string){const{data,error}=await this.supabase.forUser(u.token).from("tailoring_jobs").update({status:"CANCELLED"}).eq("id",id).eq("status","PENDING").select("id,status").maybeSingle();if(error)failure(error,"The pending tailoring job could not be cancelled.");if(!data)throw new ApiException("TAILORING_JOB_NOT_FOUND","The pending tailoring job was not found or is inaccessible.",HttpStatus.NOT_FOUND);return data;}
  async fileUrl(u:AuthenticatedUser,id:string){const client=this.supabase.forUser(u.token),{data,error}=await client.from("tailoring_jobs").select("resumes(storage_bucket,storage_path,original_filename)").eq("id",id).maybeSingle();if(error)failure(error,"The queue file could not be loaded.");const resume:any=Array.isArray(data?.resumes)?data.resumes[0]:data?.resumes;if(!resume)throw new ApiException("TAILORING_JOB_NOT_FOUND","The tailoring job was not found or is inaccessible.",HttpStatus.NOT_FOUND);const{data:signed,error:signedError}=await client.storage.from(resume.storage_bucket).createSignedUrl(resume.storage_path,90);if(signedError||!signed?.signedUrl)failure(signedError,"The private Resume file could not be opened.");return{signedUrl:signed.signedUrl,expiresInSeconds:90,filename:resume.original_filename};}
}
