import{createHash}from"node:crypto";import{HttpStatus,Inject,Injectable}from"@nestjs/common";import type{AuthenticatedUser}from"@resume-jd/contracts";import{ApiException}from"../common/errors/api.exception.js";import{SupabaseService}from"../supabase/supabase.service.js";import{renderTailoredResumeDocx,TAILORED_RESUME_TEMPLATES}from"./tailored-resume.renderer.js";import{renderTailoredResumePdf}from"./tailored-resume-pdf.renderer.js";
function failure(error:any,fallback:string):never{const raw=String(error?.message||""),known=raw.match(/^([A-Z][A-Z0-9_]+):\s*(.+)$/),code=known?.[1]||(error?.code==="42501"?"ACCESS_DENIED":"DATABASE_ERROR"),status=error?.code==="42501"||code.includes("ACCESS")?403:code.includes("NOT_FOUND")?404:code.includes("EXPIRED")?410:code.includes("CONFLICT")||code.includes("UNAVAILABLE")?409:known?400:502;throw new ApiException(code,known?.[2]||fallback,status);}
@Injectable()export class PlatformService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(u:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(u.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  async roles(u:AuthenticatedUser){const{data,error}=await this.supabase.forUser(u.token).from("roles").select("id,code,name,description,active,is_system,created_at").order("code");if(error)failure(error,"System roles could not be loaded.");return data||[];}
  async users(u:AuthenticatedUser,q:any){const size=q.pageSize||25,page=q.page||1,data:any[]=await this.rpc(u,"admin_list_users_v2",{p_search:q.search||"",p_status:q.status||null,p_role_code:q.roleCode||null,p_sort:q.sort||"created_desc",p_limit:size,p_offset:(page-1)*size},"Users could not be loaded."),total=Number(data?.[0]?.total_count)||0;return{items:data||[],page,pageSize:size,total,totalPages:Math.ceil(total/size)};}
  user=(u:AuthenticatedUser,id:string)=>this.rpc(u,"admin_get_user",{p_user_id:id},"The user could not be loaded.");
  role=(u:AuthenticatedUser,id:string,code:string,assign:boolean)=>this.rpc(u,assign?"admin_assign_role":"admin_remove_role",{p_user_id:id,p_role_code:code},"The role assignment could not be changed.");
  status=(u:AuthenticatedUser,id:string,status:string)=>this.rpc(u,"admin_set_user_status",{p_user_id:id,p_status:status},"The account status could not be changed.");
  profile=(u:AuthenticatedUser,name:string)=>this.rpc(u,"update_my_profile",{p_full_name:String(name||"").trim()},"The profile could not be updated.");
  overview=(u:AuthenticatedUser,from:string,to:string)=>this.rpc(u,"get_business_overview_v30",{p_from:from,p_to:to},"The business overview could not be loaded.");
}
@Injectable()export class TailoringService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}
  private async rpc(u:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(u.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  async create(u:AuthenticatedUser,m:any){const unique=new Map<string,any>();for(const item of m.matches)if(!unique.has(item.resumeId))unique.set(item.resumeId,item);return this.rpc(u,"create_tailoring_jobs_v13",{p_job_description_id:m.jobDescriptionId,p_matches:[...unique.values()]} ,"Tailoring jobs could not be created.");}
  requestApplication(u:AuthenticatedUser,applicationId:string){return this.rpc(u,"request_application_tailoring_v13",{p_application_id:applicationId},"The Application tailoring request could not be created.");}
  bulkRequest(u:AuthenticatedUser,applicationIds:string[]){return this.rpc(u,"request_application_tailoring_bulk_v20",{p_application_ids:[...new Set(applicationIds)]},"The bulk tailoring request could not be created.");}
  bulkTickets(u:AuthenticatedUser,jobIds:string[]){return this.rpc(u,"create_tailoring_runner_tickets_bulk_v20",{p_tailoring_job_ids:[...new Set(jobIds)]},"The bulk runner command could not be created.");}
  input(u:AuthenticatedUser,id:string){return this.rpc(u,"get_tailoring_job_input_v13",{p_tailoring_job_id:id},"The sanitized tailoring input could not be loaded.");}
  preview(u:AuthenticatedUser,id:string,b:any){return this.rpc(u,"submit_tailoring_preview_v13",{p_tailoring_job_id:id,p_preview:b.result,p_generated_at:b.generatedAt},"The tailoring preview could not be saved.");}
  ticket(u:AuthenticatedUser,id:string){return this.rpc(u,"create_tailoring_runner_ticket_v15",{p_tailoring_job_id:id},"The local runner ticket could not be created.");}
  review(u:AuthenticatedUser,id:string,b:any){return this.rpc(u,"review_tailoring_preview_v14",{p_tailoring_job_id:id,p_action:b.action,p_preview:b.preview,p_notes:b.notes||"",p_expected_updated_at:b.expectedUpdatedAt},"The tailoring review could not be saved.");}
  reviews(u:AuthenticatedUser,id:string){return this.rpc(u,"get_tailoring_job_reviews_v14",{p_tailoring_job_id:id},"Tailoring review history could not be loaded.");}
  templates(){return TAILORED_RESUME_TEMPLATES.map(({key,name,description})=>({key,name,description}));}
  selectTemplate(u:AuthenticatedUser,id:string,b:any){return this.rpc(u,"select_tailoring_template_v18",{p_tailoring_job_id:id,p_render_template_key:b.renderTemplateKey,p_expected_updated_at:b.expectedUpdatedAt},"The Resume template could not be selected.");}
  selectFormat(u:AuthenticatedUser,id:string,b:any){return this.rpc(u,"select_tailoring_format_v19",{p_tailoring_job_id:id,p_render_format:b.renderFormat,p_expected_updated_at:b.expectedUpdatedAt},"The Resume artifact format could not be selected.");}
  async list(u:AuthenticatedUser,status:string){let q:any=this.supabase.forUser(u.token).from("tailoring_jobs").select("id,application_id,tailored_resume_id,match_score,match_details,status,render_template_key,template_selected_by,template_selected_at,render_format,format_selected_by,format_selected_at,input_schema_version,output_schema_version,output_preview,preview_generated_at,review_notes,reviewed_by,reviewed_at,materialized_by,materialized_at,created_at,updated_at,applications(application_number),job_descriptions(id,company,job_title),resumes:resumes!tailoring_jobs_resume_id_fkey(id,resume_number,resume_type,candidate_name,resume_name,original_filename),tailored_resume:resumes!tailoring_jobs_tailored_resume_id_fkey(id,resume_number,resume_type,resume_name,original_filename,render_template_key,render_format)").order("updated_at",{ascending:false}).limit(100);if(status!=="ALL")q=q.eq("status",status);const{data,error}=await q;if(error)failure(error,"The tailoring queue could not be loaded.");return data||[];}
  async detail(u:AuthenticatedUser,id:string){const{data,error}=await this.supabase.forUser(u.token).from("tailoring_jobs").select("id,application_id,tailored_resume_id,status,render_template_key,template_selected_by,template_selected_at,render_format,format_selected_by,format_selected_at,input_schema_version,output_schema_version,output_preview,preview_generated_at,processed_by,failure_code,failure_message,review_notes,reviewed_by,reviewed_at,materialized_by,materialized_at,created_at,updated_at,started_at,completed_at,applications(application_number),job_descriptions(id,company,job_title),resumes:resumes!tailoring_jobs_resume_id_fkey(id,resume_number,resume_type,candidate_name,resume_name,skills,structured_content),tailored_resume:resumes!tailoring_jobs_tailored_resume_id_fkey(id,resume_number,resume_type,resume_name,original_filename,render_template_key,render_format)").eq("id",id).maybeSingle();if(error)failure(error,"The tailoring job could not be loaded.");if(!data)throw new ApiException("TAILORING_JOB_NOT_FOUND","The tailoring job was not found or is inaccessible.",HttpStatus.NOT_FOUND);return data;}
  async materialize(u:AuthenticatedUser,id:string){const client=this.supabase.forUser(u.token),started:any=await this.rpc(u,"begin_tailoring_materialization_v19",{p_tailoring_job_id:id},"The approved Resume could not start rendering.");if(started?.alreadyMaterialized)return started;let uploaded=false,phase:"RENDER_FAILED"|"UPLOAD_FAILED"|"FINALIZE_FAILED"="RENDER_FAILED";try{if(!["DOCX","PDF"].includes(started.renderFormat))throw new ApiException("TAILORING_FORMAT_INVALID","The reserved artifact format is invalid.",HttpStatus.BAD_GATEWAY);const isPdf=started.renderFormat==="PDF",mime=isPdf?"application/pdf":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",bytes=isPdf?await renderTailoredResumePdf(started):await renderTailoredResumeDocx(started);if(!bytes.length||bytes.length>5242880)throw new ApiException("TAILORING_ARTIFACT_INVALID",`The rendered ${isPdf?"PDF":"DOCX"} must be between 1 byte and 5 MiB.`,HttpStatus.BAD_GATEWAY);phase="UPLOAD_FAILED";await client.storage.from(started.targetBucket).remove([started.targetPath]);const uploadedResult=await client.storage.from(started.targetBucket).upload(started.targetPath,bytes,{contentType:mime,upsert:false});if(uploadedResult.error)failure(uploadedResult.error,"The private tailored Resume could not be uploaded.");uploaded=true;phase="FINALIZE_FAILED";return await this.rpc(u,"finalize_tailoring_materialization_v19",{p_tailoring_job_id:id,p_materialization_token:started.materializationToken,p_storage_path:started.targetPath,p_original_filename:started.filename,p_mime_type:mime,p_file_size_bytes:bytes.length,p_file_sha256:createHash("sha256").update(bytes).digest("hex")},"The tailored Resume could not be finalized.");}catch(error){if(uploaded)await client.storage.from(started.targetBucket).remove([started.targetPath]);try{await this.rpc(u,"fail_tailoring_materialization_v16",{p_tailoring_job_id:id,p_materialization_token:started.materializationToken,p_failure_code:phase},"The materialization failure could not be recorded.");}catch{}if(error instanceof ApiException)throw error;throw new ApiException(phase,"The approved content remains available. Retry Resume creation.",HttpStatus.BAD_GATEWAY);}}
  cancel(u:AuthenticatedUser,id:string){return this.rpc(u,"cancel_tailoring_job_v13",{p_tailoring_job_id:id},"The pending tailoring job could not be cancelled.");}
  async fileUrl(u:AuthenticatedUser,id:string){const client=this.supabase.forUser(u.token),{data,error}=await client.from("tailoring_jobs").select("render_template_key,render_format,resumes:resumes!tailoring_jobs_resume_id_fkey(storage_bucket,storage_path,original_filename,resume_number,resume_type,render_template_key,render_format),tailored_resume:resumes!tailoring_jobs_tailored_resume_id_fkey(storage_bucket,storage_path,original_filename,resume_number,resume_type,render_template_key,render_format)").eq("id",id).maybeSingle();if(error)failure(error,"The queue file could not be loaded.");const relation:any=(data as any)?.tailored_resume||(data as any)?.resumes,resume:any=Array.isArray(relation)?relation[0]:relation;if(!resume)throw new ApiException("TAILORING_JOB_NOT_FOUND","The tailoring job was not found or is inaccessible.",HttpStatus.NOT_FOUND);const{data:signed,error:signedError}=await client.storage.from(resume.storage_bucket).createSignedUrl(resume.storage_path,90);if(signedError||!signed?.signedUrl)failure(signedError,"The private Resume file could not be opened.");return{signedUrl:signed.signedUrl,expiresInSeconds:90,filename:resume.original_filename,resumeNumber:resume.resume_number,resumeType:resume.resume_type,renderTemplateKey:resume.render_template_key||(data as any)?.render_template_key||null,renderFormat:resume.render_format||(data as any)?.render_format||null};}
}
@Injectable()export class TailoringRunnerService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(name:string,args:any,fallback:string){const{data,error}=await this.supabase.anonymous().rpc(name,args);if(error)failure(error,fallback);return data;}claim(ticket:string){return this.rpc("claim_tailoring_runner_ticket_v15",{p_ticket:ticket},"The runner ticket could not be claimed.");}preview(ticket:string,b:any){return this.rpc("submit_tailoring_runner_preview_v15",{p_ticket:ticket,p_preview:b.result,p_generated_at:b.generatedAt},"The runner preview could not be submitted.");}fail(ticket:string,code:string){return this.rpc("fail_tailoring_runner_v15",{p_ticket:ticket,p_failure_code:code},"The runner failure could not be recorded.");}}
