import{HttpStatus,Inject,Injectable}from"@nestjs/common";import type{AuthenticatedUser}from"@resume-jd/contracts";import{ApiException}from"../common/errors/api.exception.js";import{SupabaseService}from"../supabase/supabase.service.js";
function failure(error:any,fallback:string):never{const raw=String(error?.message||""),known=raw.match(/^([A-Z][A-Z0-9_]+):\s*(.+)$/),code=known?.[1]||(error?.code==="42501"?"ACCESS_DENIED":"DATABASE_ERROR"),status=error?.code==="42501"?403:code.includes("NOT_FOUND")?404:code.includes("EXPIRED")?410:code.includes("UNAVAILABLE")||code.includes("LEASE")?409:known?400:502;throw new ApiException(code,known?.[2]||fallback,status);}
@Injectable()export class TailoringBatchService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(u:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(u.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  create(u:AuthenticatedUser,b:any){return this.rpc(u,"create_tailoring_batch_v21",{p_application_ids:b.applicationIds,p_name:String(b.name||"").trim()||null},"The tailoring batch could not be created.");}
  ticket(u:AuthenticatedUser,id:string){return this.rpc(u,"create_tailoring_batch_ticket_v21",{p_batch_id:id},"The batch runner command could not be created.");}
  retry(u:AuthenticatedUser,id:string,itemIds?:string[]){return this.rpc(u,"retry_tailoring_batch_items_v21",{p_batch_id:id,p_item_ids:itemIds?.length?itemIds:null},"No failed tailoring items could be retried.");}
  cancel(u:AuthenticatedUser,id:string){return this.rpc(u,"cancel_tailoring_batch_v21",{p_batch_id:id},"The tailoring batch could not be cancelled.");}
  async list(u:AuthenticatedUser){const{data,error}=await this.supabase.forUser(u.token).from("tailoring_batches").select("*").order("created_at",{ascending:false}).limit(100);if(error)failure(error,"Tailoring batches could not be loaded.");return data||[];}
  async detail(u:AuthenticatedUser,id:string){const client=this.supabase.forUser(u.token),[batchResult,itemResult]=await Promise.all([client.from("tailoring_batches").select("*").eq("id",id).maybeSingle(),client.from("tailoring_batch_items").select("*,applications(application_number),tailoring_jobs(id,status,job_descriptions(company,job_title),resumes:resumes!tailoring_jobs_resume_id_fkey(resume_number,resume_name,candidate_name))").eq("batch_id",id).order("ordinal")]);if(batchResult.error)failure(batchResult.error,"The tailoring batch could not be loaded.");if(!batchResult.data)throw new ApiException("TAILORING_BATCH_NOT_FOUND","The tailoring batch was not found.",HttpStatus.NOT_FOUND);if(itemResult.error)failure(itemResult.error,"Tailoring batch items could not be loaded.");return{batch:batchResult.data,items:itemResult.data||[]};}
}
@Injectable()export class TailoringBatchRunnerService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}private async rpc(name:string,args:any,fallback:string){const{data,error}=await this.supabase.anonymous().rpc(name,args);if(error)failure(error,fallback);return data;}
  claim(ticket:string){return this.rpc("claim_tailoring_batch_ticket_v21",{p_ticket:ticket},"The batch ticket could not be claimed.");}
  next(ticket:string){return this.rpc("next_tailoring_batch_item_v21",{p_ticket:ticket},"The next tailoring item could not be leased.");}
  preview(b:any){return this.rpc("submit_tailoring_batch_preview_v21",{p_ticket:b.ticket,p_item_id:b.itemId,p_lease_token:b.leaseToken,p_preview:b.result,p_generated_at:b.generatedAt},"The tailoring preview could not be submitted.");}
  fail(b:any){return this.rpc("fail_tailoring_batch_item_v21",{p_ticket:b.ticket,p_item_id:b.itemId,p_lease_token:b.leaseToken,p_stage:b.stage,p_code:b.code,p_message:b.message,p_retryable:b.retryable,p_rate_limited:b.rateLimited,p_retry_after_seconds:b.retryAfterSeconds||null},"The tailoring failure could not be recorded.");}
}
