export type TailoredResumeTemplateKey="CLASSIC_V1"|"MODERN_V1"|"COMPACT_V1"|"EXECUTIVE_V1"|"TECHNICAL_V1"|"MINIMAL_V1"|"CORPORATE_V1"|"ELEGANT_V1"|"SLATE_V1"|"EMERALD_V1"|"ACADEMIC_V1"|"IMPACT_V1";
export type TailoredResumeTemplateSpec={key:TailoredResumeTemplateKey;name:string;description:string;font:string;fontSize:number;nameSize:number;accent:string;nameColor:string;nameAlignment:"left"|"center";margin:number;line:number;compact:boolean;uppercaseHeadings:boolean;headingRule:boolean};

export const TAILORED_RESUME_TEMPLATES:ReadonlyArray<Readonly<TailoredResumeTemplateSpec>>=Object.freeze([
  Object.freeze({key:"CLASSIC_V1",name:"Classic",description:"Traditional centered header with blue section rules.",font:"Arial",fontSize:20,nameSize:32,accent:"2F75B5",nameColor:"000000",nameAlignment:"center",margin:720,line:276,compact:false,uppercaseHeadings:false,headingRule:true}),
  Object.freeze({key:"MODERN_V1",name:"Modern",description:"Left-aligned header, navy typography, and teal section accents.",font:"Aptos",fontSize:20,nameSize:34,accent:"007C83",nameColor:"17365D",nameAlignment:"left",margin:800,line:276,compact:false,uppercaseHeadings:true,headingRule:true}),
  Object.freeze({key:"COMPACT_V1",name:"Compact",description:"Space-efficient layout for longer professional histories.",font:"Calibri",fontSize:18,nameSize:29,accent:"404040",nameColor:"000000",nameAlignment:"center",margin:500,line:240,compact:true,uppercaseHeadings:false,headingRule:true}),
  Object.freeze({key:"EXECUTIVE_V1",name:"Executive",description:"Refined serif layout with restrained spacing for leadership resumes.",font:"Georgia",fontSize:20,nameSize:35,accent:"1F4E79",nameColor:"1F4E79",nameAlignment:"center",margin:760,line:276,compact:false,uppercaseHeadings:false,headingRule:false}),
  Object.freeze({key:"TECHNICAL_V1",name:"Technical",description:"Dense left-aligned layout optimized for engineering skills and projects.",font:"Aptos",fontSize:19,nameSize:32,accent:"375A7F",nameColor:"25364A",nameAlignment:"left",margin:600,line:250,compact:true,uppercaseHeadings:true,headingRule:true}),
  Object.freeze({key:"MINIMAL_V1",name:"Minimal",description:"Monochrome, rule-free layout with maximum ATS simplicity.",font:"Arial",fontSize:19,nameSize:30,accent:"222222",nameColor:"111111",nameAlignment:"left",margin:720,line:260,compact:false,uppercaseHeadings:false,headingRule:false}),
  Object.freeze({key:"CORPORATE_V1",name:"Corporate",description:"Structured navy layout for enterprise and consulting roles.",font:"Calibri",fontSize:20,nameSize:33,accent:"203864",nameColor:"203864",nameAlignment:"left",margin:720,line:270,compact:false,uppercaseHeadings:true,headingRule:true}),
  Object.freeze({key:"ELEGANT_V1",name:"Elegant",description:"Serif typography with burgundy accents for polished professional profiles.",font:"Georgia",fontSize:19,nameSize:33,accent:"7A263A",nameColor:"5A1D2B",nameAlignment:"center",margin:760,line:270,compact:false,uppercaseHeadings:false,headingRule:false}),
  Object.freeze({key:"SLATE_V1",name:"Slate",description:"Compact charcoal layout for detailed technical histories.",font:"Aptos",fontSize:19,nameSize:31,accent:"455A64",nameColor:"263238",nameAlignment:"left",margin:650,line:250,compact:true,uppercaseHeadings:false,headingRule:false}),
  Object.freeze({key:"EMERALD_V1",name:"Emerald",description:"Clean green-accent layout for modern operations and product roles.",font:"Calibri",fontSize:20,nameSize:32,accent:"1B6B57",nameColor:"174D40",nameAlignment:"left",margin:700,line:270,compact:false,uppercaseHeadings:false,headingRule:true}),
  Object.freeze({key:"ACADEMIC_V1",name:"Academic",description:"Formal serif layout for research, education, and analytical careers.",font:"Times New Roman",fontSize:20,nameSize:32,accent:"333333",nameColor:"111111",nameAlignment:"center",margin:720,line:276,compact:false,uppercaseHeadings:false,headingRule:false}),
  Object.freeze({key:"IMPACT_V1",name:"Impact",description:"Strong oversized name and bold section rules for concise senior profiles.",font:"Arial",fontSize:20,nameSize:36,accent:"174A7E",nameColor:"174A7E",nameAlignment:"left",margin:620,line:260,compact:false,uppercaseHeadings:true,headingRule:true}),
]);
export const TAILORED_RESUME_TEMPLATE_KEYS:ReadonlyArray<TailoredResumeTemplateKey>=Object.freeze(TAILORED_RESUME_TEMPLATES.map(item=>item.key));
const TEMPLATE_BY_KEY=new Map(TAILORED_RESUME_TEMPLATES.map(item=>[item.key,item]));
export function resolveTailoredResumeTemplate(value:unknown):Readonly<TailoredResumeTemplateSpec>{const key=String(value||"CLASSIC_V1").toUpperCase() as TailoredResumeTemplateKey,spec=TEMPLATE_BY_KEY.get(key);if(!spec)throw new Error("TAILORING_TEMPLATE_INVALID");return spec;}
