import{HttpStatus,Inject,Injectable}from"@nestjs/common";import type{AuthenticatedUser}from"@resume-jd/contracts";import{randomUUID}from"node:crypto";import{ApiException}from"../common/errors/api.exception.js";import{SupabaseService}from"../supabase/supabase.service.js";
const safeName=(value:string)=>String(value||"file").normalize("NFKC").replace(/[^A-Za-z0-9._-]+/g,"_").replace(/^\.+/,"").slice(-180)||"file";
function failure(error:any,fallback:string):never{const raw=String(error?.message||""),known=raw.match(/^([A-Z][A-Z0-9_]+):\s*(.+)$/),code=known?.[1]||(error?.code==="42501"?"APPLICATION_ACCESS_DENIED":"DATABASE_ERROR"),message=known?.[2]||fallback,status=error?.code==="42501"||code.includes("ACCESS_DENIED")?HttpStatus.FORBIDDEN:code.includes("NOT_FOUND")?HttpStatus.NOT_FOUND:code.includes("DUPLICATE")?HttpStatus.CONFLICT:known?HttpStatus.BAD_REQUEST:HttpStatus.BAD_GATEWAY;throw new ApiException(code,message,status);}
@Injectable()export class ApplicationService{constructor(@Inject(SupabaseService)private readonly supabase:SupabaseService){}
  private async rpc(user:AuthenticatedUser,name:string,args:any,fallback:string){const{data,error}=await this.supabase.forUser(user.token).rpc(name,args);if(error)failure(error,fallback);return data;}
  list(user:AuthenticatedUser,q:any){return this.rpc(user,"list_applications_cursor",{p_search:q.search||"",p_assigned_to:q.assignedTo||null,p_work_status:q.workStatus||"",p_application_status:q.applicationStatus||"",p_priority:q.priority||"",p_company:q.company||"",p_category_id:q.categoryId||null,p_due_filter:q.dueFilter||"",p_creation_batch_id:q.creationBatchId||null,p_creation_mode:q.creationMode||"",p_cursor_updated_at:q.cursorUpdatedAt||null,p_cursor_id:q.cursorId||null,p_limit:q.pageSize||25},"Applications could not be loaded.");}
  mine(user:AuthenticatedUser,q:any){return this.rpc(user,"list_applications_v07",{p_search:"",p_assigned_to:null,p_work_status:"",p_application_status:q.applicationStatus||"",p_priority:"",p_company:"",p_category_id:null,p_due_filter:"",p_sort:q.sort||"updated_desc",p_creation_batch_id:null,p_creation_mode:"",p_limit:Math.min(Number(q.limit)||100,100),p_offset:0},"Your Applications could not be loaded.");}
  detail=(u:AuthenticatedUser,id:string)=>this.rpc(u,"get_application_detail",{p_application_id:id},"The Application could not be loaded.");
  counts=(u:AuthenticatedUser)=>this.rpc(u,"get_application_counts",{},"Application counts could not be loaded.");
  appliers=(u:AuthenticatedUser,s="")=>this.rpc(u,"list_active_appliers",{p_search:s,p_limit:200},"Active Appliers could not be loaded.");
  jobs=(u:AuthenticatedUser,s="")=>this.rpc(u,"list_application_jobs",{p_search:s,p_limit:200},"Job descriptions could not be loaded.");
  resumes=(u:AuthenticatedUser,id:string,s="")=>this.rpc(u,"list_application_resumes",{p_job_description_id:id,p_search:s,p_limit:200},"Active Resumes could not be loaded.");
  create=(u:AuthenticatedUser,m:any)=>this.rpc(u,"create_application",{p_job_description_id:m.jobDescriptionId,p_resume_id:m.resumeId,p_assigned_to:m.assignedTo||null,p_priority:m.priority,p_due_at:m.dueAt||null,p_notes:m.notes||null},"The Application could not be created.");
  update=(u:AuthenticatedUser,id:string,m:any)=>this.rpc(u,"update_application_progress",{p_application_id:id,p_work_status:m.workStatus,p_application_status:m.applicationStatus,p_application_url:m.applicationUrl||null,p_applied_at:m.appliedAt||null,p_notes:m.notes||null,p_priority:m.priority??null,p_due_at:m.dueAt??null},"The Application could not be updated.");
  assign=(u:AuthenticatedUser,id:string,m:any)=>this.rpc(u,"reassign_application",{p_application_id:id,p_new_assignee_id:m.newAssigneeId||null,p_reason:m.reason||null},"The assignment could not be changed.");
  bulkAssign=(u:AuthenticatedUser,m:any)=>this.rpc(u,"bulk_assign_applications",{p_application_ids:[...new Set(m.applicationIds)],p_new_assignee_id:m.newAssigneeId||null,p_reason:m.reason||null},"The selected Applications could not be assigned.");
  preview=(u:AuthenticatedUser,m:any)=>this.rpc(u,"preview_bulk_applications",{p_selected_jd_ids:[...new Set(m.jobDescriptionIds)]},"The bulk preview could not be generated.");
  bulkCreate=(u:AuthenticatedUser,m:any)=>this.rpc(u,"create_applications_bulk",{p_combinations:m.combinations,p_batch_name:String(m.batchName||"").trim()||null},"The bulk Applications could not be created.");
  async batches(u:AuthenticatedUser,q:any){const size=q.pageSize||25,page=q.page||1,data:any=await this.rpc(u,"list_application_batches_v2",{p_search:q.search||"",p_status:q.status||"",p_sort:q.sort||"created_desc",p_limit:size,p_offset:(page-1)*size},"Application batches could not be loaded."),total=Number(data?.total)||0,pageCount=total?Math.ceil(total/size):0;return{...data,total,page:pageCount?Math.min(page,pageCount):1,pageSize:size,pageCount,from:total?(page-1)*size+1:0,to:Math.min(page*size,total),hasPrevious:page>1,hasNext:page<pageCount};}
  batchOptions=(u:AuthenticatedUser)=>this.rpc(u,"list_application_batch_options",{p_limit:200},"Batch options could not be loaded.");
  batch=(u:AuthenticatedUser,id:string)=>this.rpc(u,"get_application_batch_detail",{p_batch_id:id},"The Application batch could not be loaded.");
  async resumeUrl(u:AuthenticatedUser,id:string){const file:any=await this.rpc(u,"get_application_resume_file",{p_application_id:id},"The Resume is not available for this Application."),{data,error}=await this.supabase.forUser(u.token).storage.from(file.bucket).createSignedUrl(file.path,90);if(error||!data?.signedUrl)failure(error,"The private Resume file could not be opened.");return{signedUrl:data.signedUrl,expiresInSeconds:90,filename:file.filename};}
  async screenshots(u:AuthenticatedUser,id:string){const{data,error}=await this.supabase.forUser(u.token).from("application_screenshots").select("id,storage_bucket,storage_path,original_filename,mime_type,file_size_bytes,created_at").eq("application_id",id).order("created_at",{ascending:false});if(error)failure(error,"Screenshots could not be loaded.");return data||[];}
  async addScreenshot(u:AuthenticatedUser,id:string,file:any){const allowed=["image/png","image/jpeg","image/webp","application/pdf"];if(!file||file.size<1||file.size>5242880||!allowed.includes(file.mimetype))throw new ApiException("APPLICATION_SCREENSHOT_INVALID","Use a PNG, JPG, WEBP, or PDF file between 1 byte and 5 MiB.",HttpStatus.BAD_REQUEST);const path=`${id}/${randomUUID()}-${safeName(file.originalname)}`,client=this.supabase.forUser(u.token),uploaded=await client.storage.from("application-screenshots").upload(path,file.buffer,{contentType:file.mimetype,upsert:false});if(uploaded.error)failure(uploaded.error,"The screenshot file could not be uploaded.");try{return await this.rpc(u,"attach_application_screenshot",{p_application_id:id,p_storage_path:path,p_original_filename:file.originalname,p_mime_type:file.mimetype,p_file_size_bytes:file.size},"The screenshot could not be attached.");}catch(error){await client.storage.from("application-screenshots").remove([path]);throw error;}}
  async removeScreenshot(u:AuthenticatedUser,id:string,screenshotId:string){const client=this.supabase.forUser(u.token),{data:existing,error:lookupError}=await client.from("application_screenshots").select("id").eq("application_id",id).eq("id",screenshotId).maybeSingle();if(lookupError)failure(lookupError,"The screenshot could not be loaded.");if(!existing)throw new ApiException("APPLICATION_SCREENSHOT_NOT_FOUND","The screenshot was not found.",HttpStatus.NOT_FOUND);const result:any=await this.rpc(u,"remove_application_screenshot",{p_screenshot_id:screenshotId},"The screenshot could not be removed.");if(result?.storagePath)await client.storage.from(result.storageBucket||"application-screenshots").remove([result.storagePath]);return result;}
  async screenshotUrl(u:AuthenticatedUser,id:string,screenshotId:string){const{data:row,error}=await this.supabase.forUser(u.token).from("application_screenshots").select("storage_bucket,storage_path,original_filename").eq("application_id",id).eq("id",screenshotId).maybeSingle();if(error)failure(error,"The screenshot could not be loaded.");if(!row)throw new ApiException("APPLICATION_SCREENSHOT_NOT_FOUND","The screenshot was not found.",HttpStatus.NOT_FOUND);const{data,error:storageError}=await this.supabase.forUser(u.token).storage.from(row.storage_bucket).createSignedUrl(row.storage_path,90);if(storageError||!data?.signedUrl)failure(storageError,"The private screenshot could not be opened.");return{signedUrl:data.signedUrl,expiresInSeconds:90,filename:row.original_filename};}
}
