import{Body,Controller,Delete,Get,Inject,Param,ParseUUIDPipe,Patch,Post,Query,Req,UploadedFile,UseGuards,UseInterceptors}from"@nestjs/common";import{FileInterceptor}from"@nestjs/platform-express";import{ApiBearerAuth,ApiOperation,ApiTags}from"@nestjs/swagger";import{Throttle}from"@nestjs/throttler";import{AuthGuard}from"../auth/auth.guard.js";import{RequireRoles}from"../auth/require-roles.decorator.js";import{RolesGuard}from"../auth/roles.guard.js";import{DtoValidationPipe}from"../common/validation/dto-validation.pipe.js";import type{ApiRequest}from"../common/types/request.js";import{ApplicationService}from"./application.service.js";import{ApplicationAutofillContextQueryDto,ApplicationListQueryDto,CreateApplicationDto,CreateApplicationExtensionSessionDto,MyApplicationQueryDto,ReassignApplicationDto,ResumeAccessDto,ResumeOptionsQueryDto,SearchOptionsQueryDto,UpdateApplicationDto,UpdateApplicationExtensionSessionDto}from"./application.dto.js";
import{ApplicationCountQueryDto}from"./application.dto.js";
const ALL=["APPLIER","APPLYING_MANAGER","DEVELOPER","DEVELOPMENT_MANAGER","ADMIN"]as const,MANAGERS=["APPLYING_MANAGER","ADMIN"]as const;
@ApiTags("Applications")@ApiBearerAuth()@Controller("applications")@UseGuards(AuthGuard,RolesGuard)export class ApplicationController{constructor(@Inject(ApplicationService)private readonly service:ApplicationService){}private response(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get()@RequireRoles(...ALL)async list(@Req()r:ApiRequest,@Query(new DtoValidationPipe(ApplicationListQueryDto))q:ApplicationListQueryDto){return this.response(r,await this.service.list(r.user!,q));}
@Get("mine")@RequireRoles("APPLIER")async mine(@Req()r:ApiRequest,@Query(new DtoValidationPipe(MyApplicationQueryDto))q:MyApplicationQueryDto){return this.response(r,await this.service.mine(r.user!,q));}
@Get("counts")@RequireRoles(...ALL)async counts(@Req()r:ApiRequest,@Query(new DtoValidationPipe(ApplicationCountQueryDto))q:ApplicationCountQueryDto){return this.response(r,await this.service.counts(r.user!,q.from,q.to));}
@Get("profile-workload")@RequireRoles("APPLIER","ADMIN")@ApiOperation({summary:"Overview workload by mapped Resume profile (own for Appliers, all for Admins)"})async profileWorkload(@Req()r:ApiRequest,@Query(new DtoValidationPipe(ApplicationCountQueryDto))q:ApplicationCountQueryDto){return this.response(r,await this.service.profileWorkload(r.user!,q.from,q.to));}
@Get("appliers")@RequireRoles(...ALL)async appliers(@Req()r:ApiRequest,@Query(new DtoValidationPipe(SearchOptionsQueryDto))q:SearchOptionsQueryDto){return this.response(r,await this.service.appliers(r.user!,q.search));}
@Get("options/jobs")@RequireRoles(...MANAGERS)async jobs(@Req()r:ApiRequest,@Query(new DtoValidationPipe(SearchOptionsQueryDto))q:SearchOptionsQueryDto){return this.response(r,await this.service.jobs(r.user!,q.search));}
@Get("options/resumes")@RequireRoles(...MANAGERS)async resumes(@Req()r:ApiRequest,@Query(new DtoValidationPipe(ResumeOptionsQueryDto))q:ResumeOptionsQueryDto){return this.response(r,await this.service.resumes(r.user!,q.jobDescriptionId,q.search));}
@Post()@RequireRoles(...MANAGERS)async create(@Req()r:ApiRequest,@Body(new DtoValidationPipe(CreateApplicationDto))body:CreateApplicationDto){return this.response(r,await this.service.create(r.user!,body));}
@Get(":id/extension-context")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Get minimal authorized Application context for the extension"})@Throttle({default:{limit:30,ttl:60000}})async extensionContext(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.extensionContext(r.user!,id));}
@Post(":id/extension-sessions")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Create a short-lived Application-to-extension handoff session"})@Throttle({default:{limit:20,ttl:60000}})async createExtensionSession(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(CreateApplicationExtensionSessionDto))body:CreateApplicationExtensionSessionDto){return this.response(r,await this.service.createExtensionSession(r.user!,id,body));}
@Post(":id/resume-access")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Create short-lived access to the exact Resume connected to an Application"})@Throttle({default:{limit:20,ttl:60000}})async resumeAccess(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ResumeAccessDto))_body:ResumeAccessDto){return this.response(r,await this.service.resumeAccess(r.user!,id));}
@Get(":id/autofill-context")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")@ApiOperation({summary:"Load verified Resume values and approved screening answers for an active Autofill session"})@Throttle({default:{limit:30,ttl:60000}})async autofillContext(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Query(new DtoValidationPipe(ApplicationAutofillContextQueryDto))q:ApplicationAutofillContextQueryDto){return this.response(r,await this.service.autofillContext(r.user!,id,q));}
@Get(":id/resume-file-url")@RequireRoles(...ALL)async resumeUrl(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.resumeUrl(r.user!,id));}
@Get(":id/screenshots")@RequireRoles(...ALL)async screenshots(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.screenshots(r.user!,id));}
@Post(":id/screenshots")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")@UseInterceptors(FileInterceptor("file",{limits:{fileSize:5242880,files:1}}))async addScreenshot(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@UploadedFile()file:any){return this.response(r,await this.service.addScreenshot(r.user!,id,file));}
@Delete(":id/screenshots/:screenshotId")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")async removeScreenshot(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("screenshotId",new ParseUUIDPipe({version:"4"}))screenshotId:string){return this.response(r,await this.service.removeScreenshot(r.user!,id,screenshotId));}
@Get(":id/screenshots/:screenshotId/file-url")@RequireRoles(...ALL)async screenshotUrl(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("screenshotId",new ParseUUIDPipe({version:"4"}))screenshotId:string){return this.response(r,await this.service.screenshotUrl(r.user!,id,screenshotId));}
@Patch(":id/progress")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")async update(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(UpdateApplicationDto))body:UpdateApplicationDto){return this.response(r,await this.service.update(r.user!,id,body));}
@Patch(":id/assignment")@RequireRoles(...MANAGERS)async assign(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ReassignApplicationDto))body:ReassignApplicationDto){return this.response(r,await this.service.assign(r.user!,id,body));}
@Get(":id")@RequireRoles(...ALL)async detail(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.detail(r.user!,id));}}

@ApiTags("Extension sessions")@ApiBearerAuth()@Controller("extension-sessions")@UseGuards(AuthGuard,RolesGuard)@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")export class ExtensionSessionController{constructor(@Inject(ApplicationService)private readonly service:ApplicationService){}@Patch(":id")@ApiOperation({summary:"Update an owned Application extension session"})@Throttle({default:{limit:60,ttl:60000}})async update(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(UpdateApplicationExtensionSessionDto))body:UpdateApplicationExtensionSessionDto){return{data:await this.service.updateExtensionSession(r.user!,id,body),requestId:r.requestId};}}
