import{Body,Controller,Delete,Get,Inject,Param,ParseUUIDPipe,Patch,Post,Query,Req,UploadedFile,UseGuards,UseInterceptors}from"@nestjs/common";import{FileInterceptor}from"@nestjs/platform-express";import{ApiBearerAuth,ApiTags}from"@nestjs/swagger";import{AuthGuard}from"../auth/auth.guard.js";import{RequireRoles}from"../auth/require-roles.decorator.js";import{RolesGuard}from"../auth/roles.guard.js";import{DtoValidationPipe}from"../common/validation/dto-validation.pipe.js";import type{ApiRequest}from"../common/types/request.js";import{ApplicationService}from"./application.service.js";import{ApplicationListQueryDto,BulkAssignApplicationDto,CreateApplicationDto,MyApplicationQueryDto,ReassignApplicationDto,ResumeOptionsQueryDto,SearchOptionsQueryDto,UpdateApplicationDto}from"./application.dto.js";
const ALL=["APPLIER","APPLYING_MANAGER","DEVELOPER","DEVELOPMENT_MANAGER","ADMIN"]as const,MANAGERS=["APPLYING_MANAGER","ADMIN"]as const;
@ApiTags("Applications")@ApiBearerAuth()@Controller("applications")@UseGuards(AuthGuard,RolesGuard)export class ApplicationController{constructor(@Inject(ApplicationService)private readonly service:ApplicationService){}private response(r:ApiRequest,data:any){return{data,requestId:r.requestId};}
@Get()@RequireRoles(...ALL)async list(@Req()r:ApiRequest,@Query(new DtoValidationPipe(ApplicationListQueryDto))q:ApplicationListQueryDto){return this.response(r,await this.service.list(r.user!,q));}
@Get("mine")@RequireRoles("APPLIER")async mine(@Req()r:ApiRequest,@Query(new DtoValidationPipe(MyApplicationQueryDto))q:MyApplicationQueryDto){return this.response(r,await this.service.mine(r.user!,q));}
@Get("counts")@RequireRoles(...ALL)async counts(@Req()r:ApiRequest){return this.response(r,await this.service.counts(r.user!));}
@Get("appliers")@RequireRoles(...ALL)async appliers(@Req()r:ApiRequest,@Query(new DtoValidationPipe(SearchOptionsQueryDto))q:SearchOptionsQueryDto){return this.response(r,await this.service.appliers(r.user!,q.search));}
@Get("options/jobs")@RequireRoles(...MANAGERS)async jobs(@Req()r:ApiRequest,@Query(new DtoValidationPipe(SearchOptionsQueryDto))q:SearchOptionsQueryDto){return this.response(r,await this.service.jobs(r.user!,q.search));}
@Get("options/resumes")@RequireRoles(...MANAGERS)async resumes(@Req()r:ApiRequest,@Query(new DtoValidationPipe(ResumeOptionsQueryDto))q:ResumeOptionsQueryDto){return this.response(r,await this.service.resumes(r.user!,q.jobDescriptionId,q.search));}
@Post()@RequireRoles(...MANAGERS)async create(@Req()r:ApiRequest,@Body(new DtoValidationPipe(CreateApplicationDto))body:CreateApplicationDto){return this.response(r,await this.service.create(r.user!,body));}
@Post("bulk-assignment")@RequireRoles(...MANAGERS)async bulkAssign(@Req()r:ApiRequest,@Body(new DtoValidationPipe(BulkAssignApplicationDto))body:BulkAssignApplicationDto){return this.response(r,await this.service.bulkAssign(r.user!,body));}
@Get(":id/resume-file-url")@RequireRoles(...ALL)async resumeUrl(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.resumeUrl(r.user!,id));}
@Get(":id/screenshots")@RequireRoles(...ALL)async screenshots(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.screenshots(r.user!,id));}
@Post(":id/screenshots")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")@UseInterceptors(FileInterceptor("file",{limits:{fileSize:5242880,files:1}}))async addScreenshot(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@UploadedFile()file:any){return this.response(r,await this.service.addScreenshot(r.user!,id,file));}
@Delete(":id/screenshots/:screenshotId")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")async removeScreenshot(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("screenshotId",new ParseUUIDPipe({version:"4"}))screenshotId:string){return this.response(r,await this.service.removeScreenshot(r.user!,id,screenshotId));}
@Get(":id/screenshots/:screenshotId/file-url")@RequireRoles(...ALL)async screenshotUrl(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("screenshotId",new ParseUUIDPipe({version:"4"}))screenshotId:string){return this.response(r,await this.service.screenshotUrl(r.user!,id,screenshotId));}
@Patch(":id/progress")@RequireRoles("APPLIER","APPLYING_MANAGER","ADMIN")async update(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(UpdateApplicationDto))body:UpdateApplicationDto){return this.response(r,await this.service.update(r.user!,id,body));}
@Patch(":id/assignment")@RequireRoles(...MANAGERS)async assign(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ReassignApplicationDto))body:ReassignApplicationDto){return this.response(r,await this.service.assign(r.user!,id,body));}
@Get(":id")@RequireRoles(...ALL)async detail(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return this.response(r,await this.service.detail(r.user!,id));}}
