import React,{useCallback,useEffect,useRef,useState} from "react";
import {parseRoute} from "./router.js";
import {getSession,signIn,signOut} from "./services/auth-service.js";
import {categoryName,loadCategories} from "./services/category-service.js";
import {getJob,jobCount,listJobs,recentJobs} from "./services/job-read-service.js";
import {getResume,listResumes,recentResumes,resumeCount} from "./services/resume-read-service.js";
import {createResumeSignedUrl} from "./services/storage-read-service.js";
import {getMyAccessContext,listSystemRoles} from "./services/access-service.js";
import {CAPABILITIES,hasCapability} from "./access/capabilities.js";
import {guardAccessRoute,navigationForAccess} from "./access/route-access.js";
import {formatBytes,formatDate,formatLabel,formatMime,cleanTags} from "./shared/formatters.js";
import {parseJobQuery,parseResumeQuery,serializeQuery} from "./shared/query-state.js";
import {normalizeSearch,validateLogin} from "./shared/validation.js";
import {safeExternalUrl} from "./shared/url.js";
import {MIME_TYPES,PAGE_SIZES,SENIORITIES,STATUSES} from "./shared/constants.js";
import {AccessDeniedPage,AccessLoadErrorPage,InactiveAccountPage,PendingAccessPage,ProfilePage,TechnicalOverview} from "./pages/access-pages.jsx";
import {AdminRolesPage,AdminUserDetailPage,AdminUsersPage} from "./pages/admin-pages.jsx";

const go=(hash,replace=false)=>replace?location.replace(hash):location.assign(hash);
const Loading=({text="Loading…"})=><div className="state loading" role="status"><span className="spinner" aria-hidden="true"/>{text}</div>;
const ErrorState=({message,retry})=><section className="state error" role="alert"><h2>Something went wrong</h2><p>{message}</p>{retry&&<button onClick={retry}>Retry</button>}</section>;
const Badge=({value})=><span className={`badge badge-${String(value||"").toLowerCase()}`}>{formatLabel(value)}</span>;
const Tags=({values,empty})=>{const tags=cleanTags(values);return tags.length?<div className="tags">{tags.map(value=><span className="tag" key={value}>{value}</span>)}</div>:<p className="muted">{empty}</p>;};
const Meta=({items})=><dl className="metadata">{items.map(([term,value])=><div key={term}><dt>{term}</dt><dd>{value??"Not available"}</dd></div>)}</dl>;
const capturedBy=job=>job?.captured_by?.display_name?.trim()||job?.captured_by?.email||job?.user_id||"Unknown user";
const salaryRange=job=>{if(job?.salary_min==null&&job?.salary_max==null)return job?.salary_text||"Not specified";const currency=job.salary_currency||"",amount=value=>value==null?"":new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(Number(value)),range=job.salary_min===job.salary_max?amount(job.salary_min):`${amount(job.salary_min)} – ${amount(job.salary_max)}`;return `${currency} ${range}${job.salary_period?` per ${formatLabel(job.salary_period).toLowerCase()}`:""}`.trim();};
const Table=({headers,children})=><div className="table-scroll"><table><thead><tr>{headers.map(value=><th scope="col" key={value}>{value}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
const Empty=({title,text,onClear})=><section className="state empty"><h2>{title}</h2><p>{text}</p>{onClear&&<button onClick={onClear}>Clear filters</button>}</section>;

function Pagination({data,onPage}){return <nav className="pagination" aria-label="Pagination"><p>Showing {data.from}–{data.to} of {data.total}</p><div><button disabled={!data.hasPrevious} onClick={()=>onPage(data.page-1)}>Previous</button><span>Page {data.page} of {data.pageCount||1}</span><button disabled={!data.hasNext} onClick={()=>onPage(data.page+1)}>Next</button></div></nav>;}

function Shell({route,title,access,refresh,logout,children}){const items=access?.status==="ACTIVE"&&access.roles?.length?navigationForAccess(access):[];return <div className="app-shell"><nav className="sidebar" aria-label="Primary"><div className="brand">Resume JD Operations</div>{items.map(({name,label,href})=><a key={name} href={href} className={route.name===name||route.name.startsWith(`${name}-`)?"active":""}>{label}</a>)}</nav><div className="workspace"><header className="topbar"><div><p className="eyebrow">v0.5 · Role-aware dashboard</p><p className="top-title">{title}</p></div><div className="top-actions">{refresh&&<button className="secondary" onClick={refresh}>Refresh</button>}<span className="user-email">{access?.email}</span><button className="secondary" onClick={logout}>Sign Out</button></div></header><main id="main-content" tabIndex="-1">{children}</main></div></div>;}

function Login({client,onSignedIn}){const [message,setMessage]=useState(""),[busy,setBusy]=useState(false);async function submit(event){event.preventDefault();const form=new FormData(event.currentTarget),email=form.get("email"),password=form.get("password"),check=validateLogin(email,password);if(!check.valid){setMessage(Object.values(check.errors).join(" "));return;}setBusy(true);try{onSignedIn(await signIn(client,email,password));}catch(error){setMessage(error.message);}finally{setBusy(false);}}return <main className="login-page"><section className="login-card"><p className="eyebrow">Resume JD Operations</p><h1 tabIndex="-1">Sign in</h1><p>Use the same Supabase email and password as the Chrome extension.</p><form className="login-form" onSubmit={submit}><label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="username" required/><label htmlFor="password">Password</label><input id="password" name="password" type="password" autoComplete="current-password" required/><div className="form-message" aria-live="polite">{message}</div><button disabled={busy}>{busy?"Signing in…":"Sign In"}</button></form></section></main>;}

function FilterForm({kind,value,categories,onApply,onClear}){function submit(event){event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget));try{onApply({...raw,search:normalizeSearch(raw.search),page:1,pageSize:Number(raw.pageSize)});}catch(error){window.alert(error.message);}}const sorts=kind==="jobs"?[["created_desc","Captured — Newest"],["created_asc","Captured — Oldest"],["company_asc","Company — A to Z"],["title_asc","Job title — A to Z"]]:[["updated_desc","Updated — Newest"],["updated_asc","Updated — Oldest"],["candidate_asc","Candidate — A to Z"],["name_asc","Resume name — A to Z"]];return <form className="filters" onSubmit={submit}><label>Search {kind==="jobs"?"company or job title":"candidate or resume name"}<input name="search" type="search" maxLength="100" defaultValue={value.search}/></label><label>Primary category<select name="categoryId" defaultValue={value.categoryId}><option value="">All categories</option>{categories.primary.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Seniority<select name="seniority" defaultValue={value.seniority}><option value="">All seniority</option>{SENIORITIES.map(item=><option key={item}>{formatLabel(item)}</option>)}</select></label><label>Status<select name="status" defaultValue={value.status}><option value="">All statuses</option>{STATUSES.map(item=><option key={item}>{formatLabel(item)}</option>)}</select></label>{kind==="resumes"&&<label>File type<select name="mimeType" defaultValue={value.mimeType}><option value="">All file types</option>{MIME_TYPES.map(item=><option value={item} key={item}>{formatMime(item)}</option>)}</select></label>}<label>Sort<select name="sort" defaultValue={value.sort}>{sorts.map(([option,label])=><option value={option} key={option}>{label}</option>)}</select></label><label>Page size<select name="pageSize" defaultValue={value.pageSize}>{PAGE_SIZES.map(item=><option key={item}>{item}</option>)}</select></label><div className="filter-actions"><button>Apply</button><button type="button" className="secondary" onClick={onClear}>Clear filters</button></div></form>;}

function BusinessOverview({client,categories,reload}){const [result,setResult]=useState(null),[error,setError]=useState("");useEffect(()=>{let live=true;Promise.all([jobCount(client),jobCount(client,"ACTIVE"),resumeCount(client),resumeCount(client,"ACTIVE"),recentJobs(client),recentResumes(client)]).then(value=>live&&setResult(value)).catch(value=>live&&setError(value.message));return()=>{live=false};},[client,reload]);if(error)return <ErrorState message={error}/>;if(!result)return <Loading text="Loading dashboard…"/>;const [jobs,activeJobs,resumes,activeResumes,recentJ,recentR]=result;return <div className="page"><h1 tabIndex="-1">Overview</h1><section className="summary-grid" aria-label="Summary">{[["Total Job Descriptions",jobs],["Active Job Descriptions",activeJobs],["Total Resumes",resumes],["Active Resumes",activeResumes]].map(([label,count])=><article className="summary-card" key={label}><p>{label}</p><strong>{count}</strong></article>)}</section><section className="panel"><div className="section-heading"><h2>Recent job descriptions</h2><a href="#/jobs">View all</a></div>{recentJ.length?<Table headers={["Company","Job title","Category","Captured by","Status","Captured"]}>{recentJ.map(job=><tr key={job.id}><td>{job.company}</td><td><a href={`#/jobs/${job.id}`}>{job.job_title}</a></td><td>{categoryName(categories,job.category_id)}</td><td>{capturedBy(job)}</td><td><Badge value={job.status}/></td><td>{formatDate(job.created_at)}</td></tr>)}</Table>:<p className="muted">No job descriptions have been captured yet.</p>}</section><section className="panel"><div className="section-heading"><h2>Recent resumes</h2><a href="#/resumes">View all</a></div>{recentR.length?<Table headers={["Candidate","Resume","Category","Status","Updated"]}>{recentR.map(resume=><tr key={resume.id}><td>{resume.candidate_name}</td><td><a href={`#/resumes/${resume.id}`}>{resume.resume_name}</a></td><td>{categoryName(categories,resume.primary_category_id)}</td><td><Badge value={resume.status}/></td><td>{formatDate(resume.updated_at)}</td></tr>)}</Table>:<p className="muted">No resumes have been uploaded yet.</p>}</section></div>;}

function Jobs({client,categories,query,reload}){const filters=parseJobQuery(query),[data,setData]=useState(null),[error,setError]=useState("");useEffect(()=>{let live=true;setData(null);setError("");listJobs(client,filters).then(value=>live&&setData(value)).catch(value=>live&&setError(value.message));return()=>{live=false};},[client,query,reload]);const update=patch=>{const value=serializeQuery({...filters,...patch});go(`#/jobs${value?`?${value}`:""}`);};return <div className="page"><h1 tabIndex="-1">Job Descriptions</h1><FilterForm kind="jobs" value={filters} categories={categories} onApply={update} onClear={()=>go("#/jobs")}/>{error?<ErrorState message={error}/>:!data?<Loading text="Loading job descriptions…"/>:!data.items.length?<Empty title="No job descriptions" text="No job descriptions match the current view." onClear={()=>go("#/jobs")}/>:<section className="panel"><Table headers={["Company","Job title","Primary category","Subcategory","Seniority","Source site","Captured by","Status","Captured",""]}>{data.items.map(job=><tr key={job.id}><td>{job.company}</td><td>{job.job_title}</td><td>{categoryName(categories,job.category_id)}</td><td>{job.subcategory_id?categoryName(categories,job.subcategory_id):"None"}</td><td>{formatLabel(job.seniority)}</td><td>{job.source_site||"—"}</td><td>{capturedBy(job)}</td><td><Badge value={job.status}/></td><td>{formatDate(job.created_at)}</td><td><a href={`#/jobs/${job.id}`}>View</a></td></tr>)}</Table><Pagination data={data} onPage={page=>update({page})}/></section>}</div>;}

function Resumes({client,categories,query,reload}){const filters=parseResumeQuery(query),[data,setData]=useState(null),[error,setError]=useState("");useEffect(()=>{let live=true;setData(null);setError("");listResumes(client,filters).then(value=>live&&setData(value)).catch(value=>live&&setError(value.message));return()=>{live=false};},[client,query,reload]);const update=patch=>{const value=serializeQuery({...filters,...patch});go(`#/resumes${value?`?${value}`:""}`);};return <div className="page"><h1 tabIndex="-1">Resumes</h1><FilterForm kind="resumes" value={filters} categories={categories} onApply={update} onClear={()=>go("#/resumes")}/>{error?<ErrorState message={error}/>:!data?<Loading text="Loading resumes…"/>:!data.items.length?<Empty title="No resumes" text="No resumes match the current view. Resumes are uploaded through the extension." onClear={()=>go("#/resumes")}/>:<section className="panel"><Table headers={["Candidate","Resume","Primary category","Subcategory","Seniority","Status","File type","Updated",""]}>{data.items.map(resume=><tr key={resume.id}><td>{resume.candidate_name}</td><td>{resume.resume_name}</td><td>{categoryName(categories,resume.primary_category_id)}</td><td>{resume.subcategory_id?categoryName(categories,resume.subcategory_id):"None"}</td><td>{formatLabel(resume.seniority)}</td><td><Badge value={resume.status}/></td><td>{formatMime(resume.mime_type)}</td><td>{formatDate(resume.updated_at)}</td><td><a href={`#/resumes/${resume.id}`}>View</a></td></tr>)}</Table><Pagination data={data} onPage={page=>update({page})}/></section>}</div>;}

function JobDetail({client,categories,id,back,reload}){const [job,setJob]=useState(),[error,setError]=useState("");useEffect(()=>{getJob(client,id).then(setJob).catch(value=>setError(value.message));},[client,id,reload]);if(error)return <ErrorState message={error}/>;if(job===undefined)return <Loading/>;if(!job)return <ErrorState message="Job description not found or you do not have access to it."/>;const source=safeExternalUrl(job.source_url);return <div className="page"><a className="back-link" href={back}>← Back to Job Descriptions</a><div className="detail-title"><div><p className="eyebrow">{job.company}</p><h1 tabIndex="-1">{job.job_title}</h1></div><Badge value={job.status}/></div><section className="panel"><h2>Details</h2><Meta items={[["Primary category",categoryName(categories,job.category_id)],["Subcategory",job.subcategory_id?categoryName(categories,job.subcategory_id):"None"],["Industry domain",formatLabel(job.industry_domain)],["Seniority",formatLabel(job.seniority)],["Location",job.location_text||"Not specified / remote"],["Work arrangement",formatLabel(job.work_arrangement)],["Salary range",salaryRange(job)],["Original salary text",job.salary_text||"—"],["Travel required",job.travel_required===null?"Not specified":job.travel_required?"Yes":"No"],["Travel details",job.travel_details||"—"],["Source site",job.source_site],["Captured by",capturedBy(job)],["Capturer user ID",job.user_id],["Capture method",formatLabel(job.capture_method)],["Extraction confidence",formatLabel(job.extraction_confidence)],["Captured at",formatDate(job.created_at)],["Last updated",formatDate(job.updated_at)]]}/>{source&&<a className="button-link" href={source} target="_blank" rel="noopener noreferrer">Open Original Job Posting (new tab)</a>}</section><section className="panel"><h2>Security requirements</h2><Tags values={job.clearance_requirements?.map(formatLabel)} empty="No clearance requirement detected"/></section><section className="panel"><h2>Detected technology stack</h2><Tags values={job.detected_skills} empty="No technology stack detected"/></section><section className="panel"><h2>Job description</h2><div className="long-text">{job.description_text}</div></section></div>;}

function ResumeDetail({client,categories,id,back,reload}){const [resume,setResume]=useState(),[error,setError]=useState(""),[fileMessage,setFileMessage]=useState("");useEffect(()=>{getResume(client,id).then(setResume).catch(value=>setError(value.message));},[client,id,reload]);if(error)return <ErrorState message={error}/>;if(resume===undefined)return <Loading/>;if(!resume)return <ErrorState message="Resume not found or you do not have access to it."/>;async function open(){setFileMessage("Generating a secure link…");try{const url=await createResumeSignedUrl(client,{bucket:resume.storage_bucket,path:resume.storage_path});window.open(url,"_blank","noopener,noreferrer");setFileMessage("Secure link opened. It expires shortly.");}catch(value){setFileMessage(value.message);}}const structured=resume.structured_content||{};return <div className="page"><a className="back-link" href={back}>← Back to Resumes</a><div className="detail-title"><div><p className="eyebrow">{resume.candidate_name}</p><h1 tabIndex="-1">{resume.resume_name}</h1></div><Badge value={resume.status}/></div><section className="panel"><h2>Details</h2><Meta items={[["Primary category",categoryName(categories,resume.primary_category_id)],["Subcategory",resume.subcategory_id?categoryName(categories,resume.subcategory_id):"None"],["Seniority",formatLabel(resume.seniority)],["Structured schema version",resume.structured_schema_version||"Legacy"],["Original filename",resume.original_filename],["File type",formatMime(resume.mime_type)],["File size",formatBytes(resume.file_size_bytes)],["Created at",formatDate(resume.created_at)],["Last updated",formatDate(resume.updated_at)]]}/><button onClick={open}>Open Original Resume (new tab)</button><p className="form-message neutral" aria-live="polite">{fileMessage}</p></section><section className="panel"><h2>Skills</h2><Tags values={resume.skills} empty="No skills recorded"/></section><section className="panel"><h2>Industries</h2><Tags values={resume.industries} empty="No industries recorded"/></section><section className="panel"><h2>Structured resume</h2>{[["Summary",structured.summary],["Professional Experience",structured.professional_experience],["Education",structured.education],["Skills Section",structured.skills]].map(([heading,value])=>value?<details key={heading} open><summary>{heading}</summary><div className="long-text">{value}</div></details>:null)}</section><details className="panel"><summary>Original extracted resume text</summary><div className="long-text">{resume.resume_text}</div></details></div>;}

export function ConfigurationError({message}){return <main className="config-page"><section className="login-card" role="alert"><h1>Dashboard setup required</h1><p>{message}</p><p>Create dashboard/.env.local from dashboard/.env.example, then restart or rebuild.</p></section></main>;}

export function App({client}) {
  const [session,setSession]=useState(undefined),[access,setAccess]=useState(undefined),[accessError,setAccessError]=useState(null),[route,setRoute]=useState(()=>parseRoute(location.hash||"#/")),[categories,setCategories]=useState(null),[roles,setRoles]=useState([]),[reload,setReload]=useState(0),jobsBack=useRef("#/jobs"),resumesBack=useRef("#/resumes");
  const reloadAccess=useCallback(async()=>{if(!session)return;setAccessError(null);try{const next=await getMyAccessContext(client);setAccess(next);return next;}catch(error){setAccess(null);setAccessError(error);}},[client,session]);
  useEffect(()=>{getSession(client).then(setSession).catch(()=>setSession(null));const {data}=client.auth.onAuthStateChange((_event,next)=>{setSession(next);setAccess(undefined);setAccessError(null);});const hash=()=>setRoute(parseRoute(location.hash));addEventListener("hashchange",hash);if(!location.hash)location.hash="#/";return()=>{data.subscription.unsubscribe();removeEventListener("hashchange",hash);};},[client]);
  useEffect(()=>{if(session)reloadAccess();else{setAccess(undefined);setCategories(null);setRoles([]);}},[session,reloadAccess]);
  useEffect(()=>{let live=true;if(access&&hasCapability(access,CAPABILITIES.BUSINESS_DATA_READ)&&!categories)loadCategories(client).then(value=>live&&setCategories(value)).catch(setAccessError);if(access&&!hasCapability(access,CAPABILITIES.BUSINESS_DATA_READ))setCategories(null);if(access&&hasCapability(access,CAPABILITIES.USER_ADMIN))listSystemRoles(client).then(value=>live&&setRoles(value)).catch(setAccessError);else setRoles([]);return()=>{live=false};},[access,client,categories]);
  useEffect(()=>{if(session!==undefined&&(!session||access)){const redirect=guardAccessRoute(route,session,access);if(redirect)go(redirect,true);}document.title=`${route.name==="overview"?"Overview":formatLabel(route.name)} — Resume JD Operations`;queueMicrotask(()=>document.querySelector("h1")?.focus());},[route,session,access]);
  if(session===undefined)return <Loading text="Restoring session…"/>;
  if(!session)return <Login client={client} onSignedIn={next=>{setSession(next);go("#/",true);}}/>;
  const logout=async()=>{await signOut(client);setSession(null);setAccess(undefined);setCategories(null);setRoles([]);go("#/login",true);};
  if(accessError)return <Shell route={route} title="Access error" access={{email:session.user.email,status:"INACTIVE",roles:[]}} logout={logout}><AccessLoadErrorPage error={accessError} retry={reloadAccess}/></Shell>;
  if(access===undefined)return <Loading text="Loading account access…"/>;
  const guarded=guardAccessRoute(route,session,access);
  if(guarded==="#/pending-access")return <Shell route={route} title="Pending Access" access={access} logout={logout}><PendingAccessPage/></Shell>;
  if(guarded==="#/account-inactive")return <Shell route={route} title="Account Inactive" access={access} logout={logout}><InactiveAccountPage/></Shell>;
  if(guarded==="#/access-denied")return <Shell route={route} title="Access Denied" access={access} logout={logout}><AccessDeniedPage/></Shell>;
  const needsCategories=hasCapability(access,CAPABILITIES.BUSINESS_DATA_READ)&&["overview","jobs","job-detail","resumes","resume-detail"].includes(route.name);
  if(needsCategories&&!categories)return <Loading text="Loading categories…"/>;
  if(hasCapability(access,CAPABILITIES.USER_ADMIN)&&["admin-users","admin-user-detail","admin-roles"].includes(route.name)&&!roles.length)return <Loading text="Loading system roles…"/>;
  if(route.name==="jobs")jobsBack.current=location.hash;if(route.name==="resumes")resumesBack.current=location.hash;
  let page;
  if(route.name==="pending-access")page=<PendingAccessPage/>;
  else if(route.name==="account-inactive")page=<InactiveAccountPage/>;
  else if(route.name==="access-denied")page=<AccessDeniedPage/>;
  else if(route.name==="profile")page=<ProfilePage client={client} access={access} reloadAccess={reloadAccess}/>;
  else if(route.name==="overview")page=hasCapability(access,CAPABILITIES.BUSINESS_DATA_READ)?<BusinessOverview client={client} categories={categories} reload={reload}/>:<TechnicalOverview access={access}/>;
  else if(route.name==="jobs")page=<Jobs client={client} categories={categories} query={route.query} reload={reload}/>;
  else if(route.name==="job-detail")page=<JobDetail client={client} categories={categories} id={route.id} back={jobsBack.current} reload={reload}/>;
  else if(route.name==="resumes")page=<Resumes client={client} categories={categories} query={route.query} reload={reload}/>;
  else if(route.name==="resume-detail")page=<ResumeDetail client={client} categories={categories} id={route.id} back={resumesBack.current} reload={reload}/>;
  else if(route.name==="admin-users")page=<AdminUsersPage client={client} roles={roles} reload={reload}/>;
  else if(route.name==="admin-user-detail")page=<AdminUserDetailPage client={client} id={route.id} roles={roles} currentUserId={access.userId} onCurrentUserChanged={reloadAccess}/>;
  else if(route.name==="admin-roles")page=<AdminRolesPage roles={roles}/>;
  else page=<div className="page"><h1 tabIndex="-1">Page not found</h1><p>{route.name==="invalid-id"?"The record identifier is invalid.":"The requested page does not exist."}</p><a href="#/">Return to Overview</a></div>;
  return <Shell route={route} title={formatLabel(route.name)} access={access} refresh={()=>setReload(value=>value+1)} logout={logout}>{page}</Shell>;
}
