import { MESSAGE_TYPES,USER_MESSAGES } from "../shared/messages.js";
import { extractJobFromPage,selectBestFrameExtraction } from "../shared/extraction.js";
import { normalizeUrl,hostnameFromUrl } from "../shared/normalization.js";
chrome.runtime.onInstalled.addListener(()=>chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true}).catch(()=>{}));
const fail=(code,message,details="")=>({ok:false,error:{code,message,details}});
const activeTab=async()=> (await chrome.tabs.query({active:true,lastFocusedWindow:true}))[0];
const restricted=(url="")=>/^(chrome|edge|about|chrome-extension):/.test(url)||/^https:\/\/chromewebstore\.google\.com\//.test(url);
async function ensureOrigin(tab){if(!tab?.url)return false;return chrome.permissions.contains({origins:[`${new URL(tab.url).origin}/*`]});}
async function extract(selected){const tab=await activeTab();if(!tab?.id||restricted(tab.url))return fail("UNSUPPORTED_PAGE",USER_MESSAGES.UNSUPPORTED_PAGE);try{if(!await ensureOrigin(tab))return fail("EXTRACTION_PERMISSION_DENIED","Chrome site access is disabled. Open the extension's Site access setting and select On all sites.");const frames=await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},func:extractJobFromPage,args:[selected]}),best=selectBestFrameExtraction(frames);if(!best){if(selected&&frames.some(({result})=>result?.error?.code==="SELECTION_EMPTY"))return fail("SELECTION_EMPTY",USER_MESSAGES.SELECTION_EMPTY);return fail("EXTRACTION_FAILED","No usable job description was found. Select the description or enter it manually.");}const result=best.result;result.sourceUrl=normalizeUrl(best.frameId===0?result.sourceUrl:tab.url)||tab.url;result.sourceSite=hostnameFromUrl(result.sourceUrl);return {ok:true,data:result};}catch(error){return fail("EXTRACTION_FAILED","The current page could not be extracted.",String(error?.message||"").slice(0,180));}}
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{(async()=>{if(message?.type===MESSAGE_TYPES.EXTRACT_CURRENT_JOB)return extract(false);if(message?.type===MESSAGE_TYPES.EXTRACT_SELECTED_TEXT)return extract(true);if(message?.type===MESSAGE_TYPES.GET_ACTIVE_TAB){const tab=await activeTab();return {ok:true,data:{url:normalizeUrl(tab?.url)||"",restricted:restricted(tab?.url)}};}return fail("UNKNOWN_MESSAGE","Unsupported extension request.");})().then(sendResponse).catch(()=>sendResponse(fail("UNEXPECTED_ERROR","The request could not be completed.")));return true;});
