import { MESSAGE_TYPES,USER_MESSAGES } from "../shared/messages.js";
import { extractJobFromPage,selectBestFrameExtraction } from "../shared/extraction.js";
import { normalizeUrl,hostnameFromUrl } from "../shared/normalization.js";
chrome.runtime.onInstalled.addListener(()=>chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true}).catch(()=>{}));
const fail=(code,message,details="")=>({ok:false,error:{code,message,details}});
const activeTab=async()=> (await chrome.tabs.query({active:true,lastFocusedWindow:true}))[0];
const restricted=(url="")=>/^(chrome|edge|about|chrome-extension):/.test(url)||/^https:\/\/chromewebstore\.google\.com\//.test(url);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,ACTIONS=new Set(["LOAD_RESUME","AUTOFILL"]),SESSION_KEY="activeApplicationSession";
async function dashboardOriginAllowed(sender){try{const senderOrigin=new URL(sender?.tab?.url||"").origin,{backendConfig}=await chrome.storage.local.get("backendConfig"),configured=new URL(backendConfig?.baseUrl||"").origin;return senderOrigin===configured||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(senderOrigin);}catch{return false;}}
async function targetTab(url){const normalized=normalizeUrl(url);if(!normalized||!/^https?:\/\//.test(normalized))throw new Error("The Application job URL is invalid.");const tabs=await chrome.tabs.query({});let tab=tabs.find(item=>normalizeUrl(item.url)===normalized);if(tab?.id){await chrome.tabs.update(tab.id,{active:true});if(tab.windowId!=null)await chrome.windows.update(tab.windowId,{focused:true});}else tab=await chrome.tabs.create({url:normalized,active:true});return tab;}
async function handoffSession(payload,sender){const internal=sender?.id===chrome.runtime.id&&!sender?.tab;if(!internal&&!await dashboardOriginAllowed(sender))return fail("DASHBOARD_ORIGIN_DENIED","The Application handoff did not come from the configured dashboard.");const expires=Date.parse(payload?.expiresAt||"");if(!UUID.test(payload?.id||"")||!UUID.test(payload?.applicationId||"")||!ACTIONS.has(payload?.action)||!Number.isFinite(expires)||expires<=Date.now()||expires>Date.now()+20*60*1000)return fail("APPLICATION_SESSION_INVALID","The Application handoff is invalid or expired.");try{const tab=await targetTab(payload.targetUrl),session={id:payload.id,applicationId:payload.applicationId,action:payload.action,targetUrl:normalizeUrl(payload.targetUrl),targetTabId:tab.id,expiresAt:payload.expiresAt};await chrome.storage.session.set({[SESSION_KEY]:session});return{ok:true,data:{sessionId:session.id,applicationId:session.applicationId,targetTabId:session.targetTabId}};}catch{return fail("APPLICATION_TARGET_FAILED","The job page could not be opened or focused.");}}
async function currentApplicationSession(){const stored=(await chrome.storage.session.get(SESSION_KEY))[SESSION_KEY];if(!stored)return null;if(Date.parse(stored.expiresAt)<=Date.now()){await chrome.storage.session.remove(SESSION_KEY);return null;}return stored;}
async function ensureOrigin(tab){if(!tab?.url)return false;return chrome.permissions.contains({origins:[`${new URL(tab.url).origin}/*`]});}
async function extract(selected){const tab=await activeTab();if(!tab?.id||restricted(tab.url))return fail("UNSUPPORTED_PAGE",USER_MESSAGES.UNSUPPORTED_PAGE);try{if(!await ensureOrigin(tab))return fail("EXTRACTION_PERMISSION_DENIED","Chrome site access is disabled. Open the extension's Site access setting and select On all sites.");const frames=await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},func:extractJobFromPage,args:[selected]}),best=selectBestFrameExtraction(frames);if(!best){if(selected&&frames.some(({result})=>result?.error?.code==="SELECTION_EMPTY"))return fail("SELECTION_EMPTY",USER_MESSAGES.SELECTION_EMPTY);return fail("EXTRACTION_FAILED","No usable job description was found. Select the description or enter it manually.");}const result=best.result;result.sourceUrl=normalizeUrl(best.frameId===0?result.sourceUrl:tab.url)||tab.url;result.sourceSite=hostnameFromUrl(result.sourceUrl);return {ok:true,data:result};}catch(error){return fail("EXTRACTION_FAILED","The current page could not be extracted.",String(error?.message||"").slice(0,180));}}
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{(async()=>{if(message?.type===MESSAGE_TYPES.EXTRACT_CURRENT_JOB)return extract(false);if(message?.type===MESSAGE_TYPES.EXTRACT_SELECTED_TEXT)return extract(true);if(message?.type===MESSAGE_TYPES.GET_ACTIVE_TAB){const tab=await activeTab();return {ok:true,data:{url:normalizeUrl(tab?.url)||"",restricted:restricted(tab?.url)}};}if(message?.type===MESSAGE_TYPES.HANDOFF_APPLICATION_SESSION)return handoffSession(message.payload,sender);if(message?.type===MESSAGE_TYPES.GET_ACTIVE_APPLICATION_SESSION)return{ok:true,data:await currentApplicationSession()};if(message?.type===MESSAGE_TYPES.RESET_ACTIVE_APPLICATION_SESSION){await chrome.storage.session.remove(SESSION_KEY);return{ok:true,data:null};}return fail("UNKNOWN_MESSAGE","Unsupported extension request.");})().then(sendResponse).catch(()=>sendResponse(fail("UNEXPECTED_ERROR","The request could not be completed.")));return true;});
