import {authenticatedApiRequest} from "../../services/api-client.js";
import {validateApplicationCreate,validateApplicationProgress} from "./validation.js";

const errorMessages={APPLICATION_DUPLICATE:"An Application already exists for this job description and resume.",APPLICATION_INVALID_ASSIGNEE:"Select an active user with the Applier role.",APPLICATION_INVALID_RESUME:"Select an active resume.",APPLICATION_ACCESS_DENIED:"You do not have permission to perform this action.",APPLICATION_NOT_FOUND:"The Application was not found or is no longer accessible.",APPLICATION_PROTECTED_FIELDS:"Appliers can change only the status fields and Confirmation URL.",APPLICATION_UNASSIGNED:"Assign an Applier before changing progress.",APPLICATION_INVALID_URL:"Enter a valid http or https Confirmation URL.",APPLIER_PROFILE_REQUIRED:"This Applier cannot receive Applications until at least one Resume profile is assigned.",APPLIER_RESUME_NOT_ALLOWED:"This Resume's original profile is not assigned to this Applier.",RESUME_PROFILE_MISSING:"This Resume and its original profile are not assigned to any Applier.",RESUME_PROFILE_TAKEN:"That Resume is already assigned to another active Applier."};
export function normalizeApplicationError(error,fallback="The Application request could not be completed."){const raw=String(error?.message||""),code=errorMessages[error?.code]?error.code:error?.code==="42501"?"APPLICATION_ACCESS_DENIED":Object.keys(errorMessages).find(value=>raw.toUpperCase().includes(value))||(error?.code||"APPLICATION_REQUEST_FAILED");return {code,message:errorMessages[code]||raw||fallback,retryable:error?.retryable||/fetch|network|timeout/i.test(raw)};}
async function api(client,baseUrl,path,{method="GET",body,timeoutMs}={}){try{const{payload}=await authenticatedApiRequest(client,{baseUrl,path,method,body,timeoutMs});return payload.data;}catch(error){throw normalizeApplicationError(error);}}
const query=(values)=>{const p=new URLSearchParams();for(const[key,value]of Object.entries(values))if(value!==undefined&&value!==null&&value!=="")p.set(key,String(value));const text=p.toString();return text?`?${text}`:"";};
export function listApplications(client,baseUrl,filters={}){return api(client,baseUrl,"/api/v1/applications"+query(filters));}
export const getApplication=(client,baseUrl,id)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}`);
export const getApplicationCounts=(client,baseUrl,dateRange)=>api(client,baseUrl,"/api/v1/applications/counts"+query(dateRange||{}));
export const getApplierProfileWorkload=(client,baseUrl,dateRange)=>api(client,baseUrl,"/api/v1/applications/profile-workload"+query(dateRange||{}));
export const getApplicationExtensionContext=(client,baseUrl,id)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/extension-context`);
export const createApplicationExtensionSession=(client,baseUrl,id,action)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/extension-sessions`,{method:"POST",body:{action}});
export const updateApplicationExtensionSession=(client,baseUrl,id,status,errorCode)=>api(client,baseUrl,`/api/v1/extension-sessions/${encodeURIComponent(id)}`,{method:"PATCH",body:{status,...(errorCode?{errorCode}:{})}});
export const listActiveAppliers=(client,baseUrl,search="")=>api(client,baseUrl,"/api/v1/applications/appliers"+query({search}));
export const listApplicationJobs=(client,baseUrl,search="")=>api(client,baseUrl,"/api/v1/applications/options/jobs"+query({search}));
export const listApplicationResumes=(client,baseUrl,jobDescriptionId,search="")=>api(client,baseUrl,"/api/v1/applications/options/resumes"+query({jobDescriptionId,search}));
export async function createApplication(client,baseUrl,value){const check=validateApplicationCreate(value);if(!check.valid)throw {code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};return api(client,baseUrl,"/api/v1/applications",{method:"POST",body:{...value,assignedTo:value.assignedTo||undefined,dueAt:value.dueAt||undefined,notes:value.notes||undefined}});}
export async function updateApplication(client,baseUrl,id,value){const check=validateApplicationProgress(value);if(!check.valid)throw {code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};return api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/progress`,{method:"PATCH",body:{...value,applicationUrl:value.applicationUrl||undefined,appliedAt:value.appliedAt||undefined,dueAt:value.dueAt||undefined}});}
export const reassignApplication=(client,baseUrl,id,newAssigneeId,reason)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/assignment`,{method:"PATCH",body:{newAssigneeId:newAssigneeId||undefined,reason:reason||undefined}});
export async function bulkCancelApplications(client,baseUrl,{applicationIds,notes}={}){const ids=[...new Set((applicationIds||[]).map((value)=>String(value||"").trim()).filter(Boolean))];if(!ids.length)throw{code:"VALIDATION_ERROR",message:"Select at least one Application."};return api(client,baseUrl,"/api/v1/applications/bulk-cancel",{method:"POST",body:{applicationIds:ids,...(notes!=null&&String(notes).trim()?{notes:String(notes).trim()}: {})}});}
export async function bulkDeleteApplications(client,baseUrl,{applicationIds}={}){const ids=[...new Set((applicationIds||[]).map((value)=>String(value||"").trim()).filter(Boolean))];if(!ids.length)throw{code:"VALIDATION_ERROR",message:"Select at least one Application."};return api(client,baseUrl,"/api/v1/applications/bulk-delete",{method:"POST",body:{applicationIds:ids}});}
export async function openApplicationResume(client,baseUrl,id){const data=await api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/resume-file-url`);return data.signedUrl;}
export const listApplicationScreenshots=(client,baseUrl,applicationId)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(applicationId)}/screenshots`);
const SCREENSHOT_MIME_TYPES=new Set(["image/png","image/jpeg","image/webp","application/pdf"]),SCREENSHOT_MIME_BY_EXT=Object.freeze({png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",webp:"image/webp",pdf:"application/pdf"}),MAX_SCREENSHOT_SIZE=5*1024*1024,SCREENSHOT_UPLOAD_TIMEOUT_MS=60000;
function inferScreenshotMime(file){if(file?.type&&SCREENSHOT_MIME_TYPES.has(file.type))return file.type;const ext=String(file?.name||"").split(".").pop()?.toLowerCase();return SCREENSHOT_MIME_BY_EXT[ext]||"";}
function screenshotUploadFile(file){const mime=inferScreenshotMime(file);if(!mime)return null;if(file?.type===mime)return file;return new File([file],file.name,{type:mime});}
export function validateApplicationScreenshotFile(file){const errors={};const mime=inferScreenshotMime(file);if(!file)errors.file="Choose a screenshot file.";else if(!mime)errors.file="Use a PNG, JPG, WEBP, or PDF file.";else if(!file.size||file.size>MAX_SCREENSHOT_SIZE)errors.file="Screenshot must be between 1 byte and 5 MiB.";return{valid:!Object.keys(errors).length,errors,mime};}
export async function attachApplicationScreenshot(client,baseUrl,applicationId,file){const check=validateApplicationScreenshotFile(file);if(!check.valid)throw{code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};const uploadFile=screenshotUploadFile(file);if(!uploadFile)throw{code:"VALIDATION_ERROR",message:"Use a PNG, JPG, WEBP, or PDF file."};const body=new FormData();body.append("file",uploadFile,uploadFile.name);return api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(applicationId)}/screenshots`,{method:"POST",body,timeoutMs:SCREENSHOT_UPLOAD_TIMEOUT_MS});}
export const removeApplicationScreenshot=(client,baseUrl,applicationId,screenshotId)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(applicationId)}/screenshots/${encodeURIComponent(screenshotId)}`,{method:"DELETE"});
export async function getApplicationScreenshotUrl(client,baseUrl,applicationId,screenshotId){return api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(applicationId)}/screenshots/${encodeURIComponent(screenshotId)}/file-url`);}
export async function openApplicationScreenshot(client,baseUrl,applicationId,screenshot){const data=await getApplicationScreenshotUrl(client,baseUrl,applicationId,screenshot.id);window.open(data.signedUrl,"_blank","noopener,noreferrer");}
export async function openFirstApplicationScreenshot(client,baseUrl,applicationId){const screenshots=await listApplicationScreenshots(client,baseUrl,applicationId);const screenshot=screenshots?.[0];if(!screenshot)throw{code:"APPLICATION_SCREENSHOT_NOT_FOUND",message:"No screenshot is attached."};return openApplicationScreenshot(client,baseUrl,applicationId,screenshot);}
