import {paginationMeta} from "../../shared/pagination.js";
import {createResumeSignedUrl} from "../../services/storage-read-service.js";
import {parseApplicationQuery} from "./query-state.js";
import {validateApplicationCreate,validateApplicationProgress} from "./validation.js";

const errorMessages={APPLICATION_DUPLICATE:"An Application already exists for this job description and resume.",APPLICATION_INVALID_ASSIGNEE:"Select an active user with the Applier role.",APPLICATION_INVALID_RESUME:"Select an active resume.",APPLICATION_ACCESS_DENIED:"You do not have permission to perform this action.",APPLICATION_NOT_FOUND:"The Application was not found or is no longer accessible.",APPLICATION_PROTECTED_FIELDS:"Appliers can change only the status fields and Application URL.",APPLICATION_UNASSIGNED:"Assign an Applier before changing progress.",APPLICATION_INVALID_URL:"Enter a valid http or https Application URL."};
export function normalizeApplicationError(error,fallback="The Application request could not be completed."){const raw=String(error?.message||"");const code=Object.keys(errorMessages).find(value=>raw.toUpperCase().includes(value))||(error?.code==="42501"?"APPLICATION_ACCESS_DENIED":"APPLICATION_REQUEST_FAILED");return {code,message:errorMessages[code]||fallback,retryable:/fetch|network/i.test(raw)};}
async function rpc(client,name,args,fallback){const {data,error}=await client.rpc(name,args);if(error)throw normalizeApplicationError(error,fallback);return data;}
export async function listApplications(client,input=""){const q=typeof input==="string"?parseApplicationQuery(input):input,page=Math.max(1,Number(q.page)||1),pageSize=[25,50,100].includes(Number(q.pageSize))?Number(q.pageSize):25,data=await rpc(client,"list_applications",{p_search:q.search||"",p_assigned_to:q.assignedTo||null,p_work_status:q.workStatus||"",p_application_status:q.applicationStatus||"",p_priority:q.priority||"",p_company:q.company||"",p_category_id:q.categoryId||null,p_due_filter:q.dueFilter||"",p_sort:q.sort||"updated_desc",p_limit:pageSize,p_offset:(page-1)*pageSize},"Unable to load Applications.");return {...data,...paginationMeta(data?.total,page,pageSize)};}
export const getApplication=(client,id)=>rpc(client,"get_application_detail",{p_application_id:id},"Unable to load the Application.");
export const getApplicationCounts=client=>rpc(client,"get_application_counts",{},"Unable to load Application counts.");
export const listActiveAppliers=(client,search="")=>rpc(client,"list_active_appliers",{p_search:search,p_limit:200},"Unable to load active Appliers.");
export const listApplicationJobs=(client,search="")=>rpc(client,"list_application_jobs",{p_search:search,p_limit:200},"Unable to load job descriptions.");
export const listApplicationResumes=(client,jobDescriptionId,search="")=>rpc(client,"list_application_resumes",{p_job_description_id:jobDescriptionId,p_search:search,p_limit:200},"Unable to load active resumes.");
export async function createApplication(client,value){const check=validateApplicationCreate(value);if(!check.valid)throw {code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};return rpc(client,"create_application",{p_job_description_id:value.jobDescriptionId,p_resume_id:value.resumeId,p_assigned_to:value.assignedTo||null,p_priority:value.priority,p_due_at:value.dueAt||null,p_notes:value.notes||null},"Unable to create the Application.");}
export async function updateApplication(client,id,value){const check=validateApplicationProgress(value);if(!check.valid)throw {code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};return rpc(client,"update_application_progress",{p_application_id:id,p_work_status:value.workStatus,p_application_status:value.applicationStatus,p_application_url:value.applicationUrl||null,p_applied_at:value.appliedAt||null,p_notes:value.notes||null,p_priority:value.priority??null,p_due_at:value.dueAt??null},"Unable to update the Application.");}
export const reassignApplication=(client,id,newAssigneeId,reason)=>rpc(client,"reassign_application",{p_application_id:id,p_new_assignee_id:newAssigneeId||null,p_reason:reason||null},"Unable to change the assignment.");
export async function openApplicationResume(client,id){const file=await rpc(client,"get_application_resume_file",{p_application_id:id},"Unable to access this Application's Resume.");return createResumeSignedUrl(client,file);}
