import {authenticatedApiRequest} from "../../services/api-client.js";
import {validateApplicationCreate,validateApplicationProgress} from "./validation.js";

const errorMessages={APPLICATION_DUPLICATE:"An Application already exists for this job description and resume.",APPLICATION_INVALID_ASSIGNEE:"Select an active user with the Applier role.",APPLICATION_INVALID_RESUME:"Select an active resume.",APPLICATION_ACCESS_DENIED:"You do not have permission to perform this action.",APPLICATION_NOT_FOUND:"The Application was not found or is no longer accessible.",APPLICATION_PROTECTED_FIELDS:"Appliers can change only the status fields and Application URL.",APPLICATION_UNASSIGNED:"Assign an Applier before changing progress.",APPLICATION_INVALID_URL:"Enter a valid http or https Application URL.",BULK_ASSIGN_NO_APPLICATIONS:"Select at least one Application.",BULK_ASSIGN_LIMIT:"You can assign up to 500 Applications at once.",BULK_ASSIGN_REASON_INVALID:"Assignment reason cannot exceed 2,000 characters."};
export function normalizeApplicationError(error,fallback="The Application request could not be completed."){const raw=String(error?.message||""),code=errorMessages[error?.code]?error.code:error?.code==="42501"?"APPLICATION_ACCESS_DENIED":Object.keys(errorMessages).find(value=>raw.toUpperCase().includes(value))||(error?.code||"APPLICATION_REQUEST_FAILED");return {code,message:errorMessages[code]||raw||fallback,retryable:error?.retryable||/fetch|network|timeout/i.test(raw)};}
async function api(client,baseUrl,path,{method="GET",body}={}){try{const{payload}=await authenticatedApiRequest(client,{baseUrl,path,method,body});return payload.data;}catch(error){throw normalizeApplicationError(error);}}
const query=(values)=>{const p=new URLSearchParams();for(const[key,value]of Object.entries(values))if(value!==undefined&&value!==null&&value!=="")p.set(key,String(value));const text=p.toString();return text?`?${text}`:"";};
export function listApplicationsCursor(client,baseUrl,filters={},cursor=null,pageSize=25){return api(client,baseUrl,"/api/v1/applications"+query({...filters,cursorUpdatedAt:cursor?.updatedAt,cursorId:cursor?.id,pageSize}));}
export const getApplication=(client,baseUrl,id)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}`);
export const getApplicationCounts=(client,baseUrl)=>api(client,baseUrl,"/api/v1/applications/counts");
export const listActiveAppliers=(client,baseUrl,search="")=>api(client,baseUrl,"/api/v1/applications/appliers"+query({search}));
export const listApplicationJobs=(client,baseUrl,search="")=>api(client,baseUrl,"/api/v1/applications/options/jobs"+query({search}));
export const listApplicationResumes=(client,baseUrl,jobDescriptionId,search="")=>api(client,baseUrl,"/api/v1/applications/options/resumes"+query({jobDescriptionId,search}));
export async function createApplication(client,baseUrl,value){const check=validateApplicationCreate(value);if(!check.valid)throw {code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};return api(client,baseUrl,"/api/v1/applications",{method:"POST",body:{...value,assignedTo:value.assignedTo||undefined,dueAt:value.dueAt||undefined,notes:value.notes||undefined}});}
export async function updateApplication(client,baseUrl,id,value){const check=validateApplicationProgress(value);if(!check.valid)throw {code:"VALIDATION_ERROR",message:Object.values(check.errors).join(" ")};return api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/progress`,{method:"PATCH",body:{...value,applicationUrl:value.applicationUrl||undefined,appliedAt:value.appliedAt||undefined,dueAt:value.dueAt||undefined}});}
export const reassignApplication=(client,baseUrl,id,newAssigneeId,reason)=>api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/assignment`,{method:"PATCH",body:{newAssigneeId:newAssigneeId||undefined,reason:reason||undefined}});
export function bulkAssignApplications(client,baseUrl,ids,newAssigneeId,reason){const applicationIds=[...new Set((ids||[]).filter(Boolean))],assignmentReason=String(reason||"").trim();if(!applicationIds.length)throw {code:"BULK_ASSIGN_NO_APPLICATIONS",message:errorMessages.BULK_ASSIGN_NO_APPLICATIONS};if(applicationIds.length>500)throw {code:"BULK_ASSIGN_LIMIT",message:errorMessages.BULK_ASSIGN_LIMIT};if(assignmentReason.length>2000)throw {code:"BULK_ASSIGN_REASON_INVALID",message:errorMessages.BULK_ASSIGN_REASON_INVALID};return api(client,baseUrl,"/api/v1/applications/bulk-assignment",{method:"POST",body:{applicationIds,newAssigneeId:newAssigneeId||undefined,reason:assignmentReason||undefined}});}
export async function openApplicationResume(client,baseUrl,id){const data=await api(client,baseUrl,`/api/v1/applications/${encodeURIComponent(id)}/resume-file-url`);return data.signedUrl;}
