export const APPLICATION_STATUSES = Object.freeze(["UNASSIGNED","ASSIGNED","IN_PROGRESS","BLOCKED","APPLIED","SCREENING","INTERVIEW_SCHEDULED","OFFER_RECEIVED","REJECTED","WITHDRAWN","CLOSED","CANCELLED"]);
export const APPLICATION_PRIORITIES = Object.freeze(["LOW","NORMAL","HIGH","URGENT"]);
export const DUE_FILTERS = Object.freeze([["OVERDUE","Overdue"],["DUE_TODAY","Due today"],["NO_DUE_DATE","No due date"]]);
