export const SKILLS = Object.freeze([
  ["Python",["python"]],["SQL",["sql"]],["Java",["java"]],["JavaScript",["javascript","js"]],["TypeScript",["typescript"]],["C#",["c#","c sharp"]],["C++",["c++"]],["Go",["golang","go"]],["R",["r"]],["Scala",["scala"]],["Kotlin",["kotlin"]],["Ruby",["ruby"]],["PHP",["php"]],["Rust",["rust"]],["Bash",["bash","shell scripting"]],["PowerShell",["powershell"]],
  ["Apache Spark",["apache spark","spark"]],["PySpark",["pyspark"]],["Databricks",["databricks"]],["Delta Lake",["delta lake"]],["Snowflake",["snowflake"]],["dbt",["dbt","data build tool"]],["Airflow",["apache airflow","airflow"]],["Dagster",["dagster"]],["Prefect",["prefect"]],["Kafka",["apache kafka","kafka"]],["Flink",["apache flink","flink"]],["Hadoop",["hadoop"]],["Hive",["apache hive","hive"]],["Trino",["trino","presto"]],["Iceberg",["apache iceberg","iceberg"]],["Fivetran",["fivetran"]],["Informatica",["informatica"]],["Talend",["talend"]],["Workato",["workato"]],["Azure Data Factory",["azure data factory","adf"]],["Azure Synapse",["azure synapse","synapse analytics"]],["Azure Data Lake",["azure data lake","adls"]],["AWS Glue",["aws glue"]],["Amazon S3",["amazon s3","s3"]],["Amazon EMR",["amazon emr","emr"]],["BigQuery",["bigquery"]],["Redshift",["amazon redshift","redshift"]],["Google Dataflow",["google dataflow","dataflow"]],["Microsoft Fabric",["microsoft fabric"]],
  ["PostgreSQL",["postgresql","postgres"]],["MySQL",["mysql"]],["SQL Server",["sql server","mssql"]],["Oracle",["oracle database","oracle"]],["MongoDB",["mongodb"]],["Redis",["redis"]],["DynamoDB",["dynamodb"]],["Cassandra",["cassandra"]],["Elasticsearch",["elasticsearch","elastic search"]],["OpenSearch",["opensearch"]],["Neo4j",["neo4j"]],["Teradata",["teradata"]],["ClickHouse",["clickhouse"]],["DuckDB",["duckdb"]],["Pinecone",["pinecone"]],["Weaviate",["weaviate"]],
  ["AWS",["aws","amazon web services"]],["Azure",["microsoft azure","azure"]],["Google Cloud",["google cloud platform","google cloud","gcp"]],["Docker",["docker"]],["Kubernetes",["kubernetes","k8s"]],["Terraform",["terraform"]],["Pulumi",["pulumi"]],["Ansible",["ansible"]],["Helm",["helm"]],["Jenkins",["jenkins"]],["GitHub Actions",["github actions"]],["GitLab CI",["gitlab ci"]],["Azure DevOps",["azure devops"]],["CI/CD",["ci/cd","continuous integration","continuous delivery"]],["Linux",["linux"]],["Nginx",["nginx"]],["Prometheus",["prometheus"]],["Grafana",["grafana"]],["Datadog",["datadog"]],["Splunk",["splunk"]],["New Relic",["new relic"]],["OpenTelemetry",["opentelemetry"]],
  ["Tableau",["tableau"]],["Power BI",["power bi"]],["Sigma",["sigma computing","sigma"]],["Looker",["looker"]],["Qlik",["qlik sense","qlikview","qlik"]],["Alteryx",["alteryx"]],["Excel",["microsoft excel","excel"]],["Pandas",["pandas"]],["NumPy",["numpy"]],["SciPy",["scipy"]],["Jupyter",["jupyter"]],["Matplotlib",["matplotlib"]],["Seaborn",["seaborn"]],
  ["Machine Learning",["machine learning"]],["NLP",["natural language processing","nlp"]],["Computer Vision",["computer vision"]],["LLM",["large language model","large language models","llm","llms"]],["RAG",["retrieval augmented generation","retrieval-augmented generation","rag"]],["LangChain",["langchain"]],["LlamaIndex",["llamaindex"]],["Hugging Face",["hugging face","huggingface"]],["PyTorch",["pytorch"]],["TensorFlow",["tensorflow"]],["scikit-learn",["scikit-learn","sklearn"]],["Keras",["keras"]],["XGBoost",["xgboost"]],["MLflow",["mlflow"]],["Kubeflow",["kubeflow"]],["MLOps",["mlops"]],["Prompt Engineering",["prompt engineering"]],["Agentic AI",["agentic ai","ai agents"]],["Vector Databases",["vector database","vector databases"]],
  ["React",["react.js","reactjs","react"]],["Angular",["angular"]],["Vue.js",["vue.js","vuejs"]],["Next.js",["next.js","nextjs"]],["Node.js",["node.js","nodejs"]],["Express.js",["express.js","expressjs"]],["NestJS",["nestjs"]],["Spring Boot",["spring boot"]],["Django",["django"]],["Flask",["flask"]],["FastAPI",["fastapi"]],["ASP.NET",["asp.net"]],[".NET",[".net","dotnet"]],["REST API",["rest api","restful api","restful services"]],["GraphQL",["graphql"]],["gRPC",["grpc"]],["Microservices",["microservices","micro-services"]],
  ["Git",["git version control","git workflows"]],["GitHub",["github"]],["GitLab",["gitlab"]],["Jira",["jira"]],["Confluence",["confluence"]],["Salesforce",["salesforce"]],["Workday",["workday"]],["ServiceNow",["servicenow"]],["SAP",["sap"]],["Oracle Cloud",["oracle cloud","oci"]],["Retool",["retool"]],["Kafka Connect",["kafka connect"]],["Debezium",["debezium"]],
  ["Cybersecurity",["cybersecurity"]],["SIEM",["security information and event management","siem"]],["IAM",["identity and access management","iam"]],["OAuth",["oauth","oauth2"]],["SAML",["saml"]],["Zero Trust",["zero trust"]],["SOC 2",["soc 2","soc2"]],["HIPAA",["hipaa"]],["PCI DSS",["pci dss","pci-dss"]]
].map(([canonical,aliases])=>Object.freeze({canonical,aliases:Object.freeze(aliases)})));
