const clean=value=>String(value||"").replace(/\r\n?/g,"\n").replace(/[ \t]+/g," ").replace(/ *\n */g,"\n").replace(/\n{3,}/g,"\n\n").trim();
const headingKey=(line,kind)=>{const h=clean(line).replace(/[:\s]+$/g,"").toLowerCase();const maps=kind==="resume"?[
  ["summary",/^(professional |career |executive )?summary$|^profile$|^objective$/],
  ["professional_experience",/^(professional |work |relevant )?experience$|^employment( history)?$|^career history$/],
  ["education",/^education$|^academic (background|history|qualifications)$/],
  ["skills",/^(technical |core |professional |key )?skills$|^technical proficiencies$|^competencies$/]
]:[
  ["overview",/^overview$|^about (the )?(role|position|job)$|^position summary$|^job summary$|^description$/],
  ["responsibilities",/^responsibilities$|^what you('ll| will) do$|^duties$|^essential (functions|duties)$/],
  ["qualifications",/^qualifications$|^requirements$|^what you('ll| will) need$|^preferred qualifications$|^minimum qualifications$/],
  ["benefits",/^benefits$|^what we offer$|^compensation( and benefits)?$|^perks$/]
];return maps.find(([,pattern])=>pattern.test(h))?.[0]||null;};
function parseSections(text,kind,keys){const result=Object.fromEntries(keys.map(key=>[key,""])),preamble=[],buckets=Object.fromEntries(keys.map(key=>[key,[]]));let current=null;for(const line of clean(text).split("\n")){const key=headingKey(line,kind);if(key){current=key;continue;}(current?buckets[current]:preamble).push(line);}for(const key of keys)result[key]=clean(buckets[key].join("\n"));if(kind==="resume"&&!result.summary&&preamble.length)result.summary=clean(preamble.join("\n"));if(kind==="jd"){result.other=clean(preamble.join("\n"));if(!Object.values(result).some(Boolean))result.other=clean(text);}return result;}
export const parseResumeSections=text=>parseSections(text,"resume",["summary","professional_experience","education","skills"]);
export const parseJobSections=text=>parseSections(text,"jd",["overview","responsibilities","qualifications","benefits","other"]);
export function detectJobConditions({title="",description="",location="",workArrangement=""}={}){const text=`${title}\n${location}\n${description}`,lower=text.toLowerCase();let arrangement=workArrangement||"UNSPECIFIED";if(!workArrangement){if(/\b(fully |100% |entirely )?remote\b|\btelecommut(e|ing)\b/.test(lower))arrangement="REMOTE";else if(/\bhybrid\b/.test(lower))arrangement="HYBRID";else if(/\b(on[ -]?site|in[ -]?office)\b/.test(lower))arrangement="ONSITE";}const clearances=[];if(/\bpublic trust\b/i.test(text))clearances.push("PUBLIC_TRUST");if(/\b(do[dD]|department of defense)\b.{0,40}\b(clearance|secret)\b|\bsecret clearance\b/i.test(text))clearances.push("DOD_SECRET");if(/\btop secret\b|\bTS\/SCI\b/i.test(text))clearances.push(/\bTS\/SCI\b/i.test(text)?"TS_SCI":"TOP_SECRET");if(/\bsecurity clearance\b/i.test(text)&&!clearances.length)clearances.push("OTHER_SECURITY_CLEARANCE");const noTravel=/\b(no travel|travel (is )?not required|0% travel)\b/i.test(text),travelMatch=text.match(/\b(?:travel (?:is )?required|required travel|up to \d{1,3}% travel|travel up to \d{1,3}%|\d{1,3}% travel)/i);return {locationText:arrangement==="REMOTE"?null:(clean(location)||null),workArrangement:arrangement,clearanceRequirements:[...new Set(clearances)],travelRequired:noTravel?false:travelMatch?true:null,travelDetails:travelMatch?.[0]||null};}
