export const APP_NAME="Resume JD Operations";
export const PAGE_SIZES=Object.freeze([10,25,50]);
export const USER_PAGE_SIZES=Object.freeze([25,50,100]);
export const STATUSES=Object.freeze(["ACTIVE","ARCHIVED"]);
export const SENIORITIES=Object.freeze(["INTERN","ENTRY","JUNIOR","MID","SENIOR","LEAD","PRINCIPAL","MANAGER","DIRECTOR","EXECUTIVE","UNSPECIFIED"]);
export const MIME_TYPES=Object.freeze(["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"]);
const directions=(key,column)=>({[`${key}_asc`]:{column,ascending:true},[`${key}_desc`]:{column,ascending:false}});
export const JOB_SORTS=Object.freeze({...directions("company","company"),...directions("title","job_title"),...directions("category","category_id"),...directions("subcategory","subcategory_id"),...directions("seniority","seniority"),...directions("source","source_site"),...directions("capturer","user_id"),...directions("status","status"),...directions("review","review_status"),...directions("created","created_at")});
export const RESUME_SORTS=Object.freeze({...directions("number","resume_number"),...directions("candidate","candidate_name"),...directions("name","resume_name"),...directions("category","primary_category_id"),...directions("subcategory","subcategory_id"),...directions("seniority","seniority"),...directions("status","status"),...directions("mime","mime_type"),...directions("updated","updated_at")});
export const USER_SORTS=Object.freeze({...directions("name","full_name"),...directions("email","email"),...directions("status","status"),...directions("roles","role_codes"),...directions("created","created_at")});
export const USER_ROLE_CODES=Object.freeze(["APPLIER","APPLYING_MANAGER","DEVELOPER","DEVELOPMENT_MANAGER","JD_FINDER","ADMIN"]);
export const SEARCH_MAX=100,SIGNED_URL_SECONDS=90;
