import React from"react";
import{Button,Card,Col,Empty,Flex,Input,InputNumber,Row,Typography}from"antd";
const{Text,Title}=Typography;
let sequence=0;const id=()=>globalThis.crypto?.randomUUID?.()||`education-${Date.now()}-${++sequence}`;
export const newEducation=()=>({id:id(),institution:"",degree:"",field_of_study:"",location:"",start_date:null,end_date:null,gpa:"",details:""});
export const newCertification=()=>({id:id(),name:"",issuer:"",issued_date:"",expiration_date:"",credential_id:"",credential_url:""});
const dateValue=value=>value?.year?`${value.year}-${String(value.month||1).padStart(2,"0")}`:"";
const dateFrom=value=>{const match=String(value||"").match(/^(\d{4})-(\d{2})$/);return match?{year:Number(match[1]),month:Number(match[2])}:null;};

export function EducationEditor({items,onChange}){const replace=(index,patch)=>onChange(items.map((item,position)=>position===index?{...item,...patch}:item)),remove=index=>onChange(items.filter((_,position)=>position!==index));return <section><Flex className="structured-heading" justify="space-between" align="start" gap="middle" wrap><div><Title level={3}>Education</Title><Text type="secondary">Add each school as a separate structured record.</Text></div><Button type="primary" onClick={()=>onChange([...items,newEducation()])}>Add education</Button></Flex>{!items.length&&<Card><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No structured education records. Review the legacy text and add each school."/></Card>}{items.map((item,index)=><Card key={item.id} title={`Education ${index+1}`} extra={<Button type="text" danger onClick={()=>remove(index)}>Remove</Button>}><Row gutter={[12,12]}><Col xs={24} md={12}><label>Institution<Input value={item.institution} onChange={event=>replace(index,{institution:event.target.value})} maxLength={240}/></label></Col><Col xs={24} md={12}><label>Degree<Input value={item.degree} onChange={event=>replace(index,{degree:event.target.value})} maxLength={200}/></label></Col><Col xs={24} md={12}><label>Field of study<Input value={item.field_of_study} onChange={event=>replace(index,{field_of_study:event.target.value})} maxLength={200}/></label></Col><Col xs={24} md={12}><label>Location<Input value={item.location} onChange={event=>replace(index,{location:event.target.value})} maxLength={200}/></label></Col><Col xs={24} md={8}><label>Start month<Input type="month" value={dateValue(item.start_date)} onChange={event=>replace(index,{start_date:dateFrom(event.target.value)})}/></label></Col><Col xs={24} md={8}><label>End month<Input type="month" value={dateValue(item.end_date)} onChange={event=>replace(index,{end_date:dateFrom(event.target.value)})}/></label></Col><Col xs={24} md={8}><label>GPA<Input value={item.gpa} onChange={event=>replace(index,{gpa:event.target.value})} maxLength={40}/></label></Col><Col span={24}><label>Details<Input.TextArea value={item.details} onChange={event=>replace(index,{details:event.target.value})} autoSize={{minRows:2,maxRows:6}} maxLength={10000}/></label></Col></Row></Card>)}</section>}

export function CertificationEditor({items,onChange}){const replace=(index,patch)=>onChange(items.map((item,position)=>position===index?{...item,...patch}:item)),remove=index=>onChange(items.filter((_,position)=>position!==index));return <section><Flex className="structured-heading" justify="space-between" align="start" gap="middle" wrap><div><Title level={3}>Certifications</Title><Text type="secondary">Optional credentials stored with this Resume.</Text></div><Button onClick={()=>onChange([...items,newCertification()])}>Add certification</Button></Flex>{items.map((item,index)=><Card key={item.id} title={`Certification ${index+1}`} extra={<Button type="text" danger onClick={()=>remove(index)}>Remove</Button>}><Row gutter={[12,12]}><Col xs={24} md={12}><label>Name<Input value={item.name} onChange={event=>replace(index,{name:event.target.value})} maxLength={240}/></label></Col><Col xs={24} md={12}><label>Issuer<Input value={item.issuer} onChange={event=>replace(index,{issuer:event.target.value})} maxLength={240}/></label></Col><Col xs={24} md={6}><label>Issued date<Input type="date" value={item.issued_date||""} onChange={event=>replace(index,{issued_date:event.target.value})}/></label></Col><Col xs={24} md={6}><label>Expiration date<Input type="date" value={item.expiration_date||""} onChange={event=>replace(index,{expiration_date:event.target.value})}/></label></Col><Col xs={24} md={6}><label>Credential ID<Input value={item.credential_id} onChange={event=>replace(index,{credential_id:event.target.value})}/></label></Col><Col xs={24} md={6}><label>Credential URL<Input type="url" value={item.credential_url} onChange={event=>replace(index,{credential_url:event.target.value})}/></label></Col></Row></Card>)}</section>}
