import{Body,Controller,Delete,Get,Inject,Param,ParseUUIDPipe,Patch,Post,Query,Req,UploadedFile,UseGuards,UseInterceptors}from"@nestjs/common";import{FileInterceptor}from"@nestjs/platform-express";import{ApiBearerAuth,ApiTags}from"@nestjs/swagger";import{AuthGuard}from"../auth/auth.guard.js";import{RequireRoles}from"../auth/require-roles.decorator.js";import{RolesGuard}from"../auth/roles.guard.js";import type{ApiRequest}from"../common/types/request.js";import{DtoValidationPipe}from"../common/validation/dto-validation.pipe.js";import{ResumeService}from"./resume.service.js";import{ResumeBannedCompanyDto}from"./resume-banned-company.dto.js";import{ResumeNameDto}from"./resume-name.dto.js";import{ResumeStatusDto}from"./resume-status.dto.js";
const ROLES=["APPLIER","APPLYING_MANAGER","DEVELOPER","DEVELOPMENT_MANAGER","ADMIN"]as const;
const MANAGERS=["APPLYING_MANAGER","ADMIN"]as const;
@ApiTags("Resumes")@ApiBearerAuth()@Controller("resumes")@UseGuards(AuthGuard,RolesGuard)export class ResumeController{constructor(@Inject(ResumeService)private readonly resumes:ResumeService){}
@Get()@RequireRoles(...ROLES)async list(@Req()r:ApiRequest,@Query()q:any){return{data:await this.resumes.list(r.user!,q),requestId:r.requestId};}
@Get("count")@RequireRoles(...ROLES)async count(@Req()r:ApiRequest,@Query("status")status?:string){return{data:await this.resumes.count(r.user!,status),requestId:r.requestId};}
@Get("recent")@RequireRoles(...ROLES)async recent(@Req()r:ApiRequest){return{data:await this.resumes.recent(r.user!),requestId:r.requestId};}
@Post("identity-duplicates")@RequireRoles("ADMIN")async identity(@Req()r:ApiRequest,@Body()b:any){return{data:await this.resumes.identity(r.user!,b),requestId:r.requestId};}
@Get("checksum/:checksum")@RequireRoles("ADMIN")async checksum(@Req()r:ApiRequest,@Param("checksum")checksum:string){return{data:await this.resumes.checksum(r.user!,checksum),requestId:r.requestId};}
@Post()@RequireRoles("ADMIN")@UseInterceptors(FileInterceptor("file",{limits:{fileSize:5242880,files:1}}))async upload(@Req()r:ApiRequest,@UploadedFile()file:any,@Body("metadata")raw:string){let metadata;try{metadata=JSON.parse(raw||"{}");}catch{metadata={};}return{data:await this.resumes.upload(r.user!,metadata,file),requestId:r.requestId};}
@Post(":id/cover-letter")@RequireRoles(...MANAGERS)@UseInterceptors(FileInterceptor("file",{limits:{fileSize:5242880,files:1}}))async uploadCoverLetter(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@UploadedFile()file:any){return{data:await this.resumes.uploadCoverLetter(r.user!,id,file),requestId:r.requestId};}
@Get(":id/cover-letter/file-url")@RequireRoles(...ROLES)async coverLetterFile(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return{data:await this.resumes.coverLetterSignedUrl(r.user!,id),requestId:r.requestId};}
@Delete(":id/cover-letter")@RequireRoles(...MANAGERS)async removeCoverLetter(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return{data:await this.resumes.removeCoverLetter(r.user!,id),requestId:r.requestId};}
@Get(":id/banned-companies")@RequireRoles(...ROLES)async listBannedCompanies(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return{data:await this.resumes.listBannedCompanies(r.user!,id),requestId:r.requestId};}
@Post(":id/banned-companies")@RequireRoles(...MANAGERS)async addBannedCompany(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ResumeBannedCompanyDto))body:ResumeBannedCompanyDto){return{data:await this.resumes.addBannedCompany(r.user!,id,body.companyName),requestId:r.requestId};}
@Delete(":id/banned-companies/:entryId")@RequireRoles(...MANAGERS)async removeBannedCompany(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Param("entryId",new ParseUUIDPipe({version:"4"}))entryId:string){return{data:await this.resumes.removeBannedCompany(r.user!,id,entryId),requestId:r.requestId};}
@Patch(":id/name")@RequireRoles(...MANAGERS)async rename(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ResumeNameDto))body:ResumeNameDto){return{data:await this.resumes.rename(r.user!,id,body.resumeName),requestId:r.requestId};}
@Patch(":id")@RequireRoles("ADMIN")async update(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body()b:any){return{data:await this.resumes.update(r.user!,id,b),requestId:r.requestId};}
@Patch(":id/status")@RequireRoles(...MANAGERS)async status(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string,@Body(new DtoValidationPipe(ResumeStatusDto))body:ResumeStatusDto){return{data:await this.resumes.status(r.user!,id,body.status),requestId:r.requestId};}
@Get(":id/file-url")@RequireRoles(...ROLES)async file(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return{data:await this.resumes.signedUrl(r.user!,id),requestId:r.requestId};}
@Get(":id")@RequireRoles(...ROLES)async detail(@Req()r:ApiRequest,@Param("id",new ParseUUIDPipe({version:"4"}))id:string){return{data:await this.resumes.detail(r.user!,id),requestId:r.requestId};}}
