import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {RESUME_DETAIL_FIELDS,RESUME_LIST_FIELDS} from "../src/services/resume-read-service.js";import {createResumeSignedUrl} from "../src/services/storage-read-service.js";import {JOB_SORTS,RESUME_SORTS,SIGNED_URL_SECONDS} from "../src/shared/constants.js";import {pageRange} from "../src/shared/pagination.js";
import {applyFilters,applySearch,applySort} from "../src/services/query-helpers.js";import {normalizeError} from "../src/shared/errors.js";
const jobBackendSource=()=>readFile(new URL("../../apps/api/src/job-descriptions/job-description-read.service.ts",import.meta.url),"utf8");
test("list contracts exclude large text and details include it",async()=>{const source=await jobBackendSource(),list=source.match(/JOB_LIST_FIELDS = ([^;]+)/)?.[1]||"",detail=source.match(/JOB_DETAIL_FIELDS = ([^;]+)/)?.[1]||"";assert.equal(list.includes("description_text"),false);assert.equal(detail.includes("description_text"),true);assert.equal(RESUME_LIST_FIELDS.includes("resume_text"),false);assert.equal(RESUME_DETAIL_FIELDS.includes("resume_text"),true);});
test("job contracts include the capturer profile",async()=>{const source=await jobBackendSource();assert.match(source,/user_id/);assert.match(source,/captured_by:user_profiles/);assert.match(source,/display_name,email/);});
test("sort mappings and range are controlled",()=>{assert.deepEqual(JOB_SORTS.created_desc,{column:"created_at",ascending:false});assert.deepEqual(RESUME_SORTS.candidate_asc,{column:"candidate_name",ascending:true});assert.deepEqual(pageRange(2,25),{from:25,to:49});});
test("signed URL is requested through the authenticated backend",async()=>{let call;const originalFetch=globalThis.fetch,client={auth:{getSession:async()=>({data:{session:{access_token:"token"}},error:null})},storage:{from:()=>{throw new Error("Direct Storage attempted");}}};globalThis.fetch=async(url,options)=>{call={url,options};return new Response(JSON.stringify({data:{signedUrl:"https://signed.example/file",expiresInSeconds:SIGNED_URL_SECONDS}}),{status:200});};try{assert.equal(await createResumeSignedUrl(client,{id:"f3a34ffd-d66a-49f7-815e-c7786857576b",apiBaseUrl:"https://api.example.com"}),"https://signed.example/file");assert.match(call.url,/\/api\/v1\/resumes\//);await assert.rejects(()=>createResumeSignedUrl(client,{}),{code:"SIGNED_URL_FAILED"});}finally{globalThis.fetch=originalFetch;}});
test("query helpers apply only present filters and allowlisted sort",()=>{const calls=[],query={eq:(...args)=>{calls.push(["eq",...args]);return query;},or:value=>{calls.push(["or",value]);return query;},order:(...args)=>{calls.push(["order",...args]);return query;}};applyFilters(query,{categoryId:"cat",status:""},{categoryId:"category_id",status:"status"});applySearch(query,"Data Engineer",["company","job_title"]);applySort(query,"unknown",JOB_SORTS,"created_desc");assert.deepEqual(calls[0],["eq","category_id","cat"]);assert.equal(calls.some(x=>x[0]==="eq"&&x[1]==="status"),false);assert.equal(calls[1][1],"company.ilike.%Data Engineer%,job_title.ilike.%Data Engineer%");assert.deepEqual(calls[2],["order","created_at",{ascending:false}]);});
test("raw errors normalize to safe contracts",()=>{const x=normalizeError(new Error("database policy details"),"Unable to load jobs.");assert.equal(x.code,"DATA_REQUEST_FAILED");assert.equal(x.message,"Unable to load jobs.");assert.equal(x.retryable,true);});
