-- v3.10: expose Resume name on the autofill profile payload used by the Resume editor.

create or replace function public.get_candidate_autofill_profile_v088(p_resume_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_result jsonb;
begin
  if not public.candidate_resume_actor_can_view_v088(p_resume_id) then raise exception 'CANDIDATE_PROFILE_NOT_FOUND: The Resume profile was not found or is not accessible.' using errcode='P0001'; end if;
  select jsonb_build_object(
    'id',r.id,'resumeId',r.id,'resumeName',r.resume_name,'fullName',r.candidate_name,'firstName',r.candidate_first_name,'middleName',r.candidate_middle_name,'lastName',r.candidate_last_name,
    'email',r.candidate_email,'phone',r.candidate_phone,'reviewStatus',r.profile_review_status,'reviewedBy',r.profile_reviewed_by,'reviewedAt',r.profile_reviewed_at,
    'createdAt',r.created_at,'updatedAt',r.updated_at,'summary',coalesce(r.structured_content->>'summary',''),'skills',coalesce(r.structured_content->>'skills',''),
    'addresses',case when coalesce(r.address_line_1,r.address_line_2,r.address_city,r.address_state_region,r.address_postal_code,r.address_country) is null then '[]'::jsonb else jsonb_build_array(jsonb_build_object('id',r.id,'addressType','PRIMARY','addressLine1',r.address_line_1,'addressLine2',r.address_line_2,'city',r.address_city,'stateRegion',r.address_state_region,'postalCode',r.address_postal_code,'country',r.address_country,'isPrimary',true)) end,
    'links',(select coalesce(jsonb_agg(x.value),'[]'::jsonb) from jsonb_array_elements(jsonb_build_array(case when r.linkedin_url is null then null else jsonb_build_object('id',r.id::text||'-linkedin','linkType','LINKEDIN','label',null,'url',r.linkedin_url) end,case when r.github_url is null then null else jsonb_build_object('id',r.id::text||'-github','linkType','GITHUB','label',null,'url',r.github_url) end,case when r.portfolio_url is null then null else jsonb_build_object('id',r.id::text||'-portfolio','linkType','PORTFOLIO','label',null,'url',r.portfolio_url) end)) x(value) where x.value<>'null'::jsonb),
    'employment',coalesce((select jsonb_agg(jsonb_build_object('id',x.value->>'id','company',x.value->>'company','jobTitle',x.value->>'job_title','location',nullif(x.value->>'location',''),'startDate',public.candidate_partial_date_v088(x.value->'start_date'),'endDate',public.candidate_partial_date_v088(x.value->'end_date'),'isCurrent',lower(coalesce(x.value->>'is_current','false')) in ('true','t','1','yes'),'experienceDetails',nullif(x.value->>'experience_details',''),'displayOrder',(x.ordinality-1)::integer,'source','RESUME_METADATA') order by x.ordinality) from jsonb_array_elements(case when jsonb_typeof(r.structured_content->'professional_experience')='array' then r.structured_content->'professional_experience' else '[]'::jsonb end) with ordinality x(value,ordinality)),'[]'::jsonb),
    'education',coalesce((select jsonb_agg(jsonb_build_object('id',x.value->>'id','institution',x.value->>'institution','degree',nullif(x.value->>'degree',''),'fieldOfStudy',nullif(x.value->>'field_of_study',''),'location',nullif(x.value->>'location',''),'startDate',public.candidate_partial_date_v088(x.value->'start_date'),'endDate',public.candidate_partial_date_v088(x.value->'end_date'),'gpa',nullif(x.value->>'gpa',''),'details',nullif(x.value->>'details',''),'displayOrder',(x.ordinality-1)::integer,'source','RESUME_METADATA') order by x.ordinality) from jsonb_array_elements(case when jsonb_typeof(r.structured_content->'education')='array' then r.structured_content->'education' else '[]'::jsonb end) with ordinality x(value,ordinality)),'[]'::jsonb),
    'educationLegacyText',coalesce(r.structured_content->>'education_legacy_text',''),
    'certifications',coalesce((select jsonb_agg(jsonb_build_object('id',x.value->>'id','name',x.value->>'name','issuer',nullif(x.value->>'issuer',''),'issuedDate',nullif(x.value->>'issued_date',''),'expirationDate',nullif(x.value->>'expiration_date',''),'credentialId',nullif(x.value->>'credential_id',''),'credentialUrl',nullif(x.value->>'credential_url',''),'source','RESUME_METADATA') order by x.ordinality) from jsonb_array_elements(case when jsonb_typeof(r.structured_content->'certifications')='array' then r.structured_content->'certifications' else '[]'::jsonb end) with ordinality x(value,ordinality)),'[]'::jsonb)
  ) into v_result from public.resumes r where r.id=p_resume_id;
  if v_result is null then raise exception 'CANDIDATE_PROFILE_NOT_FOUND: The Resume was not found.' using errcode='P0001'; end if;
  return v_result;
end;
$$;
