-- v0.9.1: atomic structured Resume editing on the canonical resumes row.

create or replace function public.get_candidate_autofill_profile_v088(p_resume_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_result jsonb;
begin
  if not public.candidate_resume_actor_can_view_v088(p_resume_id) then raise exception 'CANDIDATE_PROFILE_NOT_FOUND: The Resume profile was not found or is not accessible.' using errcode='P0001'; end if;
  select jsonb_build_object(
    'id',r.id,'resumeId',r.id,'fullName',r.candidate_name,'firstName',r.candidate_first_name,'middleName',r.candidate_middle_name,'lastName',r.candidate_last_name,
    'email',r.candidate_email,'phone',r.candidate_phone,'reviewStatus',r.profile_review_status,'reviewedBy',r.profile_reviewed_by,'reviewedAt',r.profile_reviewed_at,
    'createdAt',r.created_at,'updatedAt',r.updated_at,'summary',coalesce(r.structured_content->>'summary',''),'skills',coalesce(r.structured_content->>'skills',''),
    'addresses',case when coalesce(r.address_line_1,r.address_line_2,r.address_city,r.address_state_region,r.address_postal_code,r.address_country) is null then '[]'::jsonb else jsonb_build_array(jsonb_build_object('id',r.id,'addressType','PRIMARY','addressLine1',r.address_line_1,'addressLine2',r.address_line_2,'city',r.address_city,'stateRegion',r.address_state_region,'postalCode',r.address_postal_code,'country',r.address_country,'isPrimary',true)) end,
    'links',(select coalesce(jsonb_agg(x.value),'[]'::jsonb) from jsonb_array_elements(jsonb_build_array(case when r.linkedin_url is null then null else jsonb_build_object('id',r.id::text||'-linkedin','linkType','LINKEDIN','label',null,'url',r.linkedin_url) end,case when r.github_url is null then null else jsonb_build_object('id',r.id::text||'-github','linkType','GITHUB','label',null,'url',r.github_url) end,case when r.portfolio_url is null then null else jsonb_build_object('id',r.id::text||'-portfolio','linkType','PORTFOLIO','label',null,'url',r.portfolio_url) end)) x(value) where x.value<>'null'::jsonb),
    'employment',coalesce((select jsonb_agg(jsonb_build_object('id',x.value->>'id','company',x.value->>'company','jobTitle',x.value->>'job_title','location',nullif(x.value->>'location',''),'startDate',public.candidate_partial_date_v088(x.value->'start_date'),'endDate',public.candidate_partial_date_v088(x.value->'end_date'),'isCurrent',lower(coalesce(x.value->>'is_current','false')) in ('true','t','1','yes'),'experienceDetails',nullif(x.value->>'experience_details',''),'displayOrder',(x.ordinality-1)::integer,'source','RESUME_METADATA') order by x.ordinality) from jsonb_array_elements(case when jsonb_typeof(r.structured_content->'professional_experience')='array' then r.structured_content->'professional_experience' else '[]'::jsonb end) with ordinality x(value,ordinality)),'[]'::jsonb),
    'education',coalesce((select jsonb_agg(jsonb_build_object('id',x.value->>'id','institution',x.value->>'institution','degree',nullif(x.value->>'degree',''),'fieldOfStudy',nullif(x.value->>'field_of_study',''),'location',nullif(x.value->>'location',''),'startDate',public.candidate_partial_date_v088(x.value->'start_date'),'endDate',public.candidate_partial_date_v088(x.value->'end_date'),'gpa',nullif(x.value->>'gpa',''),'details',nullif(x.value->>'details',''),'displayOrder',(x.ordinality-1)::integer,'source','RESUME_METADATA') order by x.ordinality) from jsonb_array_elements(case when jsonb_typeof(r.structured_content->'education')='array' then r.structured_content->'education' else '[]'::jsonb end) with ordinality x(value,ordinality)),'[]'::jsonb),
    'educationLegacyText',coalesce(r.structured_content->>'education_legacy_text',''),
    'certifications',coalesce((select jsonb_agg(jsonb_build_object('id',x.value->>'id','name',x.value->>'name','issuer',nullif(x.value->>'issuer',''),'issuedDate',nullif(x.value->>'issued_date',''),'expirationDate',nullif(x.value->>'expiration_date',''),'credentialId',nullif(x.value->>'credential_id',''),'credentialUrl',nullif(x.value->>'credential_url',''),'source','RESUME_METADATA') order by x.ordinality) from jsonb_array_elements(case when jsonb_typeof(r.structured_content->'certifications')='array' then r.structured_content->'certifications' else '[]'::jsonb end) with ordinality x(value,ordinality)),'[]'::jsonb)
  ) into v_result from public.resumes r where r.id=p_resume_id;
  if v_result is null then raise exception 'CANDIDATE_PROFILE_NOT_FOUND: The Resume was not found.' using errcode='P0001'; end if;
  return v_result;
end;
$$;

create or replace function public.update_resume_structured_content_v091(p_resume_id uuid,p_summary text,p_skills text,p_employment jsonb,p_education jsonb,p_certifications jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_employment jsonb; v_education jsonb; v_certifications jsonb;
begin
  perform public.assert_application_manager();
  if jsonb_typeof(p_employment)<>'array' or jsonb_typeof(p_education)<>'array' or jsonb_typeof(p_certifications)<>'array' then raise exception 'STRUCTURED_RESUME_INVALID: Structured sections must be arrays.' using errcode='P0001'; end if;
  if jsonb_array_length(p_employment)>50 or jsonb_array_length(p_education)>30 or jsonb_array_length(p_certifications)>50 then raise exception 'STRUCTURED_RESUME_INVALID: Too many structured records.' using errcode='P0001'; end if;
  if char_length(coalesce(p_summary,''))>30000 or char_length(coalesce(p_skills,''))>30000 then raise exception 'STRUCTURED_RESUME_INVALID: Summary or skills are too long.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_employment) x where btrim(coalesce(x->>'company',''))='' or btrim(coalesce(x->>'jobTitle',''))='') then raise exception 'STRUCTURED_RESUME_INVALID: Every employment record needs a company and job title.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_employment) x where char_length(coalesce(x->>'company',''))>200 or char_length(coalesce(x->>'jobTitle',''))>200 or char_length(coalesce(x->>'location',''))>200 or char_length(coalesce(x->>'experienceDetails',''))>30000) then raise exception 'STRUCTURED_RESUME_INVALID: An employment field is too long.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_education) x where btrim(coalesce(x->>'institution',''))='') then raise exception 'STRUCTURED_RESUME_INVALID: Every education record needs an institution.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_education) x where char_length(coalesce(x->>'institution',''))>240 or char_length(coalesce(x->>'degree',''))>200 or char_length(coalesce(x->>'fieldOfStudy',''))>200 or char_length(coalesce(x->>'location',''))>200 or char_length(coalesce(x->>'gpa',''))>40 or char_length(coalesce(x->>'details',''))>10000) then raise exception 'STRUCTURED_RESUME_INVALID: An education field is too long.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_certifications) x where btrim(coalesce(x->>'name',''))='') then raise exception 'STRUCTURED_RESUME_INVALID: Every certification needs a name.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_certifications) x where char_length(coalesce(x->>'name',''))>240 or char_length(coalesce(x->>'issuer',''))>240 or char_length(coalesce(x->>'credentialId',''))>240 or char_length(coalesce(x->>'credentialUrl',''))>2000) then raise exception 'STRUCTURED_RESUME_INVALID: A certification field is too long.' using errcode='P0001'; end if;
  if exists(select 1 from jsonb_array_elements(p_certifications) x where coalesce(x->>'credentialUrl','')<>'' and x->>'credentialUrl' !~* '^https://[^[:space:]]+$') then raise exception 'STRUCTURED_RESUME_INVALID: Credential URLs must use HTTPS.' using errcode='P0001'; end if;

  select coalesce(jsonb_agg(jsonb_build_object('id',coalesce(nullif(btrim(x.value->>'id'),''),gen_random_uuid()::text),'company',btrim(x.value->>'company'),'job_title',btrim(x.value->>'jobTitle'),'location',btrim(coalesce(x.value->>'location','')),'start_date',public.candidate_date_json_v088(nullif(x.value->>'startDate','')::date),'end_date',case when coalesce((x.value->>'isCurrent')::boolean,false) then null else public.candidate_date_json_v088(nullif(x.value->>'endDate','')::date) end,'is_current',coalesce((x.value->>'isCurrent')::boolean,false),'experience_details',btrim(coalesce(x.value->>'experienceDetails',''))) order by x.ordinality),'[]'::jsonb) into v_employment from jsonb_array_elements(p_employment) with ordinality x(value,ordinality);
  select coalesce(jsonb_agg(jsonb_build_object('id',coalesce(nullif(btrim(x.value->>'id'),''),gen_random_uuid()::text),'institution',btrim(x.value->>'institution'),'degree',btrim(coalesce(x.value->>'degree','')),'field_of_study',btrim(coalesce(x.value->>'fieldOfStudy','')),'location',btrim(coalesce(x.value->>'location','')),'start_date',public.candidate_date_json_v088(nullif(x.value->>'startDate','')::date),'end_date',public.candidate_date_json_v088(nullif(x.value->>'endDate','')::date),'gpa',btrim(coalesce(x.value->>'gpa','')),'details',btrim(coalesce(x.value->>'details',''))) order by x.ordinality),'[]'::jsonb) into v_education from jsonb_array_elements(p_education) with ordinality x(value,ordinality);
  select coalesce(jsonb_agg(jsonb_build_object('id',coalesce(nullif(btrim(x.value->>'id'),''),gen_random_uuid()::text),'name',btrim(x.value->>'name'),'issuer',btrim(coalesce(x.value->>'issuer','')),'issued_date',nullif(x.value->>'issuedDate',''),'expiration_date',nullif(x.value->>'expirationDate',''),'credential_id',btrim(coalesce(x.value->>'credentialId','')),'credential_url',btrim(coalesce(x.value->>'credentialUrl',''))) order by x.ordinality),'[]'::jsonb) into v_certifications from jsonb_array_elements(p_certifications) with ordinality x(value,ordinality);

  update public.resumes set structured_content=coalesce(structured_content,'{}'::jsonb)||jsonb_build_object('summary',btrim(coalesce(p_summary,'')),'skills',btrim(coalesce(p_skills,'')),'professional_experience',v_employment,'education',v_education,'certifications',v_certifications),structured_schema_version=greatest(structured_schema_version,3),profile_review_status='VERIFIED',profile_reviewed_by=auth.uid(),profile_reviewed_at=now() where id=p_resume_id;
  if not found then raise exception 'CANDIDATE_PROFILE_NOT_FOUND: The Resume was not found.' using errcode='P0001'; end if;
  return public.get_candidate_autofill_profile_v088(p_resume_id);
exception when invalid_datetime_format or datetime_field_overflow then raise exception 'STRUCTURED_RESUME_INVALID: Review the structured Resume dates.' using errcode='P0001';
end;
$$;

revoke all on function public.update_resume_structured_content_v091(uuid,text,text,jsonb,jsonb,jsonb) from public,anon;
grant execute on function public.update_resume_structured_content_v091(uuid,text,text,jsonb,jsonb,jsonb) to authenticated;
