-- v1.1: original/tailored Resume identity and human-readable Resume numbers.
-- Existing rows are originals. Tailored rows are one-level children and never
-- replace or mutate their source Resume.

alter table public.resumes
  add column resume_number bigint generated by default as identity,
  add column resume_type text not null default 'ORIGINAL',
  add column parent_resume_id uuid references public.resumes(id) on delete restrict;

alter table public.resumes
  add constraint resumes_resume_number_key unique(resume_number),
  add constraint resumes_resume_number_positive check(resume_number>0),
  add constraint resumes_resume_type_check check(resume_type in('ORIGINAL','TAILORED')),
  add constraint resumes_parent_shape_check check(
    (resume_type='ORIGINAL' and parent_resume_id is null)
    or(resume_type='TAILORED' and parent_resume_id is not null and parent_resume_id<>id)
  );

alter table public.resumes drop constraint if exists resumes_storage_bucket_check;
alter table public.resumes add constraint resumes_storage_bucket_variant_check check(
  (resume_type='ORIGINAL' and storage_bucket='original-resumes')
  or(resume_type='TAILORED' and storage_bucket='tailored-resumes')
);

create index resumes_type_status_updated_idx
  on public.resumes(resume_type,status,updated_at desc);
create index resumes_parent_updated_idx
  on public.resumes(parent_resume_id,updated_at desc)
  where parent_resume_id is not null;

create or replace function public.validate_resume_variant()
returns trigger language plpgsql security invoker set search_path=public,pg_temp as $$
declare v_parent public.resumes;
begin
  if tg_op='UPDATE' and(
    new.resume_number is distinct from old.resume_number
    or new.resume_type is distinct from old.resume_type
    or new.parent_resume_id is distinct from old.parent_resume_id
  )then
    raise exception 'RESUME_VARIANT_IMMUTABLE: Resume number, type, and parent cannot be changed.' using errcode='23514';
  end if;
  if new.resume_type='TAILORED' then
    select * into v_parent from public.resumes where id=new.parent_resume_id;
    if not found or v_parent.resume_type<>'ORIGINAL' then
      raise exception 'RESUME_PARENT_INVALID: A tailored Resume must reference an original Resume.' using errcode='23514';
    end if;
    if v_parent.user_id is distinct from new.user_id then
      raise exception 'RESUME_PARENT_OWNER_MISMATCH: Resume variants must have the same owner.' using errcode='42501';
    end if;
  end if;
  return new;
end$$;

create trigger resumes_validate_variant before insert or update on public.resumes
for each row execute function public.validate_resume_variant();
revoke all on function public.validate_resume_variant() from public,anon,authenticated;

-- Application creation always starts from an original Resume. A later protected
-- approval operation may replace that one reference with a tailored child.
create or replace function public.validate_application_resume_variant()
returns trigger language plpgsql security invoker set search_path=public,pg_temp as $$
declare v_new public.resumes;v_old public.resumes;
begin
  select * into v_new from public.resumes where id=new.resume_id;
  if not found then return new;end if;
  if tg_op='INSERT' and v_new.resume_type<>'ORIGINAL' then
    raise exception 'APPLICATION_REQUIRES_ORIGINAL_RESUME: New Applications must start with an original Resume.' using errcode='23514';
  end if;
  if tg_op='UPDATE' and new.resume_id is distinct from old.resume_id and v_new.resume_type='TAILORED' then
    select * into v_old from public.resumes where id=old.resume_id;
    if v_new.parent_resume_id is distinct from coalesce(v_old.parent_resume_id,v_old.id) then
      raise exception 'APPLICATION_RESUME_FAMILY_MISMATCH: A tailored Resume must belong to the Application source Resume.' using errcode='23514';
    end if;
  end if;
  return new;
end$$;

create trigger applications_validate_resume_variant before insert or update of resume_id on public.applications
for each row execute function public.validate_application_resume_variant();
revoke all on function public.validate_application_resume_variant() from public,anon,authenticated;

-- General duplicate detection is about primary/original Resumes only.
create or replace function public.find_resume_identity_duplicates(
  p_candidate_name text,p_candidate_email text,p_candidate_phone text
)
returns table(id uuid,candidate_name text,candidate_email text,candidate_phone text,resume_name text,status text,created_at timestamptz)
language plpgsql stable security invoker set search_path=public,pg_temp as $$
declare
  v_name text:=regexp_replace(lower(btrim(coalesce(p_candidate_name,''))),'[^[:alnum:]]+','','g');
  v_email text:=lower(btrim(coalesce(p_candidate_email,'')));
  v_phone text:=regexp_replace(coalesce(p_candidate_phone,''),'[^0-9]','','g');
begin
  if v_name='' or v_email='' or char_length(v_phone)<7 then return;end if;
  return query select r.id,r.candidate_name,r.candidate_email,r.candidate_phone,r.resume_name,r.status,r.created_at
  from public.resumes r
  where r.resume_type='ORIGINAL'
    and regexp_replace(lower(btrim(r.candidate_name)),'[^[:alnum:]]+','','g')=v_name
    and lower(btrim(r.candidate_email))=v_email
    and regexp_replace(r.candidate_phone,'[^0-9]','','g')=v_phone
  order by(r.status='ACTIVE')desc,r.created_at desc limit 10;
end$$;

revoke all on function public.find_resume_identity_duplicates(text,text,text) from public,anon;
grant execute on function public.find_resume_identity_duplicates(text,text,text) to authenticated;

-- Individual Application pickers expose only active originals.
create or replace function public.list_application_resumes(p_job_description_id uuid,p_search text default '',p_limit integer default 100)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_category uuid;v_result jsonb;
begin
  perform public.assert_application_manager();
  select category_id into v_category from public.job_descriptions where id=p_job_description_id;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.same_category desc,x.candidate_name,x.resume_name),'[]'::jsonb) into v_result
  from(
    select r.id,r.resume_number,r.resume_type,r.candidate_name,r.resume_name,r.primary_category_id,r.seniority,
      (r.primary_category_id=v_category) same_category
    from public.resumes r
    where r.status='ACTIVE' and r.resume_type='ORIGINAL' and(
      coalesce(trim(p_search),'')='' or r.search_vector@@websearch_to_tsquery('english',trim(p_search))
      or(regexp_replace(upper(trim(p_search)),'^(RESUME[- ]?|#)','')~'^[0-9]+$' and r.resume_number::text=regexp_replace(upper(trim(p_search)),'^(RESUME[- ]?|#)',''))
    )
    order by(r.primary_category_id=v_category)desc,r.candidate_name,r.resume_name
    limit least(greatest(coalesce(p_limit,100),1),200)
  )x;
  return v_result;
end$$;

revoke all on function public.list_application_resumes(uuid,text,integer) from public,anon;
grant execute on function public.list_application_resumes(uuid,text,integer) to authenticated;

-- Overview Resume totals and recent Resume cards also represent originals only.
create or replace function public.get_business_overview()
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_result jsonb;v_manager boolean:=public.has_role('APPLYING_MANAGER') or public.has_role('ADMIN');
begin
  if not public.has_any_role(array['APPLIER','APPLYING_MANAGER','ADMIN']) then
    raise exception 'BUSINESS_ACCESS_DENIED: Business data access is required.' using errcode='42501';
  end if;
  select jsonb_build_object(
    'jobCounts',jsonb_build_object('total',(select count(*) from public.job_descriptions),'active',(select count(*) from public.job_descriptions where status='ACTIVE')),
    'resumeCounts',jsonb_build_object(
      'total',(select count(*) from public.resumes where resume_type='ORIGINAL'),
      'active',(select count(*) from public.resumes where resume_type='ORIGINAL' and status='ACTIVE')
    ),
    'recentJobs',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from(
      select j.id,j.company,j.job_title,j.category_id,j.status,j.created_at,jsonb_build_object('display_name',up.display_name,'email',up.email) captured_by
      from public.job_descriptions j left join public.user_profiles up on up.id=j.user_id order by j.created_at desc limit 5
    )x),
    'recentResumes',case when v_manager then '[]'::jsonb else(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from(
      select id,resume_number,candidate_name,resume_name,primary_category_id,status,updated_at
      from public.resumes where resume_type='ORIGINAL' order by created_at desc limit 5
    )x)end,
    'applierPerformance',case when not v_manager then '[]'::jsonb else(select coalesce(jsonb_agg(to_jsonb(x) order by x.completed_count desc,x.applied_count desc,x.applier_name),'[]'::jsonb) from(
      with appliers as(
        select distinct p.id,coalesce(nullif(btrim(p.full_name),''),p.email) applier_name,p.email
        from public.profiles p join public.user_roles ur on ur.user_id=p.id join public.roles r on r.id=ur.role_id
        where p.status='ACTIVE' and r.active and r.code='APPLIER'
      )
      select p.id,p.applier_name,p.email,
        count(a.id) filter(where a.status<>'CANCELLED')::integer assigned_count,
        count(a.id) filter(where a.status in('ASSIGNED','IN_PROGRESS','BLOCKED'))::integer active_count,
        count(a.id) filter(where a.status in('APPLIED','SCREENING','INTERVIEW_SCHEDULED','OFFER_RECEIVED','REJECTED','WITHDRAWN','CLOSED'))::integer completed_count,
        count(a.id) filter(where a.status in('APPLIED','SCREENING','INTERVIEW_SCHEDULED','OFFER_RECEIVED','REJECTED','WITHDRAWN','CLOSED'))::integer applied_count,
        count(a.id) filter(where a.applied_at>=date_trunc('day',now()))::integer applied_today,
        count(a.id) filter(where a.applied_at>=now()-interval '3 days')::integer applied_last_3_days,
        count(a.id) filter(where a.applied_at>=date_trunc('week',now()))::integer applied_this_week,
        count(a.id) filter(where a.applied_at>=date_trunc('month',now()))::integer applied_this_month,
        count(a.id) filter(where a.applied_at>=now()-interval '30 days')::integer applied_last_30_days,
        case when count(a.id) filter(where a.status<>'CANCELLED')=0 then 0 else round(100.0*count(a.id) filter(where a.status in('APPLIED','SCREENING','INTERVIEW_SCHEDULED','OFFER_RECEIVED','REJECTED','WITHDRAWN','CLOSED'))/count(a.id) filter(where a.status<>'CANCELLED'),1)end completion_rate
      from appliers p left join public.applications a on a.assigned_to=p.id group by p.id,p.applier_name,p.email
    )x)end
  )into v_result;
  return v_result;
end$$;

revoke all on function public.get_business_overview() from public,anon;
grant execute on function public.get_business_overview() to authenticated;

comment on column public.resumes.resume_number is 'Unique decimal identifier displayed to users; UUID remains the API identity.';
comment on column public.resumes.resume_type is 'ORIGINAL is a primary Resume; TAILORED is an Application-specific derived variant.';
comment on column public.resumes.parent_resume_id is 'Original Resume from which a TAILORED Resume was derived; null for originals.';
