import { MESSAGE_TYPES } from "../shared/messages.js";
import { normalizeUrl } from "../shared/normalization.js";
import { suggestControlledCategory } from "../shared/categories.js";
import { normalizeSeniority,SENIORITY_VALUES } from "../shared/seniority.js";
import { detectSkills,canonicalizeSkills } from "../shared/skill-detection.js";
import { detectJobConditions,parseResumeSections } from "../shared/structured-parsing.js";
import { detectIndustryDomain as detectIndustryDomainSlug } from "../shared/industry-domain.js";
import { detectSalary } from "../shared/salary-detection.js";
import { validateJob } from "../shared/validation.js";
import { scoreMatch,summarizeBatch } from "../shared/matching.js";
import { validateSupabaseConfig,getSupabaseClient,loadConfig } from "../services/supabase-client.js";
import { signIn,signOut,currentSession } from "../services/auth-service.js";
import { getMyAccessContext } from "../services/access-service.js";
import { canReadBusiness,canWriteBusiness,extensionAccessMessage } from "../access/capabilities.js";
import { listCategories } from "../services/category-service.js";
import { listIndustryDomains } from "../services/industry-domain-service.js";
import { createJob,updateJob } from "../services/job-service.js";
import { createResume,listResumes,eligibleResumes,setResumeStatus,findActiveChecksum,updateResumeMetadata } from "../services/resume-service.js";
import { parseResumeFile,sha256Hex } from "../services/resume-parser.js";
import { createTailoringJobs,listTailoringJobs,cancelTailoringJob } from "../services/tailoring-job-service.js";
import { openPrivate } from "../services/storage-service.js";
import { AppError,safeError } from "../shared/errors.js";
const $=(id)=>document.getElementById(id), split=(value)=>String(value||"").split(",").map((x)=>x.trim()).filter(Boolean);
const optionalNumber=value=>String(value??"").trim()===""?null:Number(value);
const state={client:null,session:null,access:null,categories:[],industryDomains:[],savedJob:null,duplicateJob:null,matches:[],file:null,checksum:"",config:null,minimumScore:60,captureMethod:"manual",confidence:"low",activeUrl:""};
function node(tag,text="",className=""){const n=document.createElement(tag);if(text)n.textContent=text;if(className)n.className=className;return n;}
function show(message,kind="success"){const box=$("status");box.textContent=message;box.className=`show ${kind}`;box.scrollIntoView({block:"nearest"});}
function showView(name){document.querySelectorAll(".view").forEach((v)=>v.classList.add("hidden"));$(`${name}View`).classList.remove("hidden");}
function categoryById(id){return state.categories.find((c)=>c.id===id);}
function detectIndustryDomain(title,description){const slug=detectIndustryDomainSlug(title,description);return state.industryDomains.find((domain)=>domain.slug===slug)?.id||"";}
function fillCategories(select,includeAll=false){select.replaceChildren();if(includeAll)select.add(new Option("All",""));else select.add(new Option("Select category",""));state.categories.filter((c)=>!c.parent_id).forEach((c)=>select.add(new Option(c.name,c.id)));}
function fillSubcategories(parentId,select){select.replaceChildren(new Option("None",""));state.categories.filter((c)=>c.parent_id===parentId).forEach((c)=>select.add(new Option(c.name,c.id)));}
function populateControls(){[$("jobCategory"),$("resumeCategory")].forEach((s)=>fillCategories(s));fillCategories($("resumeFilterCategory"),true);[$("jobSeniority"),$("resumeSeniority")].forEach((s)=>{s.replaceChildren();SENIORITY_VALUES.forEach((v)=>s.add(new Option(v.replaceAll("_"," "),v)));s.value="UNSPECIFIED";});$("industryDomain").replaceChildren(new Option("Unspecified",""),...state.industryDomains.map((domain)=>new Option(domain.name,domain.id)));}
function mapCaptureMethod(value){return ({json_ld:"json-ld",known_selector:"site-specific",generic_selector:"dom",main_fallback:"dom",selection:"selected-text",manual:"manual"})[value]||"manual";}
function suggestionToCategory(title,description){const suggestion=suggestControlledCategory(title,description);return {suggestion,category:state.categories.find((c)=>!c.parent_id&&c.slug===suggestion.categorySlug)};}
const clearanceIds={clearancePublicTrust:"PUBLIC_TRUST",clearanceDodSecret:"DOD_SECRET",clearanceTopSecret:"TOP_SECRET",clearanceTsSci:"TS_SCI",clearanceOther:"OTHER_SECURITY_CLEARANCE"};
function jobPayload(){const travel=$("travelRequired").value;return {company:$("company").value.trim(),jobTitle:$("jobTitle").value.trim(),categoryId:$("jobCategory").value,subcategoryId:$("jobSubcategory").value||null,industryDomainCategoryId:$("industryDomain").value||null,seniority:$("jobSeniority").value,locationText:$("jobLocation").value.trim()||null,workArrangement:$("workArrangement").value,clearanceRequirements:Object.entries(clearanceIds).filter(([id])=>$(id).checked).map(([,value])=>value),travelRequired:travel===""?null:travel==="true",travelDetails:$("travelDetails").value.trim()||null,salaryMin:optionalNumber($("salaryMin").value),salaryMax:optionalNumber($("salaryMax").value),salaryCurrency:$("salaryCurrency").value.trim().toUpperCase()||null,salaryPeriod:$("salaryPeriod").value||null,salaryText:$("salaryText").value.trim()||null,sourceSite:$("sourceSite").value.trim(),sourceUrl:$("sourceUrl").value.trim(),descriptionText:$("descriptionText").value.trim(),detectedSkills:canonicalizeSkills(split($("detectedSkills").value)),captureMethod:state.captureMethod,extractionConfidence:state.confidence};}
function confirmClearanceRequirements(job){if(!job.clearanceRequirements.length)return true;const labels={PUBLIC_TRUST:"Public Trust",DOD_SECRET:"DoD / Secret",TOP_SECRET:"Top Secret",TS_SCI:"TS/SCI",OTHER_SECURITY_CLEARANCE:"Other security clearance"},requirements=job.clearanceRequirements.map((value)=>labels[value]||value).join(", ");const accepted=confirm(`Security requirement detected: ${requirements}.\n\nConfirm that you reviewed the job posting and want to save this requirement.`);if(!accepted)show("Save cancelled. Review the trust or security-clearance selections before saving.","warning");return accepted;}
function dbJob(job){return {company:job.company,job_title:job.jobTitle,category_id:job.categoryId,subcategory_id:job.subcategoryId,industry_domain_category_id:job.industryDomainCategoryId,seniority:job.seniority,location_text:job.locationText,work_arrangement:job.workArrangement,clearance_requirements:job.clearanceRequirements,travel_required:job.travelRequired,travel_details:job.travelDetails,salary_min:job.salaryMin,salary_max:job.salaryMax,salary_currency:job.salaryCurrency,salary_period:job.salaryPeriod,salary_text:job.salaryText,source_site:job.sourceSite,source_url:job.sourceUrl,normalized_source_url:job.sourceUrl?normalizeUrl(job.sourceUrl):null,description_text:job.descriptionText,detected_skills:job.detectedSkills,capture_method:job.captureMethod,extraction_confidence:job.extractionConfidence};}
async function saveDraft(){const job=jobPayload(),key=`capture-draft:${state.activeUrl||job.sourceUrl||"manual"}`;await chrome.storage.local.set({[key]:job});}
function resetCapture(){["company","jobTitle","jobLocation","travelDetails","salaryText","salaryMin","salaryMax","salaryCurrency","sourceSite","sourceUrl","descriptionText","detectedSkills"].forEach((id)=>$(id).value="");Object.keys(clearanceIds).forEach((id)=>$(id).checked=false);$("salaryPeriod").value="";$("industryDomain").value="";$("workArrangement").value="UNSPECIFIED";$("travelRequired").value="";$("jobCategory").value="";fillSubcategories("",$("jobSubcategory"));$("jobSeniority").value="UNSPECIFIED";Object.assign(state,{savedJob:null,duplicateJob:null,matches:[],captureMethod:"manual",confidence:"low"});$("captureMethod").textContent="manual";$("confidence").textContent="low";$("matches").classList.add("hidden");$("updateJob").classList.add("hidden");}
async function extract(type){show("Extracting the active page…","warning");const response=await chrome.runtime.sendMessage({type});if(!response.ok){show(`${response.error.message}${response.error.details?` ${response.error.details}`:""}`,"error");return;}resetCapture();const d=response.data,conditions=detectJobConditions({title:d.jobTitle,description:d.jobDescription,location:d.location,workArrangement:d.workArrangement}),salary=detectSalary(d.jobDescription,d.salary);$("company").value=d.company||"";$("jobTitle").value=d.jobTitle||"";$("industryDomain").value=detectIndustryDomain(d.jobTitle,d.jobDescription);$("jobLocation").value=conditions.locationText||"";$("workArrangement").value=conditions.workArrangement;conditions.clearanceRequirements.forEach((value)=>{const id=Object.keys(clearanceIds).find((key)=>clearanceIds[key]===value);if(id)$(id).checked=true;});$("travelRequired").value=conditions.travelRequired===null?"":String(conditions.travelRequired);$("travelDetails").value=conditions.travelDetails||"";$("salaryText").value=salary.text||"";$("salaryMin").value=salary.min??"";$("salaryMax").value=salary.max??"";$("salaryCurrency").value=salary.currency||"";$("salaryPeriod").value=salary.period||"";$("sourceSite").value=d.sourceSite||"";$("sourceUrl").value=d.sourceUrl||"";$("descriptionText").value=d.jobDescription||"";$("detectedSkills").value=detectSkills(d.jobDescription).join(", ");state.captureMethod=mapCaptureMethod(d.captureMethod);state.confidence=d.extractionConfidence||"low";$("captureMethod").textContent=state.captureMethod;$("confidence").textContent=state.confidence;$("jobSeniority").value=normalizeSeniority(d.jobTitle);const {suggestion,category}=suggestionToCategory(d.jobTitle,d.jobDescription);if(category&&suggestion.confidence!=="low"){$("jobCategory").value=category.id;fillSubcategories(category.id,$("jobSubcategory"));const sub=state.categories.find((c)=>c.parent_id===category.id&&c.slug===suggestion.subcategorySlug);if(sub)$("jobSubcategory").value=sub.id;}state.activeUrl=normalizeUrl(d.sourceUrl)||d.sourceUrl;await saveDraft();show("Job extracted. Review the detected salary, technology stack, industry domain, and requirements before saving.");}
async function requireAuth(){if(!state.session)throw new AppError("AUTHENTICATION_REQUIRED","Sign in before using this feature.");}
function requireBusinessWrite(){if(!canWriteBusiness(state.access))throw new AppError("ACCESS_DENIED","Your role does not allow this action.");}
function applyAccessUi(){const read=canReadBusiness(state.access),write=canWriteBusiness(state.access);document.body.classList.toggle("readonly-access",read&&!write);document.querySelectorAll('nav button[data-view="capture"],nav button[data-view="resumes"],nav button[data-view="queue"]').forEach(button=>button.classList.toggle("hidden",!read));["saveJob","updateJob","createJobs"].forEach(id=>$(id).disabled=!write);$("uploadDetails").classList.toggle("hidden",!write);$("accessHeading").textContent=state.access?.status==="INACTIVE"?"Account Inactive":!state.access?.roles?.length?"Pending Access":"Extension Access";$("accessMessage").textContent=extensionAccessMessage(state.access);enforceDynamicWriteControls();}
function enforceDynamicWriteControls(){if(canWriteBusiness(state.access))return;document.querySelectorAll("#resumeList button,#queueList button").forEach(button=>{if(/^(Edit metadata|Archive|Restore|Cancel)$/i.test(button.textContent.trim()))button.classList.add("hidden");});}
new MutationObserver(enforceDynamicWriteControls).observe(document.querySelector("main"),{childList:true,subtree:true});
function blockUnauthorizedWriteEvent(event){if(canWriteBusiness(state.access))return;const target=event.target,form=target?.closest?.("form"),button=target?.closest?.("button"),blockedForm=form&&["jobForm","resumeForm"].includes(form.id),blockedButton=button&&(["updateJob","createJobs"].includes(button.id)||/^(Edit metadata|Archive|Restore|Cancel)$/i.test(button.textContent.trim()));if(blockedForm||blockedButton){event.preventDefault();event.stopImmediatePropagation();show("Your role does not allow this action.","error");}}
document.addEventListener("submit",blockUnauthorizedWriteEvent,true);document.addEventListener("click",blockUnauthorizedWriteEvent,true);
async function loadMatches(){if(!state.savedJob)return;const resumes=await eligibleResumes(state.client,state.savedJob.category_id);state.matches=resumes.map((r)=>({resume:r,details:scoreMatch({categoryId:state.savedJob.category_id,subcategoryId:state.savedJob.subcategory_id,seniority:state.savedJob.seniority,detectedSkills:state.savedJob.detected_skills},{id:r.id,primaryCategoryId:r.primary_category_id,subcategoryId:r.subcategory_id,seniority:r.seniority,skills:r.skills,updatedAt:r.updated_at},state.minimumScore)})).sort((a,b)=>b.details.total-a.details.total);renderMatches();}
function renderMatches(){const root=$("matchList");root.replaceChildren();state.matches.forEach((m)=>{const card=node("article","","card"),row=node("label","","match-row"),check=document.createElement("input");check.type="checkbox";check.dataset.resumeId=m.resume.id;check.checked=m.details.eligible;row.append(check,node("span",`${m.resume.candidate_name} — ${m.resume.resume_name}`));card.append(row,node("p",`${m.details.total}/100 · ${m.details.eligible?"Eligible":"Below threshold"}`,"score"),node("p",`Category 50/50 · Subcategory ${m.details.subcategory.points}/20 (${m.details.subcategory.reason}) · Seniority ${m.details.seniority.points}/15 (${m.details.seniority.compatibility}) · Skills ${m.details.skills.points}/15`,"tags"),node("p",`Matched: ${m.details.skills.matchedSkills.join(", ")||"None"}. Missing: ${m.details.skills.missingSkills.join(", ")||"None"}.`,"tags"));root.append(card);});$("matches").classList.toggle("hidden",!state.matches.length);}
async function loadResumeList(){const rows=await listResumes(state.client,{status:$("resumeStatus").value,categoryId:$("resumeFilterCategory").value,search:$("resumeSearch").value});const root=$("resumeList");root.replaceChildren();rows.forEach((r)=>{const card=node("article","","card");card.append(node("h3",`${r.candidate_name} — ${r.resume_name}`),node("p",`${categoryById(r.primary_category_id)?.name||"Unknown"} · ${r.seniority} · ${r.status}`),node("p",r.skills.join(", ")||"No skills","tags"));const actions=node("div","","actions"),open=node("button","Open source"),edit=node("button","Edit metadata","secondary"),toggle=node("button",r.status==="ACTIVE"?"Archive":"Restore","secondary");open.addEventListener("click",()=>openPrivate(state.client,r.storage_bucket,r.storage_path,r.original_filename).catch(handle));edit.addEventListener("click",async()=>{const candidateName=prompt("Candidate name",r.candidate_name);if(candidateName===null)return;const resumeName=prompt("Resume name",r.resume_name);if(resumeName===null)return;const skills=prompt("Canonical skills, comma-separated",r.skills.join(", "));if(skills===null)return;await updateResumeMetadata(state.client,r.id,{candidateName,resumeName,primaryCategoryId:r.primary_category_id,subcategoryId:r.subcategory_id,seniority:r.seniority,skills:split(skills),industries:r.industries});await loadResumeList();});toggle.addEventListener("click",async()=>{await setResumeStatus(state.client,r.id,r.status==="ACTIVE"?"ARCHIVED":"ACTIVE");await loadResumeList();});actions.append(open,edit,toggle);card.append(actions);root.append(card);});}
async function loadQueue(){const rows=await listTailoringJobs(state.client,$("queueStatus").value);const root=$("queueList");root.replaceChildren();rows.forEach((q)=>{const jd=q.job_descriptions||{},resume=q.resumes||{},card=node("article","","card");card.append(node("h3",`${jd.company||"Unknown"} — ${jd.job_title||"Job"}`),node("p",`${resume.candidate_name||"Candidate"} · ${resume.resume_name||"Resume"}`),node("p",`${q.match_score}/100 · ${q.status} · ${new Date(q.created_at).toLocaleString()}`),node("p",q.review_notes||"No review notes","tags"));const actions=node("div","","actions"),open=node("button","Open source"),details=node("button","View match explanation","secondary"),jobDetails=node("button","Open JD details","secondary");open.addEventListener("click",()=>openPrivate(state.client,resume.storage_bucket,resume.storage_path,resume.original_filename).catch(handle));details.addEventListener("click",()=>alert(JSON.stringify(q.match_details,null,2)));jobDetails.addEventListener("click",()=>alert(`${jd.company||""}\n${jd.job_title||""}\nInternal JD ID: ${jd.id||""}`));actions.append(open,details,jobDetails);if(q.status==="PENDING"){const cancel=node("button","Cancel","secondary");cancel.addEventListener("click",async()=>{if(confirm("Cancel this pending tailoring job?")){await cancelTailoringJob(state.client,q.id);await loadQueue();}});actions.append(cancel);}card.append(actions);root.append(card);});}
function handle(error){const safe=safeError(error);show(`${safe.message}${safe.details?` ${safe.details}`:""}`,"error");}
function readSettingsForm(){return {config:{projectUrl:$("projectUrl").value.trim(),publishableKey:$("publishableKey").value.trim()},minimumScore:Math.max(0,Math.min(100,Number($("minimumScore").value)))};}
function writeSettingsForm(config,minimumScore){$("projectUrl").value=config.projectUrl||"";$("publishableKey").value=config.publishableKey||"";$("minimumScore").value=minimumScore;}
async function initialize(){const stored=await loadConfig();state.config=stored.supabaseConfig;state.minimumScore=Number(stored.matchingSettings.minimumScore??60);$("projectUrl").value=state.config.projectUrl||"";$("publishableKey").value=state.config.publishableKey||"";$("minimumScore").value=state.minimumScore;const check=validateSupabaseConfig(state.config);if(!check.valid){showView("settings");return;}state.client=getSupabaseClient(state.config);state.session=await currentSession(state.client);$("connection").textContent="Supabase configured";if(!state.session){showView("auth");return;}await enterAuthenticated();}
async function enterAuthenticated(){state.session=await currentSession(state.client);if(!state.session){showView("auth");return;}$("email").textContent=state.session.user.email;$("signOut").classList.remove("hidden");$("nav").classList.remove("hidden");try{state.access=await getMyAccessContext(state.client);}catch(error){state.access=null;applyAccessUi();showView("access");throw error;}applyAccessUi();if(!canReadBusiness(state.access)){showView("access");show(extensionAccessMessage(state.access),state.access.status==="INACTIVE"?"error":"warning");return;}[state.categories,state.industryDomains]=await Promise.all([listCategories(state.client),listIndustryDomains(state.client)]);populateControls();showView("capture");if(!canWriteBusiness(state.access))show(extensionAccessMessage(state.access),"warning");}
document.querySelectorAll("nav button").forEach((b)=>b.addEventListener("click",async()=>{showView(b.dataset.view);try{if(b.dataset.view==="resumes")await loadResumeList();if(b.dataset.view==="queue")await loadQueue();}catch(e){handle(e);}}));
$("settingsForm").addEventListener("submit",async(e)=>{e.preventDefault();try{const {config,minimumScore}=readSettingsForm(),check=validateSupabaseConfig(config);if(!check.valid)return show(Object.values(check.errors).join(" "),"error");await chrome.storage.local.set({supabaseConfig:check.normalized,matchingSettings:{minimumScore}});state.config=check.normalized;state.minimumScore=minimumScore;state.client=getSupabaseClient(state.config);writeSettingsForm(state.config,state.minimumScore);$("connection").textContent="Supabase configured";show("Settings successfully saved.");}catch(error){const safe=safeError(error);show(`Failed to save settings. ${safe.message}`,"error");}});
$("testConnection").addEventListener("click",async()=>{const button=$("testConnection"),originalText=button.textContent;button.disabled=true;button.textContent="Testing…";try{const {config}=readSettingsForm(),check=validateSupabaseConfig(config);if(!check.valid)throw new AppError("SUPABASE_CONFIG_INVALID","Failed to connect to Supabase.",Object.values(check.errors).join(" "));const client=getSupabaseClient(check.normalized),{error}=await client.from("categories").select("id").limit(1);if(error&&!/permission denied|row-level security/i.test(error.message))throw error;$("connection").textContent="Supabase connected";show(error?"Connection was successful. Sign in to access protected data.":"Connection was successful.");}catch(error){const safe=safeError(error);$("connection").textContent="Supabase connection failed";show(`Failed to connect to Supabase. ${safe.details||safe.message}`,"error");}finally{button.disabled=false;button.textContent=originalText;}});
$("continueToSignIn").addEventListener("click",()=>{const check=validateSupabaseConfig(readSettingsForm().config);if(!check.valid)return show("Save valid Supabase settings before signing in.","error");showView("auth");});
$("clearSession").addEventListener("click",async()=>{if(state.client)await signOut(state.client).catch(()=>{});for(const key of Object.keys(await chrome.storage.local.get(null)))if(key.startsWith("supabase-auth:"))await chrome.storage.local.remove(key);state.session=null;state.access=null;document.body.classList.remove("readonly-access");show("Supabase session cleared.");showView("auth");});
$("authForm").addEventListener("submit",async(e)=>{e.preventDefault();try{await signIn(state.client,$("authEmail").value,$("authPassword").value);await enterAuthenticated();show("Signed in successfully.");}catch(err){handle(err);}});
$("signOut").addEventListener("click",async()=>{await signOut(state.client);state.session=null;state.access=null;document.body.classList.remove("readonly-access");$("nav").classList.add("hidden");$("signOut").classList.add("hidden");$("email").textContent="";showView("auth");});
$("extract").addEventListener("click",()=>extract(MESSAGE_TYPES.EXTRACT_CURRENT_JOB).catch(handle));$("selection").addEventListener("click",()=>extract(MESSAGE_TYPES.EXTRACT_SELECTED_TEXT).catch(handle));$("resetCapture").addEventListener("click",resetCapture);$("editUrl").addEventListener("click",()=>{$("sourceUrl").readOnly=false;$("sourceUrl").focus();});$("jobCategory").addEventListener("change",()=>fillSubcategories($("jobCategory").value,$("jobSubcategory")));document.querySelectorAll("#jobForm input,#jobForm textarea,#jobForm select").forEach((field)=>field.addEventListener("change",()=>saveDraft().catch(()=>{})));
$("jobForm").addEventListener("submit",async(e)=>{e.preventDefault();try{await requireAuth();const job=jobPayload(),validation=validateJob(job);if(!validation.valid)throw new AppError("JD_VALIDATION_FAILED","Review the job fields.",Object.values(validation.errors).join(" "));if(!confirmClearanceRequirements(job))return;const saved=await createJob(state.client,dbJob(job));state.savedJob=saved;state.duplicateJob=null;$("updateJob").classList.add("hidden");show(`JD saved to Supabase: ${saved.company} — ${saved.job_title}.`);await loadMatches();}catch(err){if(err.code==="JD_DUPLICATE"){state.duplicateJob=JSON.parse(err.details).existing;state.savedJob=state.duplicateJob;$("updateJob").classList.remove("hidden");show("This source URL is already saved. Choose Update Existing JD to replace its reviewed fields.","warning");await loadMatches();}else handle(err);}});
$("updateJob").addEventListener("click",async()=>{if(!state.duplicateJob||!confirm("Update the existing JD with the currently reviewed fields?"))return;const job=jobPayload();if(!confirmClearanceRequirements(job))return;try{state.savedJob=await updateJob(state.client,state.duplicateJob.id,dbJob(job));show("Existing JD updated.");$("updateJob").classList.add("hidden");await loadMatches();}catch(e){handle(e);}});
$("createJobs").addEventListener("click",async()=>{try{const chosen=[...document.querySelectorAll("#matchList input:checked")].map((box)=>state.matches.find((m)=>m.resume.id===box.dataset.resumeId));if(!chosen.length)throw new AppError("NO_RESUMES_SELECTED","Select at least one resume.");if(chosen.some((m)=>!m.details.eligible)&&!confirm("One or more selections are below the score threshold. Queue them anyway?"))return;const results=await createTailoringJobs(state.client,state.session.user.id,state.savedJob,chosen),summary=summarizeBatch(results);show(`Created: ${summary.created}. Already queued: ${summary.alreadyQueued}. Failed: ${summary.failed}.`,summary.failed?"warning":"success");}catch(e){handle(e);}});
$("resumeCategory").addEventListener("change",()=>fillSubcategories($("resumeCategory").value,$("resumeSubcategory")));$("resumeFile").addEventListener("change",async()=>{try{state.file=$("resumeFile").files[0];if(!state.file)return;$("uploadProgress").textContent="Reading file · Extracting text";const buffer=await state.file.arrayBuffer(),parsed=await parseResumeFile(state.file),sections=parseResumeSections(parsed.text);$("resumeText").value=parsed.text;$("resumeSummary").value=sections.summary;$("resumeExperience").value=sections.professional_experience;$("resumeEducation").value=sections.education;$("resumeSkillsSection").value=sections.skills;$("resumeSkills").value=detectSkills(parsed.text).join(", ");$("uploadProgress").textContent="Computing checksum";state.checksum=await sha256Hex(buffer);$("uploadProgress").textContent=`Ready${parsed.warnings.length?` · ${parsed.warnings.join("; ")}`:""}`;}catch(e){handle(e);$("uploadProgress").textContent="Failed";}});
$("resumeForm").addEventListener("submit",async(e)=>{e.preventDefault();try{await requireAuth();const duplicate=await findActiveChecksum(state.client,state.checksum);if(duplicate&&!confirm(`This file matches active resume “${duplicate.resume_name}”. Create another categorized record anyway?`))return;$("uploadProgress").textContent="Uploading original file · Saving structured resume metadata";await createResume(state.client,state.session.user.id,{candidateName:$("candidateName").value,resumeName:$("resumeName").value,primaryCategoryId:$("resumeCategory").value,subcategoryId:$("resumeSubcategory").value,seniority:$("resumeSeniority").value,skills:split($("resumeSkills").value),industries:split($("industries").value),resumeText:$("resumeText").value,structuredContent:{summary:$("resumeSummary").value.trim(),professional_experience:$("resumeExperience").value.trim(),education:$("resumeEducation").value.trim(),skills:$("resumeSkillsSection").value.trim()}},state.file,state.checksum);$("uploadProgress").textContent="Completed";show("Resume uploaded privately with structured sections saved.");await loadResumeList();}catch(e){$("uploadProgress").textContent="Failed";handle(e);}});
[$("refreshResumes"),$("resumeStatus"),$("resumeFilterCategory")].forEach((x)=>x.addEventListener("click",()=>loadResumeList().catch(handle)));$("resumeSearch").addEventListener("change",()=>loadResumeList().catch(handle));$("refreshQueue").addEventListener("click",()=>loadQueue().catch(handle));$("queueStatus").addEventListener("change",()=>loadQueue().catch(handle));
initialize().catch(handle);
