import React,{useEffect,useState}from"react";
import{Alert,Button,Card,Checkbox,Col,Empty,Flex,Form,Input,InputNumber,Modal,Row,Space,Tag,Typography}from"antd";
import{createCandidateEducation,createCandidateEmployment,getCandidateProfile,updateCandidateEducation,updateCandidateEmployment,updateCandidateProfile}from"./candidate-profile-service.js";
const{Title,Text}=Typography;
const emptyEmployment={company:"",jobTitle:"",location:"",startDate:null,endDate:null,isCurrent:false,experienceDetails:"",displayOrder:0};
const emptyEducation={institution:"",degree:"",fieldOfStudy:"",location:"",startDate:null,endDate:null,gpa:"",details:"",displayOrder:0};
const dateInput=(value)=>value||undefined;
function EmploymentForm(){return <><Row gutter={12}><Col span={12}><Form.Item name="company" label="Company" rules={[{required:true}]}><Input maxLength={200}/></Form.Item></Col><Col span={12}><Form.Item name="jobTitle" label="Job title" rules={[{required:true}]}><Input maxLength={200}/></Form.Item></Col><Col span={24}><Form.Item name="location" label="Location"><Input maxLength={200}/></Form.Item></Col><Col span={12}><Form.Item name="startDate" label="Start date"><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="endDate" label="End date"><Input type="date"/></Form.Item></Col></Row><Form.Item name="isCurrent" valuePropName="checked"><Checkbox>Currently employed here (the end date will be cleared)</Checkbox></Form.Item><Form.Item name="experienceDetails" label="Achievements and responsibilities"><Input.TextArea autoSize={{minRows:5,maxRows:12}} maxLength={30000} showCount/></Form.Item><Form.Item name="displayOrder" label="Display order"><InputNumber min={0} max={1000}/></Form.Item></>}
function EducationForm(){return <><Row gutter={12}><Col span={12}><Form.Item name="institution" label="Institution" rules={[{required:true}]}><Input maxLength={240}/></Form.Item></Col><Col span={12}><Form.Item name="degree" label="Degree"><Input maxLength={200}/></Form.Item></Col><Col span={12}><Form.Item name="fieldOfStudy" label="Field of study"><Input maxLength={200}/></Form.Item></Col><Col span={12}><Form.Item name="location" label="Location"><Input maxLength={200}/></Form.Item></Col><Col span={12}><Form.Item name="startDate" label="Start date"><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="endDate" label="End date"><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="gpa" label="GPA"><Input maxLength={40}/></Form.Item></Col></Row><Form.Item name="details" label="Details"><Input.TextArea autoSize={{minRows:3,maxRows:8}} maxLength={10000}/></Form.Item><Form.Item name="displayOrder" label="Display order"><InputNumber min={0} max={1000}/></Form.Item></>}
const cleanDates=(value)=>({...value,startDate:value.startDate||null,endDate:value.isCurrent?null:value.endDate||null,displayOrder:Number(value.displayOrder)||0});

export function CandidateProfilePage({client,apiBaseUrl,id}){
 const[profile,setProfile]=useState(),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[editor,setEditor]=useState(null),[editForm]=Form.useForm(),[profileForm]=Form.useForm();
 const load=()=>{setError("");setProfile(undefined);getCandidateProfile(client,apiBaseUrl,id).then(setProfile).catch(x=>setError(x.message));};
 useEffect(load,[client,apiBaseUrl,id]);
 useEffect(()=>{if(!profile)return;const address=profile.addresses?.find(x=>x.isPrimary)||{},links=Object.fromEntries((profile.links||[]).map(x=>[x.linkType,x.url]));profileForm.setFieldsValue({fullName:profile.fullName,firstName:profile.firstName,middleName:profile.middleName,lastName:profile.lastName,email:profile.email,phone:profile.phone,addressLine1:address.addressLine1,addressLine2:address.addressLine2,city:address.city,stateRegion:address.stateRegion,postalCode:address.postalCode,country:address.country,linkedInUrl:links.LINKEDIN,githubUrl:links.GITHUB,portfolioUrl:links.PORTFOLIO,verified:profile.reviewStatus==="VERIFIED"});},[profile,profileForm]);
 async function saveProfile(values){setBusy(true);setError("");try{const links=[["LINKEDIN",values.linkedInUrl],["GITHUB",values.githubUrl],["PORTFOLIO",values.portfolioUrl]].filter(([,url])=>url).map(([linkType,url])=>({linkType,url}));const primaryAddress={addressLine1:values.addressLine1||"",addressLine2:values.addressLine2||"",city:values.city||"",stateRegion:values.stateRegion||"",postalCode:values.postalCode||"",country:values.country||""};const next=await updateCandidateProfile(client,apiBaseUrl,id,{fullName:values.fullName,firstName:values.firstName||"",middleName:values.middleName||"",lastName:values.lastName||"",email:values.email||undefined,phone:values.phone||"",reviewStatus:values.verified?"VERIFIED":"NEEDS_REVIEW",primaryAddress,links});setProfile(next);setNotice(values.verified?"Candidate Profile verified and saved.":"Candidate Profile saved as needing review.");}catch(x){setError(x.message);}finally{setBusy(false);}}
 function openEditor(kind,item=null){const defaults=kind==="employment"?emptyEmployment:emptyEducation,set={...defaults,...item,startDate:dateInput(item?.startDate),endDate:dateInput(item?.endDate)};setEditor({kind,item});editForm.setFieldsValue(set);}
 async function saveItem(){const values=cleanDates(await editForm.validateFields());setBusy(true);setError("");try{let next;if(editor.kind==="employment")next=editor.item?await updateCandidateEmployment(client,apiBaseUrl,id,editor.item.id,values):await createCandidateEmployment(client,apiBaseUrl,id,values);else next=editor.item?await updateCandidateEducation(client,apiBaseUrl,id,editor.item.id,values):await createCandidateEducation(client,apiBaseUrl,id,values);setProfile(next.profile||next);setEditor(null);setNotice(`${editor.kind==="employment"?"Employment":"Education"} saved.`);}catch(x){setError(x.message);}finally{setBusy(false);}}
 if(profile===undefined&&!error)return <div className="page"><Card loading/></div>;
 if(error&&!profile)return <div className="page"><Alert type="error" showIcon message="Candidate Profile could not be loaded" description={error}/></div>;
 return <div className="page"><a className="back-link" href={`#/resumes/${profile.resumeId}`}>← Back to Resume</a><Flex justify="space-between" align="center" wrap><div><Text type="secondary" className="eyebrow">Resume-scoped Candidate Profile</Text><Title level={1}>{profile.fullName}</Title></div><Tag color={profile.reviewStatus==="VERIFIED"?"green":"gold"}>{profile.reviewStatus.replace("_"," ")}</Tag></Flex>
 {error&&<Alert type="error" showIcon closable onClose={()=>setError("")} message={error}/>} {notice&&<Alert type="success" showIcon closable onClose={()=>setNotice("")} message={notice}/>}<Alert type="info" showIcon message="Review required" description="Values seeded from a Resume are not trusted automatically. Verify them before enabling future autofill."/>
 <Card title="Personal, contact, address, and links"><Form form={profileForm} layout="vertical" onFinish={saveProfile}><Row gutter={12}><Col xs={24} md={12}><Form.Item name="fullName" label="Full name" rules={[{required:true,max:200}]}><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="email" label="Email" rules={[{type:"email"}]}><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="firstName" label="First name"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="middleName" label="Middle name"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="lastName" label="Last name"><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="phone" label="Phone"><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="addressLine1" label="Address line 1"><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="addressLine2" label="Address line 2"><Input/></Form.Item></Col><Col xs={24} md={6}><Form.Item name="city" label="City"><Input/></Form.Item></Col><Col xs={24} md={6}><Form.Item name="stateRegion" label="State / region"><Input/></Form.Item></Col><Col xs={24} md={6}><Form.Item name="postalCode" label="Postal code"><Input/></Form.Item></Col><Col xs={24} md={6}><Form.Item name="country" label="Country"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="linkedInUrl" label="LinkedIn URL" rules={[{type:"url"}]}><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="githubUrl" label="GitHub URL" rules={[{type:"url"}]}><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="portfolioUrl" label="Portfolio URL" rules={[{type:"url"}]}><Input/></Form.Item></Col></Row><Form.Item name="verified" valuePropName="checked"><Checkbox>I reviewed these values and confirm they are accurate for this Resume.</Checkbox></Form.Item><Button type="primary" htmlType="submit" loading={busy}>Save Profile</Button></Form></Card>
 <Card title="Employment history" extra={<Button type="primary" onClick={()=>openEditor("employment")}>Add employment</Button>}>{profile.employment?.length?<Space orientation="vertical" size="middle" style={{width:"100%"}}>{profile.employment.map(item=><Card size="small" key={item.id} title={`${item.company} — ${item.jobTitle}`} extra={<Button onClick={()=>openEditor("employment",item)}>Edit</Button>}><Text>{item.startDate||"Start not recorded"} – {item.isCurrent?"Present":item.endDate||"End not recorded"}</Text><p className="long-text">{item.experienceDetails||"No details recorded."}</p></Card>)}</Space>:<Empty description="No structured employment history."/>}</Card>
 <Card title="Education" extra={<Button type="primary" onClick={()=>openEditor("education")}>Add education</Button>}>{profile.education?.length?<Space orientation="vertical" size="middle" style={{width:"100%"}}>{profile.education.map(item=><Card size="small" key={item.id} title={item.institution} extra={<Button onClick={()=>openEditor("education",item)}>Edit</Button>}><Text>{[item.degree,item.fieldOfStudy].filter(Boolean).join(" — ")||"Degree not recorded"}</Text><p>{item.startDate||"Start not recorded"} – {item.endDate||"End not recorded"}</p></Card>)}</Space>:<Empty description="No structured education."/>}</Card>
 <Modal open={Boolean(editor)} title={`${editor?.item?"Edit":"Add"} ${editor?.kind||"record"}`} onCancel={()=>setEditor(null)} onOk={saveItem} confirmLoading={busy} destroyOnHidden><Form form={editForm} layout="vertical">{editor?.kind==="employment"?<EmploymentForm/>:<EducationForm/>}</Form></Modal></div>;
}
